
=== あなたとBluetooth Low Energy技術 ===

通信には必ず相手が必要。相手に声が届く、声を理解できる、お互いに同じ会話をしようとしている、いろんな前提と同じ知識と意思
無線通信規格は、その前提の取りまとめ。それに従って作ることで、未だ見て事もない相手とでも通話ができる、運用できる。
言葉を覚えること、旅行で、あるいはその国で生活したい、商売や通訳になる。カタコトで良いのか、専門技能として必要なのか。


== 身近なBluetooth low energy技術とその活用 ==

放送サービスやネットワーク・サービスは、無線通信技術がなければ成り立ちません。ですが、安全な空気や水の存在を意識することがないように、無線通信技術はあることがあたりまえすぎて、普段はそれに気づくこともありません。

無線通信技術と一口に言っても、用途に合わせた様々な技術があります。そのなかで、Bluetooth low energy技術は、私達と身の回りにある"もの"との間にある、数十メートルをつなぐのに適した無線通信技術です。この章では、無線通信技術の基礎と、そしてBluetooth low energy技術の概要とその活用方法を見ていきます。

=== 身近にある無線通信技術 ===

1900年代は、電気の時代と言えます。毎日の生活に欠かせない洗濯機や冷蔵庫あるいは電子レンジなどの電化製品は、発明されたのはまだほんの100年ほど前、一般に普及し始めたのはここ70年ほどでのことです。電気のエネルギーは、電気モーターを回して肉体労働を肩代わりして、電球の光となり夜の暗闇を照らしています。

目には見えない電波で遠くに情報を伝える無線通信技術の発展と普及も、ここ100年あまりの出来事でしかありません。Bluetooth low energy技術も含めた無線通信技術は、生活のどのような場面で使われているのか、そして無線通信のなにが嬉しくて、あるいはなにが楽しいのでしょうか。

==== ホビーと無線通信技術 ====

イタリアのマルコーニ、船舶、大西洋通信、海底ケーブル、電信、有線通信、
1876年にマイクの発明、ベル。
1915年、真空管。
発明家たちが、送信機と受信機、長距離通信の記録競争、アマチュア無線家。商業化されて、通信機は購入するもの
// 長波（ちょうは、LF (Low Frequency) またはLW (Longwave, Long Wave)）とは、30 - 300kHzの周波数の電波をいう[1][2]。 波長は1 - 10km、
//電波、短波帯と呼ばれる周波数帯
//HF、3 - 30MHz）(100メートルから10メートル)
// 電波工学は、波長で分類。
// 日本の電波法では、実際の伝搬特性で区分。総務省令の無線局運用規則第2条第1項第5号が定義する、「4,000kHz から26,175kHzまでの周波数帯」の電波である。


//短波の波長は、１０～１００ｍで、約２００～４００ｋｍの高度に形成される電離層のＦ層に反射して、地表との反射を繰り返しながら地球の裏側まで伝わっていくことができます。
//長距離の通信が簡単に行えることから、現在でも、遠洋の船舶通信、国際線航空機用の通信、国際放送及びアマチュア無線に広く利用され、今後も需要が続く見込みです。

中学校の技術の授業で、4つの部品で組み立てるゲルマニウム・ラジオ、あるいは今であれば集積回路を使った高性能なラジオを組み立てた方も多いでしょう。見えないもの、作ったものが、音を出す。それも外から。

ラジコン。大昔は送信機と受信機すら自作している。目で見て操作する。だから片方向でいい。

短波の伝搬。アマチュア無線。そこからプロフェッショナル、無線通信機器を自作したり。1990年代には、商業化して。特に。国を超えて誰かと通話ができる唯一の手段。コンピュータネットワークを相互接続するインターネット技術が普及していない。

パソコン通信、個人そして商業サービス。サーバーに電話回線で接続する。サービス=回線接続。
//// 電子レンジが発明されたのは1945年、冷蔵庫は家庭用が1915年あたり、1900年。

目には見えない電波で遠くに情報を伝える無線通信技術は、不思議なものです。中学校の技術の授業で、4つの部品で組み立てるゲルマニウム・ラジオ、あるいは今であれば集積回路を使った高性能なラジオを組み立てた方も多いでしょう。私達の生まれた時から毎日の生活にある放送や通信や、それらを支える無線通信技術は、もうあることが当たり前すぎて、その存在にすら気づかなくなっています。この章では、身近にある無線通信技術を通じて、無線通信技術の基本を見ていきます。

めちゃくちゃ出力を強くしたら? 27MHzだと、文字通り世界の裏側に届く。それで嬉しい? 世界中のラジコンに混信して、自分の操作で動く。目で見えないから、そんなことになっても嬉しくはないし、誰もが迷惑をする。

==== 放送と無線通信技術 ====

伝搬。中波と短波。国際的な取り決め。電離層反射。周波数の割り当て。国ごと。衛星も、衛星通信。世界で追尾。衛星から見て世界のどこが見えているか、通信装置の仕様、運用に関わる。で周波数の切り替えとか大変。国が連携できるように、周波数の割り当て。


==== 通信と無線通信技術 ===

放送がエリア、相手を識別しない何か。通信、相手がいるもの。前世紀だと、特定の人。今だと、クラウドを経由して、ぼんやり。
通話している時間と、通話していない時間が明確。つながり続けていて、何が何やら。エディタ入力すら多人数で同時進行。

==== 周辺機器と無線通信技術 ===
ヘッドホンやイヤホン。売れる。半導体が高性能、できることが広がる。高音質化。買い換える理由。
マウスやヘッドホン。ワイヤレス。単に便利。繋がなくても。(便利ではない人もいるけど、ならばUSBのゆうせんで)

スマートホン、Android、BTクラシック。MFi互換。なんで広がらなかったんだろう?　通信接続、ちょうどイヤホンを差し込む。
だから、制約がなくても、外部装置=ユーザが設定アプリから接続しないと。




==== 事業と無線通信技術 ====

裏側、ラジオ放送。基地局、放送サービス。
課金要素、アナログだと無理か。、誰でも受信できる、その地域から受信料を取るか、装置を持っている人を見つけて、無償、広告モデル。ネット同じ。使う人が多いほど。

使えているものを、機器、支える人たち。それは仕事なので、楽しいかどうかは横に置いておいて。製造して販売、修理サポート、破棄してもらう。
壊れずにずっと使えることが、価値観であれば。普及期にはいいけど、だんだん売れなくなって、仕事としては成り立たない。
無線通信機器、技術が素晴らしくなる、感度がより高くなる。送信出力は決められているから。とは言っても違いはわかりにくい。
常に新しい顧客を見つける。ラジコン。大昔は送信機と受信機すら自作している。
アマチュア無線。

==== 極端な改造 ====



=== 無線通信とその楽しさ ===

仕組み:伝搬、周波数割り当て。
地方の中波放送、国際的な短波放送。周波数、割り当て。放送局。
特に短波と呼ばれる電波は、電離層反射で地球中に伝搬する。

通信の途切れにくさや速度、ハードウェアの製造価格など、その時代に使える技術で、いくつもの要素のバランスをとって

高品質で高速な通信技術は高価になりがちですし、低価格にすれば

人が利用する無線通信サービスには、通信がとぎれず高速な高品質の無線通信技術が用いられます。

ところで、私達の身の回りを見てみると、数多くのものがあります。しかし、その中に無線通信機能があるものは、ほとんどありません。このように、我々とものの間、あるいは、ものとネットワークの間には、まだ通信でつながっていない最後の1メートルがあります。Bluetooth low energy技術は、その最後の1メートルをつなぐのに適した無線通信技術です。



==== ホビーと無線通信 ====

==== 周辺機器と無線通信 ====
事業と開発。
ワイヤレスの産業。ハードウェア事業は、製造販売、在庫がなくなり、損害がなく廃棄してもらうこと。新規に作ることで売り上げ。


生まれた時にはすでにラジオやテレビジョンがあった私達は、ラジオを見ても驚いたりはしません。ですが、人類の歴史に初めて無線通信技術が登場したのは、まだほんの100年あまり前のことです。ラジオの登場は、単なる音が出る面白い装置の登場ではありませんでした。広い領域に同時に情報を伝えるラジオ放送やテレビジョン放送は、マス・メディアを生み出し、大量消費社会を牽引しました。無線通信技術の発明と発達は、私達の生活や社会そのものを大きく変化させてきたのです。

ラジコン、目に見えない配線、必要だけど特に。
確実に動くこと。







== Bluetooth low energy技術の登場とその活用 ==

21世紀に入り、私達の生活や社会は、デジタル・データの流れで動くようになりました。いわゆるインターネットと、パーソナル・コンピュータそしてモバイル機器が急速に普及しました。いまではスマートホンとソーシャル・ネットワーキング・サービスが、人々を常にネットワークにつなげています。

いつでもどこでも、インターネットを通じてネットワーク・サービスを利用できるのは、目には見えない電波で離れた場所に情報を伝える無線通信技術のおかげです。身近にある道具、例えばハサミや包丁あるいは自動車を見ても、全ての用途に使える万能のものはなく、様々な

=== Bluetooth low energy技術の概要 ===

Bluetooth low energy技術には、この技術だからこそ実現できるものや、この技術である必要はないがスマートホンという通信相手が普及しているから成り立つものなど、多種多様な利用場面がすでにあります。この技術の特徴とその活用方法とを、いくつかの具体的な利用場面を通じて見ていきます。

まず、キーボードやマウス、あるいは電子楽器やゲームコントローラーといった、ワイヤレスの入力機器があります。ワイヤレスですから、電源コードもなく電池で動きます。電源のオン・オフを意識されることはありません。そして、人間が操作すれば、その操作が画面や音出力に直ちに反映されるものです。

身につける小さな機器、またはウエアラブル・デバイスと呼ばれるものがあります。これは、靴または衣服やズボンのベルト、あるいはメガネや腕時計など、すでに身につける習慣があるものに、センサーと無線通信機能を追加するものです。人間の体の動きなどから活動量や睡眠状態を記録したり、メッセージの到着などを音や光で通知したりします。

ホーム・オートメーションあるいはスマート家電は、無線通信技術がさらなる採用を目指している分野です。それは、いままでにない新しい機器を提案するものではありません。従来からある機器に、無線通信を通じて動作状態を取得する機能とと動作を指示する機能とを追加する程度です。例えば、遠隔から部屋の温度を設定したり、音声で操作ができるなどの、新しい使い方や体験は、それらの機器の通信相手が提供します。

位置や近接検出にも用いられます。これは、絶対的な距離や方向がわかるわけではありません。受信電波強度の強弱から、電波を出しているビーコンまでの距離が、1メートル程度のとても近くなのか、10メートル以上のやや離れているのかが推定できる技術です。駅や空港の道順案内や、博物館の展示物解説アプリケーションの屋内位置推定、あるいは落とし物を発見するためのタグに近接検出として用いられます。

==== 無線通信規格と相互運用 ====

すべての利用場面は、Bluetoothという無線通信規格があることで成り立っています。通信には必ず通信相手がいます。Bluetooth無線技術は、電波がお互いに直接届く相手との間で、相互運用 (Interoperability) を提供します。相互運用とは、2つの何かが情報を交換して、お互いが交換した情報を活用できることを言います。

無線通信での相互運用の確保が、無線通信規格の役割です。Bluetooth無線技術は、製品が技術に適合しているかを認証して、認証に合格した製品がBluetoothのロゴを使用できる制度が運用されています。だから、Bluetoothの青色のロゴがついている製品であれば、どの製品同士を組み合わせても利用できます。相互運用が確保されているから、どの会社の製品であってもBluetoothのロゴを見て、安心して購入できます。

相互運用は、いま販売されている製品同士だけではなく、これまでに販売された製品との相互運用もあります。通信規格は、時代の進歩や要望に合わせて、技術の更新が必要です。ですが、Bluetooth無線技術は、周辺機器のようなハードウェアに使われる技術です。新技術を採用したことで、これまでに販売した製品との相互運用が失われれば、ロゴがもたらす安心感という価値が失われます。そのため、Bluetooth無線技術は、後方互換性を保ちます。

ワイヤレスのキーボードやマウスは、Bluetooth low energy技術が登場する以前から、製品がありました。これは周辺機器とUSB接続のレシーバーとを組みにしたもので、その間の無線通信は独自方式の技術が用いられています。パーソナル・コンピュータから見れば、USB接続のレシーバーがUSBマウスとして見えるので、無線接続のための設定やデバイス・ドライバのインストールの必要はありません。

ワイヤレスの周辺機器の無線通信技術は、目には見えない配線として機能すればよいものです。ですから、無線したい部分の両端に、お互いに相手の装置とだけ通信する送受信回路を置けばよいのです。その間の無線通信方式は、独自のものでかまいません。通信相手は装置で固定されますから、通信相手の設定すら必要なく、すぐに使用できます。

独自の無線通信方式での装置のワイヤレス化は、持ち運ぶことが前提のモバイル・デバイスでは成り立ちません。本体に余計な物をつけたくはないですから、無線通信の装置を外付けすることはできません。ですから、無線通信機能の本体内蔵が必要です。もしも独自の無線通信方式を採用すれば、そのモバイル・デバイスの開発会社が、周辺機器まで開発するほかなくなります。モバイル・デバイスが、一般に広く相互運用が確保された無線通信規格を採用していれば、その無線通信規格の認証がある周辺機器であれば、どれでも組み合わせられます。

==== Bluetooth low energy技術の特徴 ====

Bluetooth low energy技術の特徴は、無線通信の接続を超低消費電力で維持できること、無線接続の確立と切断とをミリ秒単位の短い時間で完了できること、そして多種多様なものをデジタル・データで表現する仕組みです。これら3つの特徴のお互いの組み合わせが、Bluetooth low energy技術の活用場面を広げています。そして、この技術の活用例は、既存製品をワイヤレス化するものと、この技術の登場により実現できたものの、2つがあります。

ワイヤレスのキーボードやマウスなどの入力機器は、今まであった製品をワイヤレス化したものです。配線がなくなれば、配線のからみに悩まされることもなく、机の上がすっきりします。ですが、配線は情報だけではなく電力も伝えています。つまり、既存機器のワイヤレス化は、無線通信機能を追加するだけではなく、電源を内蔵して単体で動くようにもしなければなりません。超低消費電力無線通信技術が、充電や電池交換の手間を十分に小さくしてくれます。

ワイヤレスのウエアラブル機器は、Bluetooth low energy技術で初めて実用的になる機器です。電力消費量が大きいほど、必要な電池容積は大きく、また頻繁な充電や電池交換が必要になります。身につけても邪魔にならない小さく薄く軽量で、たまに充電すればよい機器には、超低消費電力無線通信技術が必要です。

Bluetooth low energy技術では、ぱっと無線通信を開始して、必要な情報をぱっとやりとりできる仕組みになっています。そのため、通信相手の素早い発見と、発見した通信相手と短い時間で通信を開始できる工夫がなされています。これは、通信相手が通信可能範囲に入ったり出たりする場面に適しています。例えば、ウエアラブル機器は常に身につけていますが、スマートホンは机に置いたままかもしれません。そこで部屋の外に出れば、ウエアラブル機器からスマートホンに電波は届かなくなります。しかし、また部屋に戻れば、お互いに電波が届くようになり、通信を短い時間で開始できます。

この、Bluetooth low energy技術の、相手をぱっと発見する仕組みは、位置や近接検出に利用されています。電波を出すビーコンを建物のあちこちに設置すれば、ビーコンの検出情報から屋内位置を推定できます。また受信電波強度から、あるビーコンの近くにいることを検出できます。

Bluetooth low energy技術には、ジェネリック・アトリビュート(Generic ATTribute, GATT)という、ものの機能をデジタル・データで表現する仕組みがあります。これが、相互運用と多様性とを確保する鍵になっています。

例として、エアコンを操作するためのデジタル・データの表現を考えてみます。エアコンには、いくつもの機能がありますから、まず操作したい機能が何かを表現する必要があります。そして、その機能に何をさせるのかが続くでしょう。エアコンの運転の開始と停止で、エアコンの運転を数値1、そして、運転の開始を数値1、停止を数値0と決めたとします。動作開始は[1(運転の), 1(開始)]、動作停止は[1(運転の), 0(停止)]と表現できます。ここで、かぎかっこは数値の配列を表します。

この例のように、通信で機器を操作するために、対象と動作とを組みにしたコマンド体系が機器ごとに作られます。コマンドは、デジタル・データを流し続けるヘッドホンとは違い、動作を指示する少しのデジタル・データを、動作を指示する時に送ればよいだけなので、Bluetooth low energy技術の、ぱっとつながり、ぱっと通信ができる技術が適しています。

エアコンに付属する専用リモコンのように、通信する機器が1つに限定されるものであれば、この例のような独自設計したコマンド体系が使えます。ですが、このシンプルなコマンド体系では、様々な機器とつながるBluetooth low energy技術では、目的以外の機器を暴走させるかもしれません。例えば、偶然にエアコンと同じ機種名の自動車があり、その自動車と通信がつながり、エアコンだと思って送信した動作コマンドが、たまたま自動車のコマンドとしても有効で暴走を引き起こすかもしれません。

このような、思わぬものに影響を与えてしまうと困ります。そうならないように、GATTでは、例えば"エアコンの運転の"などの、機能のデジタル・データ表現に128ビット、10進数で38桁ものとても大きな数値を使います。独自設計で機能を勝手に定義しても、値の範囲があまりに広いので、他の機器の定義と値が衝突することはまずありません。この仕組みが、多種多様な機器を設計できる基盤なのです。

GATTは、機器とつながるスマートホンのアプリケーションでも重要な役割を果たします。パーソナル・コンピュータでは、デバイス・ドライバというソフトウェアを利用者がインストールして、アプリケーションから多種多様な周辺機器が利用していました。しかしスマートホンのオペレーティング・システムでは、利用者がインストールできるものはアプリケーションだけです。しかし、アプリケーションにはGATT基盤のインタフェースが公開されているので、アプリケーションにデバイス・ドライバに相当する機器を扱う機能が実装できます。

==== プロファイルとプラットフォーム ====

Bluetooth low energy技術は、電波をやりとりする物理層からGATTの仕組みまでが、コア仕様として定義されています。GATTを基盤にした、それぞれの機器や利用場面ごとの、具体的なデータ表現とその振る舞いの仕様をプロファイル(profile)と呼びます。無線通信を通じたもののデジタル・データの表現とその交換の仕組みと、その仕組を活用した振る舞いの仕様との分離が、相互運用性と多様性とを両立させる鍵です。

また、それぞれのソフトウェアや利用場面が共通して利用する基盤部分を、プラットフォーム(platform)と呼びます。Bluetooth low energy技術の活用では、無線通信の半導体から通信制御のソフトウェア・ライブラリまでが、コア仕様の機能を提供する基盤部分となります。GATTを基盤にしたプロファイルは、機器のアプリケーションとして実装されます。基盤部分が相互運用性を確保し、プロファイルは自由度が高いアプリケーションとして実装されることで、相互運用性と多様性とを実装します。

プロファイルは、任意のものが定義できます。例えば自社の研究成果で幸福度がわかるウエアラブル・デバイスが開発できたとします。そのような世界で初めての、類似する前例がない機器ではデータ定義が存在しません。そのような場合は、自分たちでGATT基盤のデータ表現およびプロファイルを作ります。それをカスタム・プロファイルと呼びます。スマートホンのアプリケーションは、GATT基盤のインタフェースが使えます。ですから、自社製品と対になる、自分たちのカスタム・プロファイルに対応したスマートホンのアプリケーションが開発できます。この機器とスマートホンのアプリケーションとの組み合わせから、相互運用性と多様性が生み出されます。

一方で、キーボードやマウスなどの一般的な機器は、どの製造会社のものであっても、一般的な機器として同じように使えなければ困ります。そのような一般的な機器では、プロファイルも相互運用性を確保する要素の1つです。そのために、Bluetooth無線技術の開発を監督している Bluetooth Special Interest Group (SIG), Inc. が採択したプロファイルがあります。採択済みプロファイルを採用する製品は、Bluetooth無線技術の認証過程で、その採択済みプロファイルを満たしているかも試験されます。

ですから、スマートホンのオペレーティング・システムは、対応したい一般的な機器の採択済みプロファイルを実装すれば、どの製造会社の製品でも使えるようになるのです。例えば、キーボードの採択済みプロファイルを実装したとしましょう。オペレーティング・システムには、製造会社に関わらず任意のキーボードが接続できます。オペレーティング・システムは、キーボードから送られてくるキー入力情報から、編集カーソル位置の移動や日本語変換などの複雑な処理をして、テキスト入力機能にします。アプリケーションは、入力装置がタッチパネルなのか、Bluetooth low energy技術で接続しているキーボードなのか、ハードウェアを気にすることなくテキスト入力機能が使えます。

カスタム・プロファイルと採択済みプロファイルは、お互いに排他的なものではありません。カスタム・プロファイルがあるからといって、採択済プロファイルを実装できなくなるわけではありませんし、その逆もしかりです。ですから、採択済みプロファイルを実装したキーボードでも、自社製品の設定機能を提供するカスタム・プロファイルを定義して実装するなどして、自社製品ならではの工夫ができます。カスタム・プロファイルと認証済みプロファイルとの違いは、Bluetooth SIGによる採択と認証があるかどうかの違いでしかありません。

カスタム・プロファイルで、独自の認証制度を運用することも可能です。例えば、Apple社は、HomeKitと呼ばれる家電製品をネットワークで連携動作させるカスタム・プロファイルを定義しています。Apple社の認証制度に合格したものだけが、HomeKitに準拠した製品として製造販売できることで、相互運用性が確保されています。

このようなプロファイルの柔軟な運用と、その組み合わせが可能なことが、多種多様な製品を生み出し、そして高い相互運用性の確保との両立を可能としています。

=== Bluetooth low energy技術の基礎 ===

Bluetooth low energy技術は、超低消費電力無線通信技術、ものをデジタル・データで表現するGATTという仕組み、そして、ものとの関わり方や使われ方を表すプロファイルという、いくつもの分野の異なる技術の要素で組み上げられています。

それぞれの技術要素ごとの基礎知識は、Bluetooth low energy技術の枠内で、できることを想像したり、できないことを予想するのに役立ちます。例えば、電波伝搬の基礎知識は、Bluetooth low energy技術を利用した電波ビーコンの振る舞いを想像するのに役立ちます。この技術は、受信信号強度から大雑把に距離を推定するため、その距離推定値は周囲の障害物や伝播経路の変化による、予測困難な振る舞いをします。その振る舞いが想像できれば、電波ビーコンを活用した利用者体験を立案して、電波ビーコンの設置や運用費用の見通しがたてられます。

また、Bluetooth low energy技術では実現できないと一般によく言われることが、なぜできないのかを説明するためにも、基礎知識が必要です。例えば、Bluetooth low energy技術では、スマートホンの電話通話はできません。これは、技術的に実現できないのではありません。採択済みプロファイルに、音声通話のプロファイルがまだないからです。ですから、自分たちのアプリケーションで通話ができるデバイスであれば、カスタム・プロファイルとして実現できます。もしも基礎知識がなければ、この実現できない場合と実現できる場合とがあるものを、どちらもできないと誤解したままかもしれません。

// レイヤーの話、物理層、電波の振る舞い、情報のやり取り(通信、相手がいる世界)
// 通信でいえば、届けばOK、届かない、切れる。ビーコン、思ったふるまいと異なる、物理との齟齬。
// 運用の話、電波法、BT認証制度、各国ごとに異なる電気製品の認証制度
// 守るべきタイミングと守るもの。

==== 無線通信技術の黎明期 ====

こすった琥珀が物をひきつけたり磁石同士に働く不思議な力は、紀元前前から知られていたようです。いまでは電場や磁場の働きとして理解できるこれらの現象の研究は、1800年のボルタ電池の発明から、急速に発展します。1820年にハンス・クリスティアン・エルステッドが、電流を流すと磁石に力が働く現象を発見します。これはアンペールが法則にまとめ、アンペールの法則と呼ばれています。さらに、1831年にマイケル・ファラデーが、電線の周りで磁石を動かすと電圧が発生して電流が流れる現象、電磁誘導を発見しました。

電気エネルギーは、人類にとって初めての、形のないまま扱えるエネルギーです。形がないので、薪や油のように、ものとしてエネルギーを運搬する必要がなく、張り巡らせた電線を通じて少ない損失で遠くまで送れます。また、小学校の理科教材で、電池で豆電球を光らせたり、電磁石で釘をひきつけたり、あるいは磁石と組み合わせたモーターを回転させる実験をしたように、電気エネルギーは熱や光あるいは動力に、用途に合わせて様々な形に変換して利用できる便利なエネルギーです。

エネルギーを遠くの相手に送る技術は、そのまま情報を遠くに伝える技術として使えます。電気エネルギーはまず有線通信技術として利用されはじめました。形がなく遠くまで小さな損失で送れる電気エネルギーの性質は、紙に染み込ませたインクのパターンで情報を記した手紙を運搬する郵便よりも早く、すぐに減衰する空気の振動エネルギーで音声をやりとりする会話よりも遠くに、情報を伝えます。

無線通信に用いている電磁波の存在は、1864年にジェームズ・クラーク・マクスウェルが、時間変化も含めて電場と磁場との関係をまとめたマクスウェルの方程式で示されました。電磁波は、時間変化する磁界が電界を、時間変化する電界が磁界を生じて、空間を伝搬する波です。計算から求めた電磁波の速さと、当時実験的に知られていた光の速さがほぼ同じであることから、光は電磁波だと示されました。

地球からの天体観測で何百億光年もの遠くにある星雲が観測できるように、電磁波を吸収したり遮る物体がない限り、空間には電磁波をそのまま伝搬させる性質があります。

理論が示した電磁波は、1888年のハインリヒ・ヘルツの実験によって、実験室でその存在が実際に示されました。その功績をたたえて、その名前は周波数の単位ヘルツ(Hz)に使われています。1秒あたり1回繰り返すことが1ヘルツです。信号を大きく増幅する能動素子がまだ発明されていない当時に、ヘルツは、花火放電で高速な電気信号のオンオフを生み出し、そこに共振回路を組み合わせて、電磁波を発生させました。
// Electric Waves: Being Researches on the Propagation of Electric Action with Finite Velocity Through Space
//Heinrich Hertz, 1893
// https://archive.org/details/b2172457x
// Dover Publications
// https://scholar.google.co.jp/scholar?cluster=15446997761183386650&hl=ja&as_sdt=2005&sciodt=0,5

有線通信と無線通信との違いは、エネルギーを伝送する媒体です。電気エネルギーを電線に閉じ込める有線通信は、低損失で長距離通信が実現できますが、通信できる場所は電線の両端に固定されます。電磁波が空間を広がっていく無線通信は、広い空間のどこかにいる相手が信号を受信できますが、受信できるエネルギー量は送信電力の極めて一部で、極めて小さなものになります。

1900年初め頃までの無線通信の通信距離競争は、強力な電気花火で送信電力を高めた送信装置と、ガラス管に金属微粉を詰めたコヒーラ管と呼ばれる、小さな電磁波のエネルギーで大きく電気抵抗が変化する素子を使った受信装置とを用いていました。しかし、小さなエネルギーの検出は難しい技術です。検出素子の感度を高めていくほど、周囲の光や温度あるいは振動や衝撃といった、ささいなことが大きな影響を与えます。また、小さなエネルギーがあることを検出する素子では、信号が検出されても、それが受信したい信号なのか、あるいは雷などの自然現象や他の送信者の信号なのかが区別できず、周囲環境と混信に対処ができません。

無線通信技術は、1900年代はじめから急速に進歩します。1906年にリー・ド・フォレストが3極真空管(三極管)を発明しました。この、小さな信号を大きく増幅する能動素子の発明は、信号の増幅や選択処理の電気回路をもたらしました。能動素子により、電磁波の送信装置は、一定の周波数の信号を安定して発生する発振回路と、その信号を歪みなく増幅する電力増幅回路とで、電気エネルギーを高効率に電磁波のエネルギーとして空間に送出するようになりました。また受信装置は、小さな受信信号を低雑音で増幅する受信回路と、受信信号のなかから送信周波数の信号だけを鋭く選択するフィルタ回路により、高感度で安定した受信ができるようになりました。

また1900年代はじめから、電磁波の伝搬特性の研究調査も進みます。地球という大きな球面のある1点から送信した電磁波は、宇宙に向かって広がる波と、大地や海に反射吸収される波、そして回折効果で球面に沿って伝搬する地表波の、3つの広がり方があります。地球球面上での通信は地表波が支配的だろうと思えますが、無線通信実験ではさらにより長距離に伝搬するらしいことがわかってきます。特にのちに述べる短波では、小さな送信電力でも何千キロメートルも伝搬することがわかり、この発見が国際通信や放送への道を切り開きました。

いくつかの実験により、上空100キロメートル以上に、薄い大気が太陽活動で電離した層がいくつかあり、それぞれの層ごとに、電磁波を減衰透過したり反射することがわかってきます。それらの層は電離層と呼ばれます。短波は電離層でちょうどよく反射されるため、遠くまで伝搬します。また電離層が太陽活動で生み出されるため昼と夜とでは伝搬が変化すること、さらに電離層で減衰をうけるか反射されるかは、電磁波の周波数で異なることがわかってきます。

花火放電による電磁波の送出とエネルギー検出による受信から始まった無線通信技術は、真空管の発明により、ある決まった周波数にエネルギーが集中した電磁波の送信装置と、その周波数を鋭く選択して目的外の電磁波の影響を排除できる、エネルギーではなく電気信号を処理する高い選択度と感度の受信装置、そして短波の伝搬特性の発見により、通信や放送へと急速に実用化が進みます。

==== 無線通信技術の普及 ====

誰も彼もが好き勝手に電磁波を送信すると、お互いの放送や通信が混じり合い通信や放送が成り立たなくなります。黎明期から実用化に移行するには、電磁波をどのように社会で扱うか、そのルールづくりと運営が必要になります。

光もX線も電磁波ですから、まず無線通信に使う電磁波の範囲を決める必要があります。無線通信に使う電磁波を、電波と呼びます。周波数が3テラヘルツ以下、つまり波長が0.1ミリメートルよりも長い電磁波が、電波です。この3テラヘルツという値は、電気信号として扱える領域の上限の目安で、特に根拠があるわけではありません。ですが、もう1桁周波数が高い領域、30テラヘルツでは波長は10ミクロンです。この波長は室温で物体が輻射する電磁波のピーク波長程度、つまり赤外線ですから、もはや光として扱う領域です。
// テラ 10^12、ギガ 10^9 、メガ 10^6 、キロ 10^3
//SI接頭辞（エスアイせっとうじ）は、国際単位系 (SI) において、SI単位の十進の倍量・分量単位を作成するために、単一記号で表記するSI単位（唯一、質量の単位は例外でSI基本単位でないgに適用する）の前につけられる接頭辞である。
//国際単位系 (SI) 国際文書第8版（2006年）日本語版[1]や理科年表、日本工業規格（JIS Z 8203、JIS Z 8202、他多数）ではSI接頭語（エスアイせっとうご）と言う。また、計量単位令[2]（政令）や計量単位規則[3]（省令）では単に接頭語と言う。

また、電離層伝搬で広い範囲に伝わる周波数帯や、地球を周る衛星通信と世界各地の通信局とが通信するため、世界で同じ周波数を割り当てる必要がある用途があり、国境を超えて伝わる電波を財産として活用するためには、国際的な取り組みが必要です。

そこで、電波活用のための国際協力の維持と増進を目的として、国際連合の電気通信に関する専門機関、国際電気通信連合(ITU: International Telecommunication Union)があります。その無線通信部門（ITU-R: ITU Radio communication Sector)では、無線通信に関する国際的規則である無線通信規則（RR: Radio Regulations）の改正、無線通信の技術・運用等の問題の研究、 勧告の作成及び周波数の割当てや登録等が行われています。その国際的な枠組みもとで、それぞれの国での電波資源はそれぞれの国で監理されています。日本では、総務省が電波利用に属する全てを、電波法のもとで監理しています。

//周波数の区分、工学の分類と行政
そして、電波は、その波長により伝搬特性が大きく異なるため、電波は波長範囲で区分されます。工学での分類は、波長が1,000メートルから10,000メートル、周波数でいえば30キロヘルツから300キロヘルツの範囲を、長波と呼びます。波長が100メートルから1,000メートルが中波、10メートルから100メートルが短波、1メートルから10メートルが超短波、0.1メートルから1メートルが極超短波と、波長1桁ごとに名前がつけられています。

電波の周波数は、光の速度を波長で割れば求まります。光の速度は毎秒299,792,458メートルで、30万キロメートルとしても1000分の0.7程度しか違いませんから、約30万キロとしても、計算結果は最初の3桁は同じです。波長が1メートルで周波数が300メガヘルツだと覚えておくと、これを基準にして波長と周波数の換算が簡単にできます。

電波区分を周波数で書き直すと、長波は30キロヘルツから300キロヘルツ、中波が300キロヘルツから3メガヘルツ、短波が3メガヘルツから30メガヘルツ、超短波が30メガヘルツから300メガヘルツ、そして極超短波が300メガヘルツから3ギガヘルツとなります。

また、電波行政での分類は、短波帯のように、"帯"をつけて区別されます。短波帯は4メガヘルツから26.175メガヘルツまでの周波数帯と、短波とは区分が異なります。これは、実利用で主に電離層による伝搬で利用される周波数帯を、短波帯と区分しているためです。
// 短波帯の定義は、総務省令の無線局運用規則第2条第1項第5号で定義されています。

電波は周波数で伝搬特性や伝えられる情報量が大きく違ってきますから、周波数は区分されて適した用途に割り当てて監理されます。また、ラジオ放送やテレビジョン放送では、放送という用途に割り当てた周波数区分のなかを、さらに1つ1つの放送に割り当てるチャンネルに分割して、そのチャンネルを事業者に割り当てていきます。

一般家庭での電波利用は、放送から始まりました。1925年には、日本初のラジオ放送が周波数800キロヘルツ(波長375メートル)の、中波で開始されました。中波ラジオは、ちょうど糸電話と同じように、音の強弱をそのまま電波の強弱にして送信する振幅変調(しんぷくへんちょう、AM、英語: Amplitude Modulation)方式を用いています。

そして1953年には、日本でテレビ放送が、超短波(ちょうたんぱ、VHF、英語: Very High Frequency)で開始されます。映像は音のようには簡単に電波で送ることはできません。アナログ方式のテレビジョンは、2次元の映像を左から右そして上から下へと走査して1つの信号の強弱に変換する撮像管と、それを電波の変化として送信する変調方式、そして受信信号を画像として表示するブラウン管という、通信と素子の特性を組み合わせる工夫で、初めて実現されました。

無線通信で単位時間あたりに伝送できる情報の量は、その通信に使う周波数の幅、帯域幅(たいいきはば、英:Bandwidth)に比例します。そして、電波の波長を1/10にすれば周波数は10倍になり、使える周波数の広さは10倍に広がります。無線通信技術は、能動素子の性能が向上して、より高い周波数の信号を取り扱えるようになるほど、より多くの量の情報を伝えられるようになります。

ラジオは、100ヘルツから7.5キロヘルツまでの音信号を、15キロヘルツの周波数帯域幅で送信しています。テレビジョン放送は、人間の目の残像を利用するために1秒に30枚もの画像を送るために、6メガヘルツの周波数帯域幅を使います。テレビジョン放送には、ラジオ放送に比べて400倍の周波数帯域幅が必要ですが、テレビジョン放送の電波の周波数はラジオ放送のそれに比べて100倍以上だから、それだけの周波数帯域幅が確保できます。

放送は、番組という情報を地域の受信者達に一方向に伝えるもの、つまりブロードキャストすればよいものです。ですから、回折効果が大きな中波を用いるラジオ放送ならば、平地に大きな放送局を配置します。周波数が高く回折効果が望めない超短波や極超短波を用いるテレビジョン放送は、放送地域であればどこからでも放送アンテナが直接見通せるように、山頂や放送用タワの最上部に放送アンテナを設置します。

アナログ信号処理では、契約した受信者だけがサービスを利用できる技術の実現は困難です。したがって、アナログ方式のテレビジョン放送は、広告を収益として誰もが番組を受信できる形をとりました。視聴者数の大きさが、そのまま広告収益の大きさになるため、より高い視聴率が得られる、より人気の高い番組が制作されます。そして、放送を通じて、便利な電化製品がある新たな生活場面が広く知られるようになり、それが需要を生み出し大量生産大量消費時代を生じさせました。

放送に続いて、私達の生活に普及したのが移動体通信システム、いわゆる携帯電話やスマートホンです。1980年台にはアナログ方式の第1世代移動体通信システムのサービス提供が始まりました。1990年台始めから提供された第2世代移動体通信システムでは、通信はデジタル化されて、音声情報のデジタル・データ変換技術との組み合わせになります。そして、1990年台おわりに登場する第3世代移動体通信システム以降は、いわゆるインターネットの利用が求める高速かつ大容量のデータ通信のために、高速化が進められています。

放送と異なり、利用者それぞれとの通信を提供する移動体通信システムは、利用者数分の通信帯域を必要とします。そのため、第1世代のシステムでは、電波の周波数は800メガヘルツと、放送よりも高い周波数が用いられていました。そして、通信の高速化が求める周波数帯域を確保するために、1.5ギガヘルツから3.5ギガヘルツへと、より高い周波数が用いられてきています。

移動体通信システムでは、利用者との通信の直接の相手となる基地局の配置設計が重要になります。1つの基地局の通信可能な領域が広いほど、基地局の数が少なくなり、設備投資費用が小さくなります。

電池容量に限りがある携帯電話では、送信電力をむやみには大きくできません。基地局が対応できる領域の大きさの上限を決める要素はいくつもありますが、仮に、基地局と携帯電話とがお互いに直接見通せる距離としてみます。人の目線の高さから見える水平線までの距離が約5キロメートル程度ですから、領域の半径は数キロメートルになります。また、利用者の密度が高い地域では、基地局と通信できる範囲にいる多くの利用者が必要とする通信帯域が、基地局が使える周波数帯域で提供できる通信帯域を超えてしまいます。そのような地域では、提供する通信帯域で、基地局1つがカバーする領域を細分化していきます。

携帯電話は、免許を持たなくても誰でも利用できる無線設備でもあります。電波の利用は、無線設備は法律を満たす設備かを確認して免許状を発行し、無線設備管理や運営には、資格試験に合格して十分な能力があると示した免許証を持つ人たちがあたることで、保たれていました。

しかし、携帯電話は誰でもが使えなければ、普及しません。




電波を活用。機器の改造、機器認証制度、相互運用の確保、機器認証、免許制度
いつでもどこでも電話ができる携帯電話は、急速に普及していきました。


月額課金、個人利用。便利さ、いつでもどこでも連絡できる、ネットワークを通じたサービスを利用できる、iモード、毎秒9600ビット、ほぼテキストベースの、そしてスマートホンではApple社のiPhoneおよびGoogle社のAndroidの2大プラットホーム、アプリと課金。グローバルなサービスが、その役割を担う。



放送、通信へ。固定装置からモバイル装置。 1990年台から
アナログからデジタルへ、1990年台、1995年のWindows95の発売やPentiumシリーズ、高速化

直接通信できる範囲、情報量、周波数のより高い、局所、局所の制御に至るまで。
高速デジタル、モバイル、つながった形
//====
//高度なデジタル通信技術の普及 ====







半導体技術の高度化、Windows95、OSと半導体、通信を通じて、アプリケーション。
莫大な投資が必要なものが、整備されたものと見ればいい。半導体も、放送局、基地局網。
高速なデジタル通信、ADSL、光ケーブル、無線通信。
常に利用できる、ワイヤレス、環境。
デジタル、アプリケーション次第で、手元のものが化ける
決済、プラットホーム。


デジタル情報処理技術、半導体が実現可能範囲。低価格で。
機器のあり方。誰でも電波を出せる機器を持って使う時代、移動する。機器認証制度。
つながり続ける、情報の流れ、課金。クレジットカードなど個人の契約、集約。iモード、モバイルOS
ネットワーク接続の入り口、ハブでもある。

ラジコン、市民無線とかあったけど。免許が必要な、アマチュア無線。
使う人が免許なしに、購入するだけで、誰でも利用可能。

放送では、受信機なので、電波法いらない、
初めて電波を出すものとしての携帯電話の普及。
免許ではなく、道具として使う。
認証制度、電波法と、個別のもの。
機器で。試作品、数を作らないもの、全数検査。大量に同じものを製造するもの、工事認証。
電波を出しても、ご迷惑にならないもの(機能する必要はない)
携帯電話であれば、規格認証、無線LANとWiFi、BLEなど(機能する、通信相手、システムに組み込める)
特許、ブランド、商標。それぞれ、ライセンシング。料金をとって運営する。なんらかの。

技術基準適合証明・工事設計認証」

携帯用、車載用等の小規模な無線局の増加に対応して、証明を受けた無線設備を使用して無線局の開設申請を行う場合は予備免許と落成後の検査が省略されるなど、無線局免許事務の簡素合理化と免許申請者の利便の増進を図るため、昭和56年5月23日に電波法が改正されて、「技術基準適合証明」の制度が、設けられました。（電波法第38条の6第1項）

また、平成10年5月には、技術基準適合証明に加え、新たに民間における品質管理能力を活用することによる大量生産機種向けの制度として「工事設計認証」が導入されました。（電波法第38条の24第1項）


機器認証。電波法、接続。免許がなくても、機器認証。製造時に認証して。制度化。
BLEでも、機器認証。月額はいらない、自分がハブ。高速通信、2.4GHz、免許いらない。混在通信。

サービスの必然性。そしてサービスの課金が月額で徴収されるプラットホーム。それらを支えるのは、機種のIOT、相互接続試験、電波法、免許の要らない機器の認証制度で改造不可能にして提供される端末。免許の事業者割り当て。空間の通信容量を事業者が調整する責任と義務。月額課金。音声通話ではリアルタイムなやりとり。サービス利用のための端末への切り替え、メール、非同時のやりとり。

放送では、電波の割り当て、放送設備、受信機まで含めて1つのシステム。
周波数の割当は土地の割り当て、商売を始めようとすればそこしかない。逆にアナログ、料金徴収
費用がかかるし、視聴しているかどうかの確認は不可能。配線がないから無線なので。
法律で、受信機があれば徴収する運営。

移動体通信とそのデジタル化は、それまでの放送とはまるで違う収益構造。
通信自体がサービスだから、通信で使える=SIMカード、利用者の認証、通信、お互いのやり取り。
どこでも通話ができる電話機から、どこでもサービスをうけられる窓口。
第2世界移動体通信システムで、毎秒9600ビットのデジタル・データ通信が可能になりました。
iモード、世界初の携帯電話IP接続サービスである。
月額課金文化、料金の徴収を代行したこと、

i-mode、常に利用できる、道案内や予約。パソコンで固定ではなく。
キャリア課金、サービス利用料金、月額。かなりの金額。通信料で、なので個別契約不要、とりっぱぐれがない。サービスの参入、ブラウザゲームからネイティブアプリ。OSがOSとして、SDK。課金はアプリ。



















==== Bluetooth無線技術とその変遷 ====

Bluetooth規格の開発を監督しているのは、1998年に設立された非営利の非株式会社 Bluetooth Special Interest Group (SIG), Inc. (Bluetooth SIG) https://www.bluetooth.org footnote:[Bluetooth SIG について https://www.bluetooth.org/ja-jp/members/about-sig-overview] です。

この Bluetooth SIG は Bluetooth対応製品の開発、製造、販売はしません。規格に参加するメンバーが多種多様な機器を接続するための望ましい無線技術を開発することより、Bluetoothブランドを強化することを使命としています。

Bluetooth SIGの主な任務は、次の4つです:

- Bluetooth 仕様の公開;
- 認証プログラムの管理運営;
- Bluetooth 商標の保護;
- Bluetooth 無線技術の普及促進。

認証プログラムには宣言と認証の2つがあります。"宣言"(Declaration)は、自社ブランドとしてBluetooth製品を一般販売する場合に必要です。無線モジュールを一切変更せずに組み込んだ自社製品や、設計製造会社の製品をそのまま自社製品として一般販売する場合は、宣言のみが求められます。

宣言する製品は、ヘッドホンなど電気量販店の店頭に並ぶような製品だけではなく、無線モジュールやスタックなどの、いわば製品を作るための部品も、宣言すべき製品に含まれます。宣言することで、Bluetooth無線技術の特許使用や商標利用が可能となります。もちろん、Bluetooth製品の卸や小売をするだけならば、宣言も認証も不要です。また、試作や評価段階では宣言は不要です。

なにかしらの設計をしたBluetooth製品には、宣言に加えて、"認証"(qualification)が必要です。これは、その設計されたものを試験してBluetoothの仕様を満たすと確認するものです。この認証プログラムは、設計で変更した部分を確認します。ですから、例えば無線モジュールにカスタム・プロファイルのアプリケーションを実装する場合は、追加したカスタム・プロファイルの部分だけを認証します。それ以外の、電波を出す部分やスタックは、無線モジュールの認証を引き継げます。

電波のやり取り部分の認証は、校正された高周波測定装置が必要ですから、認定機関に機器を持ち込み測定してもらいます。これには専門家に依頼するため相応の費用と時間がかかります。無線モジュールにカスタム・プロファイルを実装しただけならば、認証試験レポートの自己申告で済みます。このレポートは、オンラインでテスト手順を生成して、99ドルで販売されている試験装置に通すと、自分たちで生成できます。

//費用、年会費、宣言の費用。たくさんの企業、より多くの製品。登録。市場に出続けること。新技術開発の駆動力。
//宣言は、宣言ID(IDentifier, 識別子)を購入し、新しい申告を作成して、準拠宣言(DoC,Declaration of Compliance)に署名することで、完了します。宣言IDの価格は、2017年の時点で、年会費が無償のアダプターでは4,000米ドル、年会費が求められるアソシエイトメンバーでは8,000米ドルです。あるいは、最初のBluetooth製品を商品化するスタートアップ企業のためのイノベーション推奨プログラムが適用されれば、2,500米ドルになります。

//重要: 申告 (宣言) に複数の製品を含めることもできます。ただし、準拠宣言で参照される QDID を各製品が同様に実装している場合に限ります。これによって複数の DID を購入する必要がなくなります。

// 製品の宣言 https://www.bluetooth.com/ja-jp/develop-with-bluetooth/qualification-listing/declare-your-product

Bluetooth無線技術は、時代の要求にあわせて、新しいバージョンの規格を発表してきました。電波をやりとりする物理層に新しい技術を導入するたびに、仕様のメイジャー・バージョン番号が増えています。バージョン1.0仕様は1999年に公開されました。そして、2004年にBluetoothコア仕様バージョン 2.0 Enhanced Data Rate (EDR)が、2009年には Bluetoothコア仕様バージョン 3.0 High Speed (HS)が公開されました footnote:[社歴 https://www.bluetooth.com/ja-jp/media/our-history]。

2010年に公開された Bluetooth コ​​ア仕様バージョン4.0で、Bluetooth無線技術にBluetooth low energy技術が統合されました。この技術は、もともとは2006年にWibreeという規格として公開されたものです。その技術を、Bluetooth無線技術に、将来の発展も視野に入れて最小限の変更をして統合したものが、Bluetooth low energy技術です。

Bluetooth low energy技術の、デジタル・データを電波でやり取りする技術は、Bluetooth3.0までの技術とは異なります。統合したといっても、Bluetooth 4.0は、Bluetooth 3.0までの技術と、Bluetooth low energy技術の、2つの技術を内包したものです。そのため、Bluetooth 4.0では、Bluetooth 3.0までの無線技術とBluetooth low energy技術との両方に対応したデュアル・モードと、Bluetooth low energy技術のみに対応したシングル・モードとの、2種類があります。

Bluetooth無線技術は、バージョン3.0まで後方互換性を保ってきました。ですから、例えばバージョン2.0で製造された機器は、バージョン3.0の機器と接続し利用できます。Bluetoothの商標(ロゴ)があれば、そのバージョンを気にすることなく、安心して利用することができました。

ですが、Bluetooth 4.0では、Bluetooth 3.0まで保ち続けてきた後方互換性が、初めて一部失われました。2つの技術に対応するデュアル・モードであれば、すべての機器と接続できます。ですが、Bluetooth 3.0 までのBluetooth無線技術を採用している機器では、Bluetooth 4.0のシングル・モードの機器には接続できません。

このため、Bluetooth SIGは、コア仕様を公開した翌年の2011年10月に、Bluetooth 3.0までのロゴに加えて、Bluetooth 4.0専用のロゴを新たに発表しました。それが、Bluetooth 4.0のデュアル・モードにBluetooth Smart Ready、シングル・モードにBluetooth Smartという、2つの新しい商標(ロゴ)です。ですが、Bluetooth 4.0が広く普及した現在では、3つもあるロゴは利用者を混乱させるばかりです。そこで2016年からは、新しい青色で更新した1つの商標へ、切り替えが進められています。

コア仕様はバージョン4.0の公開から、短期間に仕様が更新されてきました。2010年のバージョン4.0の3年後に2013年12月に4.1が、その翌年の2014年には4.2が、さらに2年後に2016年に5.0が公開されました。これらの更新は、バージョン4.0との後方互換性を保ちながら、Bluetooth low energy技術に、より強固なセキュリティ、通信速度の向上、そして通信距離を延ばす技術を導入しています。

コア仕様の変遷をみると、新製品をこれから開発するならば、どのバージョンのコア仕様を選択すべきか迷うかもしれません。バージョンごとに、コア仕様の技術要素は増えていきますが、自分たちが使う技術はその全体ではなく部分です。また、Bluetooth 4.0以降は後方互換性は保たれていきます。ですから、自分たちが必要とする技術要素を決めれば、その技術が含まれているコア仕様以降であれば、どのバージョンを選んでもよいのです。

スマートホンの周辺機器ならば、Bluetooth 4.0でよいです。いくつかのBluetooth low energy技術の機器を集約してスマートホンに伝えるハブ・デバイス、例えば自転車のセンサー情報を集約してスマートホンに伝える機器や、家電製品の制御を取りまとめるコントロール・パネルのような機器などは、同時にセントラルとペリフェラルになれるBluetooth 4.1以降が必要です。また、HomeKitあるいはインターネット技術を使うものには、連続したデータをより効率よく扱えるBluetooth 4.2が適しているでしょう。


==== 無線通信とネットワーク・トポロジー ====

Bluetooth low energy機器をはじめとした、電波を送出する機器の試作や開発そして製造販売には、法律や認定制度があります。免許を受けずに車を運転していると無免許運転で逮捕されるように、免許や認定を受けずに勝手に電波を送出することはできません。

電波を受信するだけならば、周囲に影響を与えないので、厳しいルールは必要ありません。電波を送信するものには、電波の円滑な利用のためのルールづくりと、ルールのもとでの運用が必須です。ルールは、総務省が、利用目的ごとに周波数の範囲を割り当てて、電波の型式あるいは出力の大きさなどを決めます。ルールのもとでの運用は、免許制度または認定機器制度で保たれています。また不法な無線局の探査と取締りも行います。

電波の質が悪かったり、あるいは出力がむやみに大きすぎる無線局があると、同じ周波数範囲を使う他の無線局の通信を妨害します。また、割り当てられた周波数範囲に隣接している範囲での通信を、妨害するかもしれません。電波の質を、定めたルールの範囲に収めていくことが、必要です。

放送局などの通信設備は、免許制度で運営されます。無線設備は、自作したり、あるいは技術基準に適合した市販された無線設備を設置します。無線局の開局には、総務大臣の免許が必要です。無線設備と、その運用管理を担う国家資格を持つ無線従事者の資格と員数の審査と検査に合格して、初めて免許が交付されます。

ですが無線通信機器は、スマートホンやBluetooth low energy機器はもちろんコードレス電話など、私達の生活に必要なものです。それらの機器を使う前に、いちいち総務省に免許を申請してはいられません。そこで、目的や運用を特定して、技術基準適合証明を受けた無線設備だけを使用することで、免許および登録を必要としない無線局があります。これにより、私達は無線通信機器を購入して、すぐに使うことができます。

技術基準適合証明は、電波の質や出力の大きさが基準を満たしていること、また購入した人が電波の質を変えたり出力を上げたり改造が容易にできないことを求められます。電波を送出するBluetooth low energy機器は、製造販売時はもちろん試作品をいろいろな場面で試す時も、技術基準適合証明の取得が必要です。

電波が外に出ない電波暗箱あるいは電波暗室の中であれば、技術基準適合証明を取得していなくても電波を送出できます。ですが、使い勝手は実際に試作品を持ち歩いて使ってみなければわからないことが、ほとんどでしょう。

多種多様な無線通信を活用する製品の開発で、機器ごとに技術基準適合認定をうけると、たいへん費用がかかります。そこで無線モジュールと呼ばれる、電波を送出する電子回路部分を1つの部品にまとめたものが使われます。技術基準適合認定を受けた取得している無線モジュールを製品に組み込むと、その無線モジュールに付されている技術基準適合認定等の表示を製品に転記できます。無線モジュールを使うことで、試作段階から、電波を出すことができます。



ネットワーク・トポロジー
ネットワーク・トポロジー (network topology) は、コンピュータネットワークのトポロジー。数学的にはグラフ理論の応用として研究されている。一般的には、ネットワーク上のノード（英: node、「節点」あるいは「頂点」を意味し、具体的にはコンピュータやネットワーク機器など端末のこと）と、ネットワークの経路（エッジ、英: edge、「枝」や「辺」を意味する）との相関をダイアグラムで抽象化した概念のことである。
「ネットワーク構成」や「網構成」とも言う。論理的な意味のほか、物理的な実装形態でも用いられ、例えばFTTHの幹線網の網構成）も同様にネットワーク構成と言う場合がある。

周波数ごとに、情報量。エリア。
届く範囲が限定できる、思わぬ方向に届かない。基地局の整備、性質の異なる周波数帯、
単純に、情報量。
範囲、情報量。放送であれば1対多数、領域カバー。周波数の低い地表波、中波。
FM放送。超短波。広い周波数、高音質な放送。テレビ放送、超短波から極超短波。
470.3、704.、90、770

// 放送と通信、放送、ラジオからテレビ放送、
電気回路の高速化 = プロセッサの周波数と同じく、より高速、

扱う情報の量、周波数の幅、1つ区分が上がると、1桁多い情報量を扱える。しかし、短波よりも上の区分では、電離層反射は使えない。直接波、山の上やビルの上など、見通しが良い場所に、アンテナ。高いところから。高度情報化社会、扱う情報の量=周波数の幅、通信範囲を小さく区分、その掛け算。個人化。
短波放送、音声情報、広域で領域が全世界くらい。1方向の情報伝播。


// 電気通信事業法第68条の2


放送や通信に電磁波を活用するには、資源、混信、用途に合わせた利用目的、利用者、割り当て、
免許制度、電磁波の活用、放送や通信に、法律を作り制度の設計と運用、
電磁波は波長が水素原子数個分と、とても短いものまで生み出せます。しかし、すぐに吸収されて使い物にならない。通信である程度の範囲に伝搬するもの。可視光。範囲。
無線通信では便宜上、周波数3テラヘルツ以下の電磁波を電波と
電磁波といっても範囲が広い。電波、周波数3テラヘルツ以下、波長0.1ミリ以上、まで。
地球での電磁波の伝搬特性は周波数で大きく異るため、波長の範囲で区分があります。
また無線通信技術に使う電磁波の範囲を便宜的に3テラヘルツ、電波
水素原子数個分
無線通信につかう電磁波

==== 無線資源とその活用 ====

を発生させることができます。2.4ギガヘルツ

情報は、様々な表現の形をとることができます。例えば、文章を送るとします。手元には、何かのスイッチがあります。このスイッチを、短く押すことをトン、長く押すことをツーと呼ぶとしましょう。アルファベットのAにはトン・ツーとするなど、それぞれの文字にトンとツー記号を組み合わせた符号を割り当てて、それを送信者と受信者がお互いに覚えれば、文字列が送れます。このスイッチが、電線を通じて遠くにある電球を明滅させるならば、この情報の表現方式と電気エネルギーで、文章という情報を送れるようになります。

Bluetooth low energy技術をはじめとした、電波による無線通信技術は、今の私達の生活にはもはや欠かせないものとなっています。空間には電磁波を伝える性質があります。電磁波は波長で性質が大きく異なりますが、波長が0.1ミリメートルよりも長い電磁波を、無線通信に用いる電波と呼んでいます。

振動数、選択的に。小さい電力。信号処理、電気回路。
電流や磁界の関係電気工学の研究が、無線通信技術、電磁波、電波。無線通信技術
Bluetooth low energy技術をはじめとした無線通信は、電波
電磁波
波長が 100 μm 以上（周波数が 3 THz 以下）の「電波とは、人工的導体のない空間を伝搬する当面3000ギガヘルツ[1]より低い周波数の電磁波をいう[3]。」
無線通信には電磁波
無線通信の知識、資源、免許とかの制度。

超低消費電力無線通信技術、ものをデジタル・データで表現するGATTという仕組み、そして、ものとの関わり方や使われ方を表すプロファイルという、いくつもの分野の異なる技術の要素で組み上げられています。
1800年にイタリアの物理学者ボルタが発明した、ボルタ電池です。

電池の発明は、安定して流れ続ける電荷の流れ、電流をもたらし、電磁気学の研究が発達します。そして、1820年にハンス・クリスティアン・エルステッドが、電流を流すと磁石に力が働く現象を発見します。これはアンペールが法則にまとめ、アンペールの法則と呼ばれています。さらに、1831年にマイケル・ファラデーが、電線の周りで磁石を動かすと電圧が発生して電流が流れる現象、電磁誘導を発見しました。



今やったら大変。小さな電力を扱う技術。半導体回路、

周波数帯があること。アンライセンスドバンド。電波法で管理。免許。割り当てと設備。
誰でも使える、機器の認証制度。試作と製造と。日本では。
//-80dBm, 0dBm, -57dBm @ 1m, -20dBm , -88.5dBm @ 30m

届く広さ、その広さの中で周波数の幅。
Bluetooth low energy技術は、超低消費電力無線通信技術、ものをデジタル・データで表現するGATTという仕組み、そして、ものとの関わり方や使われ方を表すプロファイルという、いくつもの分野の異なる技術の要素で組み上げられています。
//==== 構成要素 ====


//==== Bluetooth low energy技術の基礎 ====
//無線通信:
//通信範囲と周波数。歴史的に。理論が先。通信競争、地球は球面、でも反射。
//用途で区分割り当て。だから、電波を周囲に出すものは免許or制度。
//アンライセンスドバンド、ライセンスドバンド。
//騒音問題。実験。暗箱、電波を外にもらさない何か。制度をパスしたもの。制度をパスさせたもの。
//モジュール、技適、工事認証。海外だとさらにVCCI。
// 80cmから1円玉、落ちる時間は0.4秒。エネルギー、7.8mJ。連続落とせば、19.6 mW
//他の方式。周波数帯、相互やりとり、速度、通信可能範囲な面積。料金。
//では、BLEの使っている周波数の性質は?

//用途と方式:で、低消費電力無線通信: 電力の大きさ、タイミングを合わせることで必要最小限。
//無線通信とは。電波を使うもの。めちゃくちゃ小さなエネルギー。
//ろうそくの炎。街灯、光。道を照らす光、その分、道の温度は上がっているが感じられない。
//920MHzの周波数を確保するために、色々移動した話。結構大変。時間もかかる、タイミングも必要。
// 電波、汚れきった電波の中で。前提がない。制御もできない。雑踏の中で。

// 超低消費電力無線通信技術、
Deprecated Specifications
https://www.bluetooth.com/specifications-dead/adopted-specifications/deprecated-specifications
Deprecated Bluetooth Core Specifications
 	​	Scope of Deprecation	Date of Deprecation Notice	Deprecation Notice Period	Date Deprecation Notice Period Ends	Recommended Alternative Specification
Bluetooth Core Specification v2.0 + EDR	​	Entire Specification	13-Nov-12	24 months	13-Nov-14	​Bluetooth Core Specification v5.0

==== Bluetooth low energy技術の特徴

// ものをデジタル・データで表現するGATTという仕組み、そして、ものとの関わり方や使われ方を表すプロファイル

この従来版Bluetooth無線技術の誕生と普及の影で、より低消費電力で低価格な新しい無線通信技術として開発が進められていたのが、Bluetooth low energy技術です。

Bluetooth low energy技術は、従来版Bluetooth無線技術を置き換える技術ではありません。従来版Bluetooth無線技術があまり使われてこなかった利用分野に向けて開発された、新しい技術です。

まず、Bluetooth low energy技術は、その名のとおり、超低消費電力の無線通信技術です。いままで無線技術が使われてこなかった製品に無線通信を採用すると、無線通信の分だけ消費電力が増えます。それにより電池交換の手間が増えて不便になったりしないように、無線通信は十分に超低消費電力でなければなりません。

従来版Bluetooth無線技術は、デジタル・データを連続してやり取りし続ける無線技術です。これは、音が途切れてはならないヘッドセットや、送信が中断してほしくないファイル交換などの利用分野では大切な技術です。ですが、途切れない安定した無線通信技術は、高品質なぶんだけ、複雑になり消費電力を小さくするのにも限界があります。

ですが、身の回りにある様々な機器に、デジタル・データを途切れなく連続してやり取りし続けるものは、あまりありません。例えば、テレビやエアコンのリモコンは、ボタンが押されときに、そのボタンの種類を送信するだけです。

ですから、従来版Bluetooth無線技術が連続してデータをやり取りし続けるのとは異なり、Bluetooth low energy技術は、少量のデータの低頻度でのやりとりを前提にして、超低消費電力無線技術を実現しています。

この超低消費電力無線通信は、無線通信を必要最小限の時間だけしか使わないことで実現できます。高周波信号をあつかう無線回路は、送信でも受信でも、動かすだけで大きな電力を消費します。ですから、送信側と受信側は、通信する時間をあらかじめ同期して、データをやり取りする時間だけ無線回路を動かし、通信が完了すればすぐに無線回路を停止するのです。

通信には2つの重要な性能項目、通信速度と遅れ時間があります。通信速度は、1秒で送信できるデジタル・データの量を、遅れ時間は、送信を開始したデジタル・データが実際に相手に届くまでにかかる時間をいいます。

この遅れ時間は、送受信側それぞれがお互いに無線回路を動かす周期(コネクション・インターバル)で決まります。この周期が短いほど、無線回路を動かす回数が増えるので、消費電力は増えます。

Bluetooth low energy技術は、この無線回路をオンにする周期を、7.5ミリ秒から4秒までの範囲で設定できます。例えば、楽器のように遅れ時間をできるだけ短くしたい利用分野はミリ秒単位の小さな遅れ時間を、また温度計のように遅れ時間がなくてもよい利用分野は、周期を長くして電力を節約するなど、利用分野それぞれに適した設定にできます。

また、Bluetooth low energy技術は、無線接続が切断することを受け入れる技術です。もしも、あらかじめ同期した時間に、来るべき無線信号がこなければ、その無線接続は切断したものとみなします。

従来版Bluetooth無線技術は、例えばヘッドセットでは通信が切断すれば音が途切れてしまうように、データが流れ続ける用途に使われます。ですから、接続が切れないよう高品質の無線通信に設計されています。

Bluetooth low energy技術は、少量のデータを低頻度でやりとりするものなので、通信が切断しても、再接続すればよいのです。また、Bluetooth low energy技術の機器の発見と接続処理は、場合によっては20ミリ秒程度と、とても素早くできるものに設計されています。

また、Bluetooth無線技術は、無線通信で機器を扱うための技術ですから、無線通信と同じくらいに、データ表現の仕組みが重要です。

従来版Bluetooth無線技術は、機器ごとに通信とデータ表現を組み合わせた最適な技術を提供しています。例えば、音声信号を送るという同じ機能でも、通話に使う電話通話向けでは遅れ時間の小ささが、音楽を聞く用途では高音質がと、異なる性能が求められます。

ですから、音声通話向けには、遅れ時間の小さい通信とその通信の特徴を活かせるデータ表現を、音楽鑑賞向けには、遅れ時間は大きくても高音質の大量のデータを遅れる通信と、その特徴を活かした高音質のデータ表現を、それぞれ提供します。

このように、利用分野に最適な技術の提供には、通信とデータ表現をうまく組み合わせることが不可欠です。ですが、Bluetooth low energy技術は、多種多様な機器に向けた技術です。従来版Bluetooth無線技術のように、機器ごとに時間と費用をかけて最適な技術を提供するわけにはいきません。

そこで、Bluetooth low energy技術は、GATT基盤アーキテクチャという仕組みを採用しています。このアーキテクチャは、機器の機能をデータベースとして表現する仕組みです。機器がサーバーに、スマートホンなどがクライアントになる、サーバー・クライアント モデルを採用しています。

このGATT基盤アーキテクチャで、通信とデータベースの読み書きとの組み合わせが最適化されています。このGATT基盤アーキテクチャ上で、機器の機能は、データベースのデータ形式として定義されます。ですから、機器ごとの開発はデータ形式を定義するだけで、GATT基盤アーキテクチャが提供する通信とデータ表現を組み合わせ最適化された技術が利用できます。

さらに、無線を通じて機器を利用するBluetooth low energy技術には、機器の所有や利用の権利を表現する仕組みがあります。無線通信では、機器の周囲にいる誰でもが電波を送信したり受信したりできます。ですから、通信相手が偽装ではなく信頼できる相手だと認証したり、その機器の所有や利用の権利があと認可するために、暗号技術と事前に交換された暗号鍵が持ちいられます。

この暗号鍵の交換と保存の機能は、ペアリングとボンディングと呼ばれます。ペアリングは無線接続時に暗号鍵を交換する機能です。ボンディングはペアリングで交換した暗号鍵を保存して、再接続時に保存した鍵を利用できる機能です。

このペアリングとボンディングを使って、所有や利用の権利を表現できます。例えば、血圧計があったとします。これがスポーツジムに設置されたものならば、それは誰が使ってもよい機器です。この場合は、ペアリングもボンディングもせず、任意のスマートホンからすぐに手軽に接続できるようにするでしょう。しかし、これが個人所有ならば、ペアリングとボンディングをして、所有者のスマートホンとだけ接続できて、かつプライバシーを守るために通信は暗号化するでしょう。

==== カスタム・プロファイルとアプセサリ

Bluetooth無線技術は、無線通信を通じて機器とアプリケーションがお互いに関係して機能を提供するための規格です。Bluetooth無線技術では、通信でデータをやりとりする手順の仕様をプロトコル、機器の振る舞いの仕様をプロファイルと呼びます footnote:[プロファイルの概要 https://www.bluetooth.com/ja-jp/specifications/profiles-overview]。

スマートホンやモバイル機器があたりまえになった時代に登場したBluetooth low energy技術は、パーソナル・コンピュータの時代にはなかった利用場面を生み出しています。

Bluetooth low energy技術は、GATT 基盤アーキテクチャを採用しています。これには、ジェネリック・アトリビュート・プロファイル(Generic Attribute profile, GATT Profile)という、機器の機能をデータベースとして表現する仕組みがあります。すべての機器のプロファイル、つまりふるまいは、このGATTプロファイルを使い表現されるデータベースと、そのデータベースへの読み書きの手順で定義されます。

プロファイルには、Bluetooth SIGにより採択された採択済みプロファイルと、任意のカスタム・プロファイルの2つがあります。

採択済みプロファイルは、例えばキーボードのような周辺機器のような、すでに市場があり機能も決まっている機器への、Bluetooth low energy技術の普及に不可欠です。機器設計製造会社は、採択済みプロファイルを実装して機器を製造販売します。オペレーティング・システムが、この採択済みプロファイルにしたがいデバイス・ドライバを実装してプロファイルに対応すれば、どの会社の製品であっても利用できます。

カスタム・プロファイルは、ユニークで多種多様のBluetooth Smart製品を生み出す鍵です。この分野では、アプリケーション(Application)とアクセサリ(Accessory)とが組み合わり初めて価値が生まれるということで、この2つの単語を組み合わせたアプセサリ(Appcessory)という造語が作られています。

スマートホンとそのアプリケーション開発環境の登場が、アプセサリを生み出しました。スマートホンでは、パーソナル・コンピュータのように、利用者がデバイス・ドライバを追加して新しい周辺機器に対応させることはできません。ですが、現在のスマートホンのソフトウェア開発キット(Software Development Kit, SDK)は、アプリケーション開発者にGATTプロファイルを公開しています。それを使うと、アプリケーションそれ自体が任意のプロファイルに直接対応できるのです。

アプセサリは大きく、機器の製造販売が原動力となるものと、サービス提供が原動力になるもの、2つに分類できます。

機器の製造販売が原動力となるものは、例えば筆圧や傾きを検出する電子ペンがあります。機器の設計製造会社は、カスタム・プロファイルを定義してペンを製造販売します。このペンに対応する描画アプリケーションが多ければ多いほど、より多くのペンが売れます。ですから、この会社は、アプリケーション開発会社と協業したり、アプリケーションからペンを使うためのライブラリを公開するなどして、対応アプリケーションを増やそうとします。

サービス提供が原動力となるものは、例えば腕時計型の活動量計があります。フィットネスを提供している会社は、自社のウェブ・アプリケーションやスマートホンのアプリケーションを魅力あるものにするために、それらと連携する腕時計型の活動量計を設計販売します。サービスの利用者が多いほど機器の売り上げが増えます。機器はサービスの売上と魅力の一部ですから、プロファイルを第3者に公開することはありません。

==== Bluetooth low energy技術の今後

Bluetooth low energy技術は、スマートホンのハードウェア対応と、GATTプロファイルのアプリケーション開発への開放で、スマートホンをハブとしたウエアラブル機器や電化製品に広く普及しました。

Bluetooth無線技術は、利用分野をより便利にさらに拡大するために、時代に合わせて技術更新を続けています。2010年にBluetooth4.0を公開してから、2013年にBluetooth4.1を、2014年にBluetooth4.2を公開しました。そして2016年にはBluetooth5の公開が予定されています。

Bluetooth4.1および4.2では、インターネット・オブ・シングス(Internet of Things, IoT)への対応が追加されました。

IoTとは、あらゆる物や物事がネットワークにつながることを言います。GATTプロファイルに最適化した無線技術そのままでは、世界中の機器とつながるためのインターネット・プロトコルを扱うには、ヘッダ情報などのGATTプロファイルにはないフィールドのために、通信効率が低くなります。そこでパケット長を拡大しています。またセキュリティ機能も高められています。

さらに、Bluetooth5では、IoT対応のさらなる強化や、音声通話や電化製品への分野拡大に向けて、1秒あたりのデータ通信速度を2倍に、また通信距離を2倍にする無線技術が導入されます。Bluetooth無線技術は、Bluetooth low energy技術を統合で、そのメイジャー番号を3から4に更新したように、無線通信の基本部分を更新したときに、規格のメイジャー番号をあげます。

通信速度の向上と通信距離の増大は、同時には得られません。データ通信速度の理論的な上限は、シャノンの定理から、送信電力とノイズ電力の比で与えられます。近距離でノイズの影響が少ない利用場面では、高速なデータ通信速度を、遠距離でノイズの影響が大きくなる利用場面には、エラー訂正符号を組み込むことで、遠距離の通信を可能とします。

通信速度が2倍になれば、IoT対応で通信データ量が増加しても、無線回路の使用時間を増やさなくてすみます。IoTの分野でも、Bluetooth low energy技術の、超低消費電力の体験が提供できます。

通信距離は、ウエアラブルよりも大きな通信距離が必要な家電製品の分野で重要です。直接通信できる距離を伸ばすだけではなく、メッシュ・ネットワークと呼ばれる、Bluetooth Smart機器同士がパケットを中継しあう自律的なネットワーク技術も登場します。

このような急速な新しい技術の取り込みは、通常はその採用機器の一般販売を阻害します。その規格を採用した機器を開発しても、一般販売を開始する頃には新しい規格が登場して使えなくなると消費者に思われると、機器を買ってもらえないからです。

ですが、Bluetooth無線技術は、これまで後方互換性を保持して市場にあるあらゆる機器との相互接続を確保してきた実績に裏付けられた、高いブランド力があります。Bluetooth4.0でのBluetooth Smart機器の登場という例外はありましたが、Bluetooth5そしてその後に続く規格でも、後方互換性が確保された、新しい技術の恩恵がうけられる運営が続けられるでしょう。






=== Bluetooth low energy技術の活用 ===















=== Bluetooth low energy技術の活用 ===

==== iPhoneとアプセサリ

世界で初めてBluetooth4.0に対応した機器は、2011年に発売されたiPhone 4Sです。それ以降、iPhoneも含む、全てのApple社製品がBluetooth low energy技術に対応しています。またiPhone 4Sに搭載されたiOS5のソフトウェア開発キットは、CoreBluetoothフレームワークを通じて、アプリケーション開発者にGATTプロファイルを開放しました。

ちょうど、iPhoneのアプリケーション開発キットとアプリストアが広く公開されて、個人や会社が様々なアプリケーションを販売するエコシステムが構築されたように、Bluetooth Smart機器の急速な普及もiPhoneを中心としたエコシステムによるところが大きいのです。

ここでは、iPhoneを中心としたBluetooth low energy技術の活用事例を見ていきます。

==== 従来版Bluetooth無線技術とiOSデバイス

iOSを搭載するiPhone、iPod touchおよびiPadなどをiOSデバイスと総称します。iOSデバイスの従来版Bluetooth無線技術での周辺機器は、キーボードやヘッドセットなどの一般的な周辺機器か、特定のiOSアプリケーションとだけ通信する専用周辺機器かの、いずれかのみが開発できます。

デバイス・ドライバをインストールして周辺機器を追加できるパーソナル・コンピュータとは異なり、iOSにユーザがインストールできるのは、アプリケーションのみです。ですから、iOSデバイスが対応するBluetoothプロファイルの周辺機器のみが利用できます footnote:[iOS：iOS デバイス対応の Bluetooth プロファイル, https://support.apple.com/ja-jp/HT204387]。

従来版Bluetooth無線技術で、プロファイルが定義されていない独自の機器には、シリアル・ポート・プロファイル ( Serial Port Profile, SPP )が使われます。シリアル・ポート・プロファイルは、その名前の通り、パーソナル・コンピュータのシリアル・ポートに相当する任意のバイナリ通信を提供します。

従来版Bluetooth無線技術でも、iOSデバイスとつながる独自の機器は開発できます。ですが、iOSはアプリケーションに、シリアル・ポート・プロファイルを開放していません。従来版Bluetoothを使うiOS周辺機器開発は、Apple社と Made for iPhone(MFi)プログラム と呼ばれる秘密保持契約を締結して、開発情報や開発機材の提供をうけて初めて開発できます。Bluetooth Smart機器をアプリケーション開発者に開放した現在でも、従来版Bluetoothの周辺機器はMFiプログラムに参加しなければ開発できません。

==== iOSとBluetooth Smart機器

2011年に発表されたiPhone4Sは世界で初めてBluetooth Smart機器に対応した端末です。そして、アプリケーション開発キットに含まれるCoreBluetoothフレームワークを通じて、一般アプリケーション開発者に、Bluetooth Smart機器と連携するアプリケーション開発が開放されました。

これは、ちょうどAppStoreが登場してアプリケーションの販売とアプリケーション内課金という収益が得られる場が生まれたことで、急激に数多くのiOSアプリケーションが登場した様子に似ています。

iOSとBluetooth Smart機器とのプロファイルには:

- 採択済みプロファイル
- カスタム・プロファイル
- iOS独自のプロファイル

の3つがあります。

キーボードなどの入力機器には、HID Over GATT Profile (HOGP) footnote:[HID Over GATT Profile (HOGP), https://developer.bluetooth.org/TechnologyOverview/pages/hogp.aspx] という採択済みプロファイルがあります。このHOGPは、従来版Bluetoothの、ヒューマン・インターフェイス・デバイス・プロファイル (Human Interface Device Profile, HID)を、GATT基盤アーキテクチャに移植したものです。

iOSはこのHOGPに対応していて、キーボードの接続をiOSが受けつけます。アプリケーションは、タッチパネル入力かキーボード入力かを区別することなく、文字入力機能を利用できます。また、iOSが管理しているプロファイルは、一般アプリケーションからは、CoreBluetoothフレームを通じても見えません。

キーボードは、アプリケーションがBluetooth Smart機器に直接接続する意味がない好例です。アプリケーションが必要とするものは文字入力機能であり、キーボードのキー情報の詳細ではありません。たとえキー入力が取得できたとしても、それを文字入力機能とするには、漢字仮名変換などiOSが元来提供している基本機能を、アプリケーション側に実装しなければなりません。

カスタム・プロファイルを利用するアプセサリについては、既に述べました。CoreBluetoothフレームワークを通じて、アプリケーションはBluetooth Smart機器との接続に、高い自由度を与えられています。

まず、ユーザが設定するほかないWiFiなど他の無線インタフェースと違い、Bluetooth Smart機器の検索と接続および切断を、アプリケーションで行えます。そして、アプリケーションが画面に表示されていないバックグラウンド状態でも、Bluetooth Smart機器との通信を続けられます。

この高い自由度を活かして、特にフィットネスや健康維持の分野で急成長する会社が登場しています。iOSアプリケーションを通じて提供されるサービスを生み出し初期の競争を生き残った企業が、今の成熟したモバイル市場で大きな売上を生み出しているのと同じように、アプセサリも規模の拡大と成熟を迎えていくでしょう。

==== iOS独自のプロファイル

iOSは、iOS独自にいくつかのカスタム・プロファイルを公開しています。それらは、iOSにしか提供できないもので、iOSのユーザ体験をより豊かにするためのものです。

プロファイルの仕様が一般に公開 footnote:[Bluetooth for Developers, https://developer.apple.com/bluetooth/] されているものは、次の2つです。これらは、MFiプログラムに参加してなくとも利用ができます:

- Apple Notification Center Service (ANCS)
- MIDI over Bluetooth low energy

つぎの4つのプロファイルは、MFiプログラムの中で提供されます:

- ゲームコントローラ
- iBeacon
- HomeKit

メールやソーシャルメディアの通知は、スマートフォン連携での定番の機能です。様ですが、々なアプリケーションからの通知情報は、ユーザのプライバシーの保護のために、iOSアプリケーションからは読み取れません。ですから、もしもiOSアプリケーションで通知機能を実現しようとすると、アプリケーション自体に様々なメールやソーシャルメディアの通知取得機能を実装しなくてはなりません。

Apple Notification Center Service (ANCS)、iOSデバイスに表示されている通知表示を、そのままBluetooth Smart機器に提供する機能です。ANCSを通じて、Bluetooth Smart機器は通知情報をiOSから直接取得できます。ANCSのおかげで、通知を取得するアプリケーションをいちいち作らなくても、通知を知らせるBluetooth Smart機器が開発できます。

MIDI（Musical Instrument Digital Interface、ミディ）は、電子楽器の演奏データを機器間でデジタル転送するための規格です。2012年にBluetooth low energy技術でMIDIデータをやり取りするカスタム・プロファイルが、2012年にApple Bluetooth low energy MIDIとして公開されました。この仕様は、2015年にMIDI本体の規格にそのまま取り込まれました footnote:[Specification for MIDI over Bluetooth Low Energy, https://www.midi.org/specifications/item/bluetooth-le-midi]。

Apple Bluetooth low energy MIDIは、iOSに深く統合されています。楽器のデータは、人間が気づかない程度の小さな遅れ時間で送らなくてはなりません。そのために、この仕様は、データ形式に加えて、コネクション・インターバルを15ミリ秒以下の小さな値にすることを決めています。

iOSが通常受け入れるコネクション・インターバルは20ミリ秒以上ですが、Apple Bluetooth low energy MIDI対応機器は、15ミリ秒以下のコネクション・インターバルを受けつけます。また、この仕様に準じる機器は、CoreBluetoothフレームワークではなく音を扱うためのCoreAudioKitフレームワークを通じて、アプリケーションからは楽器として扱えます。

このようにiOSは、楽器演奏のユーザ体験に不可欠な小さな遅れ時間を、例外的な通信パラメータの受け入れで提供しています。また、Bluetoth Smart機器ではなく楽器としてアプリケーションから見えるようにしたことで、AppStoreにある数多くの演奏アプリケーションが活用できるようにしています。

iOSの独自プロファイルは、豊かなユーザ体験に不可欠の技術を、通信とiOSのみが実装できる機能それぞれを統合して提供しています。またカスタム・プロファイルはiOSが扱い、アプリケーションからは単なる周辺機器として見えるので、既存のアプリケーションが、そのまま利用できます。

==== Bluetooth low energyとビーコン

iBeacon footnote:[https://developer.apple.com/ibeacon/] は、iOS7で導入された新しい位置と近接の検出技術です。Bluetooth low energyのアドバタイジング・パケットをブロードキャストするビーコンと、iOSの常時ビーコン検出の機能を組み合わせて使います。屋内の経路案内や博物館の展示案内あるいは紛失物の探索などに利用できます。

ビーコン検出機能は、位置情報を提供する CoreLocationフレームワークを通じて一般開発者に提供されています。開発者は Bluetooth low energy を意識することなくiBeaconを利用できます。

iOSは強力なビーコン検出を提供します。iOSデバイスが再起動してもビーコン監視は継続します。さらに、ビーコンを検出した時にアプリケーションが終了状態であれば、iOSがアプリケーションを起動して検出イベントをアプリケーションに通知します。

ビーコンは、CoreLocationフレームワークとCoreBluetoothフレームワークを使いiOSアプリケーションを使ってiOSデバイスをビーコンにするか、またはiBeaconのハードウェア仕様にしたがって製造したビーコンを利用します。このiBeaconのビーコン技術仕様はMFiプログラムの対象です。

Bluetooth low energyのアドバタイジング・パケットは、どの程度の周期で送出されるかが事前にわからないので、通常は、アドバタイジング・パケットを検出する間は、2.4GHzの高周波受信回路を動かし続けます。ですから、単純にアドバタイジング・パケットを利用するビーコンを24時間監視すると、消費電力が無視できない大きさになります。

iBeaconは、ビーコンのアドバタイジング・インターバルを規定します。そしてiOSは、その技術仕様を前提にして、iOSデバイスのハードウェアとソフトウェアとを最適化して、消費電力を小さくしています。このビーコンとiOSとの統合された最適化ではじめて、ビーコンの常時検出が実現されています。

ビーコンは、任意に設定できる128ビットの識別子(UUID)と2つの16ビット値を送出できます。iOSアプリケーションは、検出対象のビーコンのUUIDを必ず指定しなければならないので、周囲にある任意のビーコンを検出することはできません。ですから、誰かが設置したビーコンの識別情報を盗みだすスニッフィングなどの悪用はできないようになっています。

iBeaconは、iOS標準アプリのPassbook footnote:[Passbook for Developers, https://developer.apple.com/passbook/](https://developer.apple.com/passbook/] が利用しています。ビーコンがあるとロック画面にパスが表示されます。

==== HomeKitとBluetooth low energy

HomeKit footnote:[https://developer.apple.com/homekit/] は、照明機器や電子錠などの身の回りにある機器とiOSデバイスとを、 Bluetooth low energy または Wi-Fi で連携させる技術です。HomeKitは、Siriを通じて自然な音声コマンドで機器が操作できるという、映画では見慣れた誰もが理解しているアプリケーションを提供しています。

機器が連携さえしていれば、サービス提供者やアプリケーション開発者が工夫して、多種多様なアプリケーションが新たな便利さや利用シーンを作り出されていきます。しかし、アプリケーションが登場するには、機器が連携してからしばらく時間がかかります。音声コマンドによる操作は、今はまだないサード・パーティのアプリケーションがなくとも、HomeKitを特徴づけるアプリケーションとなっています。

HomeKit は、機器開発のためのHomeKit対応機器の通信仕様と、iOSアプリケーション開発のための機器の登録や操作を提供する HomeKitフレームワークの2つで構成されます。HomeKit対応機器の開発は、MFiプログラムの対象です。HomeKitフレームワークは、一般開発者に開放されています。

電化製品を遠隔操作する技術は、古くから使われてきた技術です。例えば、1975年に開発された屋内電力配線で制御信号を送る技術X10は、電灯の遠隔操作パネルなどに欧米で広く使われています。X10のように専用制御装置を使うならば、すべての機器が屋内電力配線につながりますが、HomeKitではユーザはiOSデバイスを通じて機器とつながります。そのため、HomeKitは無線通信を使います。

電波は四方八方に広がるものなので、電化製品の無線化ではセキュリティの確保とプライバシーの保護が重要な課題になります。Bluetooth low energy にも、もちろんそれらの技術が盛り込まれていまが、HomeKitはそれらの技術は使っていません。HomeKitは、Bluetooth low energyを単にデータをやりとりするだけの無線通信として利用しています。セキュリティやプライバシーは、Apple社独自仕様で守られます。

=== アプセサリを作るには

ここまで、Bluetooth low energy技術の特徴と、iOSデバイスを軸としたエコシステムを見てきました。ここでは、Bluetooth low energyを活用したアプセサリを生み出すにはどうすればよいかを見ていきます。

==== ハードウェアとその体験

アプセサリは、アクセサリとアプリケーションとの造語です。ですから、ハードウェアとしてのアクセサリが同じであっても、そこに掛け合わせるアプリケーションやサービスにより、様々なアプセサリが生み出されます。

アクセサリ、つまりハードウェア部分だけを見ると、既存の周辺機器がBluetooth Smart機器になるものと、Bluetooth low energy技術があるから初めて商品化できる機器とがあります。また機器のBluetooth low energy技術の役割は、それがなければならない必要な機能と、あってもなくてもよい追加機能であるものとに分類できます。

既存の周辺機器がBluetooth Smart機器になるものの例として、デジタル体重計があります。デジタル体重計は、Bluetooth low energy技術以前からある機器です。液晶パネルや電池があり、スマートホンがなくても単体で独立して使えます。そして、体重計の採択済みプロファイル Weight Scale Profile がありますから、これを採用してBluetooth Smart機器にできます。

もともと電子回路と電池があるデジタル体重計は、部品代がおよそ600円程度のBluetooth low energy技術の無線通信回路を追加すれば、Bluetooth Smart機器にできます。機器の工場出荷価格の目安は、およそ販売価格の3分の1です。ですから、販売価格が3000円から1万円のデジタル体重計の、工場出荷時の価格は1000円から3000円です。ですから、この600円の部品代は、けして安くはありません。

デジタル体重計にBluetooth low energy技術が、あってもなくてもよい追加機能か、必要不可欠の機能かは、組み合わせるアプリケーションやサービスで決まります。

昔から体重計を製造販売している会社であれば、低価格から高価格までの幅広い品揃えのうち、高価な部品が追加できる高価格帯の体重計にBluetooth low energy技術を付加します。これは、あってもなくてもよい機能です。また、フィットネスや体重管理のネットワーク・サービスを提供する会社であれば、自社のサービスと自然に連携させるために、Bluetooth low energy技術を採用します。これは、サービス連携のための必須機能です。

Bluetooth low energy技術を、追加機能にするか、必須機能にするかは、会社の方針から決まります。体重計という機器の製造販売が目的であれば、その会社は売上を増やし数多くの機器を販売するために、多種多様な体重計を製造販売します。Bluetooth low energy技術は、その多種多様な体重計の1つの追加機能にすぎません。

ですが、フィットネスなどのサービスが目的であれば、その会社はサービスをより魅力的にして多くの利用者の獲得が目的になります。ですから、体重計は、そのサービスのブランド・イメージに適した機種が1つあればよく、多種のものを販売する必要はありません。Bluetooth low energy技術は、サービスとの連携に必須です。

==== ブレインストーミングとプロトタイピング

アプセサリを、その体験に注目すると、ハードウェアとしての機器や、アプリケーションあるいはネットワーク・サービスの開発は、その体験を生み出すための大切な要素ですが、要素にすぎません。体験を生み出し、その体験を提供し続けるための事業を立ち上げるのは、チームにしかできません。

アプセサリの企画では、ブレインストーミングが役に立ちます。ブレインストーミングは、参加メンバーがアイディアを出しあい、そのアイディアを批判せず前向きに展開し続けることで、アイディアの連鎖反応や発想の誘発を期待する会議手法です。

また、ブレインストーミングには、プロトタイピングが活用できます。プロトタイピングは、試作品を作り早期に企画や体験の検証を短期間で繰り返す手法です。専門分野の異なるチームでは、メンバー同士の認識のすり合わせにプロトタイピングが有効です。

粘土をこねて外形を作ったり、あるいは目標とする機器とは大きさも形も違うとしても、例えばApple Watchのアプリケーションである程度の機能を作り、手で触れて動かして遊ぶと、驚くような発見や広がりそして展開につながります footnote:[Designing for Future Hardware, https://developer.apple.com/videos/play/wwdc2015/801/]。

==== センサー・デバイスと測定値

素晴らしいアプセサリを思いつこうとしても、とりかかりがなければ、考えようがありません。また、素晴らしいアプセサリの体験のアイディアが出ても、そのアクセサリが今ある技術で現実的な価格で製造可能でなければ、実現はできません。センサー・デバイスと測定値の知識は、実現可能なアプセサリを考える手がかりになります。

測定値は、ある量の大きさを計器、センサー、で測定して得られた値をいいます。世の中には様々な種類や精度のセンサーがありますが、圧力、温度、湿度、加速度、角速度、あるいは磁場などのセンサーがあります。センサー技術は絶えず進歩していて、驚くほどの高い感度や精度や機能がある新製品が登場しています。数センチメートルの高低差に相当する気圧変化が検出できる気圧センサーは、階段の昇降の検出すらできます。

最も身近なセンサーは、スマートホンに使われているものです。スマートホンに使われるセンサーは、大量生産されているので、高性能なものが安価に入手できます。例えば、スマートホンに使われるセンサーとその用途は次のものがあります。

- 磁気センサー
	- コンパス
- 光センサー
	- 画面の明るさ調整(照度センサー)
	- 顔と画面の相対位置検出 (光学式近接センサー)
	- 写真撮影 (イメージセンサー)
- 音センサー
	- マイク
- 静電容量分布センサー
	- タッチ検出
- 加速度、角速度、気圧センサー
	- デバイスの向き検出
	- 歩数や運動量の検出
- 気圧センサー
  - 高度

アプセサリが提供するものは、利用者の体験です。ですから、センサーの計測値そのものではなく、その計測値が利用者の体験にどう関わるのかが重要です。センサーがどこに取り付けられているかが、計測値の意味を決めます。計測値がそのままで使うことは、あまりありません。いくつかの計測値を組み合わせたり、計測値を数値計算をして価値のある値を取り出したりします。

例えば、熱中症の危険を検出したいならば、気温だけではなく湿度も計測しなければなりません。またセンサーは、人の近くになければ意味が無いでしょう。あるいは、スマートホンのような常に携帯している機器では、その加速度は人の動きの情報そのものです。ですから、その加速度から歩数や消費カロリーの推定値を算出できます。

==== アクセサリのライフサイクルと収益

アプセサリはアクセサリとアプリケーションおよびサービスの2つの部分があります。アクセサリは、設計製造されて、流通し販売されて、利用され、そして破棄されて、そのライフサイクルを終えます。アプリケーションおよびサービスは、利用者から見ると、アクセサリを初めて購入した時点で利用が開始し、アクセサリを買い換えてもサービス利用は継続します。

ですから、アプセサリの売上は、アクセサリの売上と、アプリケーションおよびサービスの利用料金の2つです。したがって、売上を得る組み合わせは、アクセサリの売上のみでサービスは無料、アクセサリは無料でサービスは利用料金がかかかる、あるいはアクセサリの売上とサービスの利用料金がいずれもかかる、3つの組み合わせがあります。

フィットネス分野のアプせサリは、アクセサリの売上のみでサービスは無料のものが多くあります。それはアプセサリの売上にサービス利用料金を含めることに成功しているからです。単なる万歩計は1000円程度で販売されています。しかし、サービスと連携するBluetooth Smart機器の万歩計は5000円近くで販売されています。利用者がサービス連携の価値を認めることで、アクセサリの販売価格にサービス利用料金を含められています。

また、アプセサリのサービスをアクセサリの売上だけで運営維持していくためには、アクセサリかもしくはその消耗品が定期的に売れ続けなければなりません。フィットネス分野のアクセサリは、落下や洗濯による利用者のミスによる故障や、外装が汚れてくるなどで買い替えが期待できます。また、新しいデザインや新機能がある新モデルの定期的な投入も、買い替えにつながります。

あるいは、サービスのためのアクセサリならば、課金はサービス側で行い、より多くの人に使い始めてもらうために、アクセサリは実質無償とします。一般向けの決済サービスであれば、クレジットカードを読み取るアクセサリは安価で販売して、サービス利用時にその購入代金をポイントなどで利用者に戻して、実質無料で提供します。企業向けの勤怠管理システムであれば、まず利用を始めてもらえるように、機器はリースにして導入費用を低くして、利用料金で機器の費用を回収します。

アプセサリの事業規模は、利用者が増えるほど大きくなります。これには、アプセサリを知ってもらうこと、興味を持ってもらうこと、購入して利用してもらうことが必要です。フィットネス機器は、身につけている機器が他人から見えますから、、人のつながりと口コミで商品の認知が広まります。さらに、目標の活動量達成を自動的にソーシャル・メディアに投稿する機能があると、ネットワークを通じてもアプセサリの認知が広がります。

アクセサリには、ある場所に設置できるアクセサリは1つだけという場所の排他性と、あるアクセサリを利用していれば同様の別のアクセサリに入れ替えることはないという手間のための排他性とがあります。ですから、アプセサリの事業は、最初に利用されたものや、最初に導入されたものが強い立場を得ます。例えば、腕時計は2つ身につける人はいません。あるいは、企業向けのサービスであれば、別会社のサービスに切り替えることは、機材の入れ替えなど大変な手間がかかりますから、まずありません。

==== 開発とそのチーム

事業化を目指すアプセサリの開発は、ハードウェアやソフトウェアなど、いくつかの分野にまたがるために、その開発はチームでおこなうことになります。

プロジェクトは、アクセサリとサービスの試作などのプロトタイピングとその体験の確認の繰り返しに始まり、量産を前提とした試作、そしてサービスを開始してからは不良品対応やユーザー・サポートなどの運営へと進みます。プロジェクトの段階にともない、チームやその構成メンバーは変更されていきます。

プロトタイピングでは、分野を超えた連携が特に重要です。体験と設計そして実装とが、うまく組み合わさらないと、後の詳細実装で実装ができないことがわかりプロトタイピングからやり直しになり時間と費用を消耗したり、工夫をすれば実装ができることに気がづけずに、よい体験を逃したりします。分野を超えてお互いに工夫を出しあうことが重要です。

ハードウェアとアプリケーションが、それぞれ別の開発チームであるならば、チーム間での成果物の渡し方と渡す時期の設定に工夫が必要です。

チーム間で成果物を渡す時には、その成果物だけで動作が確認できるようにします。試作したハードウェアをアプリケーション開発チームに渡す時は、ハードウェアだけではなく、動作確認用のアプリケーションも渡すようにします。開発中にハードウェアの挙動がおかしい場合は、動作確認用アプリケーションがあれば、その原因がハードウェアなのか通信あるいはアプリケーションにあるのかを切り分けられます。

チームからチームへの成果物の公開は、ファイル共有やプロジェクト管理サービスを使い、常に行います。開発プロセスの1つを完成させてから次のプロセスを進める方法では、すべてのプロセスが直列に並び開発期間がとても長くなるのと、どこかで不具合が判明した時にその修正にかかる時間がとても長くなります。

試作が完了すれば、次に量産のための試作、そして製造へと移行します。製造設備を所有していなければ、製造ができるパートナーも見つけ出さなければなりません。体験のための試作と、量産のための試作は異なります。製造のしやすさや製造費用の低減はもちろん、人への安全性などのリスク分析や、説明書への記載、リサイクルや環境への配慮などの、市場で販売するために必要な考慮が含まれます。

また、Made for iPhoneプログラムには、設計者ライセンスと製造者ライセンスがあります。iBeaconのように、iOS独自の認証技術が用いられていないものでは、通常のBluetooth Smart機器として製造ができます。ですが、HomeKitのように高度な認証技術が使われるものは、Made for iPhoneの製造者ライセンスを取得している製造パートナーを探します。

==== 電波法とBluetoothの認証

市場で販売される機器には、機器がお互いに機能できるように、認可や申告の義務があります。電波を送信するBluetooth Smart機器には、電波法の遵守と、Bluetooth無線技術の認可の取得と製品申告が必要です。

電波は公共の資源です。電波は四方八方に広がるため、混信や妨害が起きないように、国が周波数の割当や事業者への割当をおこないます。Bluetooth Smart機器は、電波を送信するので、小さいながらも無線局です。電波法に従わない勝手な無線設備の運用には、罰則規定があります footnote:[電波法 第百十条 次の各号のいずれかに該当する者は、一年以下の懲役又は百万円以下の罰金に処する。]。

無線技術の知識がない人が免許がなくても利用できるように、無線設備を電波法に適合するものとして認証する制度があります。これが、技術基準適合証明制度(技適)および工事設計認証制度です。

技術基準適合証明制度は、無線設備を1台づつ試験をして技術基準に適合しているかを判断して認証するもので、1回の申請で最大500台まで申請できます。これは、試作あるいは少数製造で利用されます。

製造では、工事設計認証制度が使われます。これは、無線設備の設計とその製造設備が基準を満たすことを認証します。この制度は、同じ特性の無線設備が製造できる工場で製造された1台の無線設備を試験して、その1台が技術基準に適合してれば、これから同じ特性で製造される無線設備も技術基準を満たすだろうというものです。

これらの制度を利用しても、製品ごとに認可を取るのは大変です。そこで使われるのがモジュール状の特定無線設備、つまり無線モジュールです。無線モジュールとは、発振部などの電波の特性に直接影響を与える部分を1つの基板や集積回路にまとめたものです。無線モジュールで、技術基準適合証明または工事設計認証を取得していれば、無線モジュールを組み込んだ最終製品で認証を取得する必要はありません。

ですから、Bluetooth Smart機器の試作と量産では、無線モジュールがよく使われます。しかし、無線モジュールが使えない小型や曲面のように特殊な形状のものでは、無線回路から設計します。このときは、電気回路の設計と試作ではシールドボックスやシールドルームという、電波を外に漏らさない箱や部屋で試験をします。また屋外で体験を検証するときは技術基準適合証明を、製造時は工事設計認証を製品に対して取得します。

電波法は国ごとに異なります。Bluetooth Smart機器を米国で販売するには、通信や電波の利用を管理する連邦通信委員会(Federal Communication Commission、FCC)の認証の取得が必要です。これには、日本国の技術基準にはない、機器から意図せず放射される電磁波の強度測定が含まれます。

このように、電波法の基準やその認証制度とその運営は国ごとに異なります。どのような試験項目があるのかは設計段階から把握し対応しなければ、試験に通らず再設計することになります。また、1回の測定で複数の国に提出できるデータを取得できるものもあります。ですから、量産のための試作では、認証サービス会社や製造パートナーと、事前にどの国で販売するかを設定して、技術評価項目を確認しておきます。

Bluetooth機器を自社製品として販売するには、Bluetoothの認可を取得して製品申告をします。これには、Bluetooth無線技術の知的財産と商標のライセンシングが含まれます footnote:[Bluetooth 認証および申告プロセス, https://www.bluetooth.org/ja-jp/test-qualification/qualification-overview]。

申告料金は、アソシエイトメンバーであれば4,000米ドル、年会費が無償のアダプターメンバーであれば8,000米ドルです。年間収入が1億米ドル以下の中小企業のアソシエイト会員の年会費は7,500米ドルですから、1年間に2つ以上の製品を登録するならば、アソシエイトメンバーになる方が得です。

また、小さな新興企業が最初のBluetooth製品を商品化できるように、イノベーション奨励プログラムがあります。年間収入が100万米ドル未満で、以前に申告をしたことがない企業は、2,500米ドルの割引金額で最大2つの申告を受けることができます。

=== まとめ

この章は、利用場面を例にして、Bluetooth low energy技術の特徴とそのエコシステムとを見ていきました。無線通信には必ず通信相手がいます。ですから、通信相手がそれぞれ普及しないかぎり、新しい無線技術は普及しはじめません。Bluetooth low energy技術は、スマートホンという通信相手の登場により、急激に普及しはじめました。

従来版Bluetooth無線技術は、無線通信と機器のデータ表現を組み合わせて最適な技術を提供していました。ですが、Bluetooth low energy無線技術は、ものをデータベースとして表現する、通信を意識しなくてもよい、GATT 基盤アーキテクチャを採用しました。

Bluetooth low energy技術のエコシステムは、機器の製造販売、アプリケーション開発、そしてサービス提供といった、事業の目的も利益も違う事業者の関わりあいで支えられます。Bluetooth low energy技術は、このエコシステムのつながりのよりどころなのです。

Bluetooth SIGの採択済みプロファイルをよりどころにして、周辺機器やフィットネスなどの機器市場へのBluetooth low energy技術の普及をみてきました。そして、カスタム・プロファイルとアプリケーション開発がもたらしたアプセサリと呼ばれる新しい利用分野を見てきました。

Bluetooth low energy技術は、その強力なブランド力で、身の回りにある様々な物と物事のための無線通信技術として、ますます普及していくでしょう。


// チーム構成
//

// べからず的な
// 距離の推定
// 通信できると思い込む
// 開発の途中での、サービスとかつながらないとか。

// 実際どのBLEのバージョンを選べばいいの?

では、新たに開発を始める時に、いくつもあるコア仕様のバージョンのどれを選択すればよいのでしょうか。

モジュール、開発環境、コスト。
5.0 家電、長距離を想定しているならば。ファームウェア・アップデート。
4.2 LE Data Packet Length Extension。パケット長の拡大。IP技術。
4.1 ピコネットのトポロジ拡張。LE チャネル。バルクデータの扱い。

//==== Bluetooth無線技術の認証制度 ====
//認証(Qualify)、
//宣言(Declaration)、Bluetoothという単語を含む、商標を使用している製品の販売、ブランド化、最ブランド化。製品の"申告"。認証設計(QDID)を参照する準拠宣言(DoC)。
//他社のBT製品を販売またはおろしうるしているだけ。ロゴの追加、自社製品としてブランド化や表明をしていない。たんなる小売やサプライヤーは、製品の認証と宣言は不要。

// EndProduct, Controller Subsystem, Host Subsystem, ProfileSubsystem, Component, Combination of the above
//認証および宣言
//shttps://www.bluetooth.com/ja-jp/develop-with-bluetooth/qualification-listing
//認証制度、一般販売。商標を使いたい時。
//電波モジュール。半導体、電波を出す部分、通信制御部分、ソフトウェアだけではなく
//電子回路の実装や部品選定。モジュール単位で認証、それを継続利用する。
//費用。メンバー2種類。40万円、80万円。
//半導体の会社、モジュールの会社、製品の会社、OSの会社、それぞれ要素ごと
//設計を継承する。その部分に一切手を加えていない。
//BLEモジュールで振る舞いがあれこれなのは、ユーザアプリがどのようなことをしても、
//無線通信に影響しないことを保証する。プリエンプティブ、優先度。余った時間で処理。


また、コア仕様のバージョン選択は、半導体会社によって、半導体の選択に影響しない場合と影響する場合があります。Nordic Semiconductor社の製品では、nRF51822は、コア仕様の更新に、無線通信を制御するスタックと呼ぶソフトウェアの更新で対応してきました。そのため、nRF51822はBluetooth 4のいずれでも対応できます。また、テキサス・インスツルメンツ社の製品では、CC2540はBluetooth 4.0のみに対応します。Bluetooth 4.1および4.2には、CC2540の後に開発された、異なる構成のCC2640が対応します。

宣言は、宣言ID(IDentifier, 識別子)を購入し、新しい申告を作成して、準拠宣言(DoC,Declaration of Compliance)に署名することで、完了します。宣言IDの価格は、2017年の時点で、年会費が無償のアダプターでは4,000米ドル、年会費が求められるアソシエイトメンバーでは8,000米ドルです。あるいは、最初のBluetooth製品を商品化するスタートアップ企業のためのイノベーション推奨プログラムが適用されれば、2,500米ドルになります。






// 中心的なものと、カスタムなもの
設定画面からBT接続。モバイルデバイス、つながったりつながらなかったり。アプリから接続制御。

// 多様性の上のプラットホーム。
ホームオートメーション、規格はないけど。規格がありすぎて。
業界団体。スマートホン、ユーザ体験。競争しているので、お互いに排他的。

この従来版Bluetooth無線技術の誕生と普及の影で、より低消費電力で低価格な新しい無線通信技術として開発が進められていたのが、Bluetooth low energy技術です。

Bluetooth low energy技術は、従来版Bluetooth無線技術を置き換える技術ではありません。従来版Bluetooth無線技術があまり使われてこなかった利用分野に向けて開発された、新しい技術です。

まず、Bluetooth low energy技術は、その名のとおり、超低消費電力の無線通信技術です。いままで無線技術が使われてこなかった製品に無線通信を採用すると、無線通信の分だけ消費電力が増えます。それにより電池交換の手間が増えて不便になったりしないように、無線通信は十分に超低消費電力でなければなりません。

従来版Bluetooth無線技術は、デジタル・データを連続してやり取りし続ける無線技術です。これは、音が途切れてはならないヘッドセットや、送信が中断してほしくないファイル交換などの利用分野では大切な技術です。ですが、途切れない安定した無線通信技術は、高品質なぶんだけ、複雑になり消費電力を小さくするのにも限界があります。

ですが、身の回りにある様々な機器に、デジタル・データを途切れなく連続してやり取りし続けるものは、あまりありません。例えば、テレビやエアコンのリモコンは、ボタンが押されときに、そのボタンの種類を送信するだけです。

ですから、従来版Bluetooth無線技術が連続してデータをやり取りし続けるのとは異なり、Bluetooth low energy技術は、少量のデータの低頻度でのやりとりを前提にして、超低消費電力無線技術を実現しています。

この超低消費電力無線通信は、無線通信を必要最小限の時間だけしか使わないことで実現できます。高周波信号をあつかう無線回路は、送信でも受信でも、動かすだけで大きな電力を消費します。ですから、送信側と受信側は、通信する時間をあらかじめ同期して、データをやり取りする時間だけ無線回路を動かし、通信が完了すればすぐに無線回路を停止するのです。

通信には2つの重要な性能項目、通信速度と遅れ時間があります。通信速度は、1秒で送信できるデジタル・データの量を、遅れ時間は、送信を開始したデジタル・データが実際に相手に届くまでにかかる時間をいいます。

この遅れ時間は、送受信側それぞれがお互いに無線回路を動かす周期(コネクション・インターバル)で決まります。この周期が短いほど、無線回路を動かす回数が増えるので、消費電力は増えます。

Bluetooth low energy技術は、この無線回路をオンにする周期を、7.5ミリ秒から4秒までの範囲で設定できます。例えば、楽器のように遅れ時間をできるだけ短くしたい利用分野はミリ秒単位の小さな遅れ時間を、また温度計のように遅れ時間がなくてもよい利用分野は、周期を長くして電力を節約するなど、利用分野それぞれに適した設定にできます。

また、Bluetooth low energy技術は、無線接続が切断することを受け入れる技術です。もしも、あらかじめ同期した時間に、来るべき無線信号がこなければ、その無線接続は切断したものとみなします。

従来版Bluetooth無線技術は、例えばヘッドセットでは通信が切断すれば音が途切れてしまうように、データが流れ続ける用途に使われます。ですから、接続が切れないよう高品質の無線通信に設計されています。

Bluetooth low energy技術は、少量のデータを低頻度でやりとりするものなので、通信が切断しても、再接続すればよいのです。また、Bluetooth low energy技術の機器の発見と接続処理は、場合によっては20ミリ秒程度と、とても素早くできるものに設計されています。

また、Bluetooth無線技術は、無線通信で機器を扱うための技術ですから、無線通信と同じくらいに、データ表現の仕組みが重要です。

従来版Bluetooth無線技術は、機器ごとに通信とデータ表現を組み合わせた最適な技術を提供しています。例えば、音声信号を送るという同じ機能でも、通話に使う電話通話向けでは遅れ時間の小ささが、音楽を聞く用途では高音質がと、異なる性能が求められます。

ですから、音声通話向けには、遅れ時間の小さい通信とその通信の特徴を活かせるデータ表現を、音楽鑑賞向けには、遅れ時間は大きくても高音質の大量のデータを遅れる通信と、その特徴を活かした高音質のデータ表現を、それぞれ提供します。

このように、利用分野に最適な技術の提供には、通信とデータ表現をうまく組み合わせることが不可欠です。ですが、Bluetooth low energy技術は、多種多様な機器に向けた技術です。従来版Bluetooth無線技術のように、機器ごとに時間と費用をかけて最適な技術を提供するわけにはいきません。

そこで、Bluetooth low energy技術は、GATT基盤アーキテクチャという仕組みを採用しています。このアーキテクチャは、機器の機能をデータベースとして表現する仕組みです。機器がサーバーに、スマートホンなどがクライアントになる、サーバー・クライアント モデルを採用しています。

このGATT基盤アーキテクチャで、通信とデータベースの読み書きとの組み合わせが最適化されています。このGATT基盤アーキテクチャ上で、機器の機能は、データベースのデータ形式として定義されます。ですから、機器ごとの開発はデータ形式を定義するだけで、GATT基盤アーキテクチャが提供する通信とデータ表現を組み合わせ最適化された技術が利用できます。

さらに、無線を通じて機器を利用するBluetooth low energy技術には、機器の所有や利用の権利を表現する仕組みがあります。無線通信では、機器の周囲にいる誰でもが電波を送信したり受信したりできます。ですから、通信相手が偽装ではなく信頼できる相手だと認証したり、その機器の所有や利用の権利があと認可するために、暗号技術と事前に交換された暗号鍵が持ちいられます。

この暗号鍵の交換と保存の機能は、ペアリングとボンディングと呼ばれます。ペアリングは無線接続時に暗号鍵を交換する機能です。ボンディングはペアリングで交換した暗号鍵を保存して、再接続時に保存した鍵を利用できる機能です。

このペアリングとボンディングを使って、所有や利用の権利を表現できます。例えば、血圧計があったとします。これがスポーツジムに設置されたものならば、それは誰が使ってもよい機器です。この場合は、ペアリングもボンディングもせず、任意のスマートホンからすぐに手軽に接続できるようにするでしょう。しかし、これが個人所有ならば、ペアリングとボンディングをして、所有者のスマートホンとだけ接続できて、かつプライバシーを守るために通信は暗号化するでしょう。

、パーソナル・コンピュータから、モバイルあるいはスマートホンへと移り変わり、
Bluetooth low energy技術は、Bluetooth無線技術に統合された、超低消費電力無線通信技術です。
2010年に規格が発表されたBluetooth4.0
このBluetooth3.0とは電波をやり取りする方式から異なる新しい技術は、
それまで
2010年に規格が発表されたBluetooth4.0
この技術は、の一部です。、
で初めて統合された、
Bluetooth low energy技術は、
とは電波をやり取りする方式から異なる新しい技術です。Bluetooth4.0は、それまでのBluetooth3.0に、Bluetooth low energy技術を付け加えた
Bluetooth4.0は、それまでのBluetooth3.0までの技術とは電波をやり取りする方式から異なるBluetooth low energy技術
21世紀にはいり、私達の生活や社会は、情報の流れで動くようになりました。


しかし、私達の身の回りを見渡すと、無線通信技術が使われているものは、ほとんどありません。掃除機や電子レンジは、操作パネルを人の手で触れて操作しています。手の届かない位置に設置されるエアコンには、離れた場所から操作できるリモコンが付属しています。

しかし、押されたボタンの情報を送信するだけでよいリモコンには、一方向にデータを送信するだけの簡易な赤外線方式が使われているだけです。

いくつもある無線通信技術のなかでも、Bluetooth無線技術は、いまやほとんどのパーソナル・コンピュータやスマートホンに搭載されている、広く普及した技術です。

Bluetooth無線技術でワイヤレスになったヘッドホンやキーボードあるいはマウスなどの周辺機器に毎日囲まれていると、まるで世の中すべての機器がワイヤレスになったような錯覚を覚えます。



Bluetooth low energy技術は、まさにそのような分野のための技術です。小さな電池で何年も無線通信をし続けられる超低消費電力無線通信技術と、多種多様なものをデジタル・データとして表現する仕組みを備えています。そして、Bluetooth low energy技術は単体としての超低消費電力無線通信技術としてではなく、それまでのより高速な通信を目指してきたBluetooth3.0に、Bluetooth low energy技術を統合した、Bluetooth4.0という1つの無線通信規格として登場しました。

ところが、Bluetooth low energy技術は、いまやあらゆるスマートホンに搭載されているほど、驚異的な速さで普及しました。それは、Bluetooth low energy技術がBluetooth4.0に統合された技術だからです。パーソナル・コンピュータやスマートホンの新製品がBluetooth4.0に対応すれば、そこにはもうBluetooth low energy技術が含まれています。


私達の社会は、100年前には存在していなかった情報通信や電子回路




そして情報処理技術に支えられています。

社会を変えうるほどの新技術が誕生しても、ただちにそれが普及するわけではありません。それが便利だと気づいた人たちが徐々に登場して、少しずつ新技術の便利さが認識されていき、ある瞬間から急速な普及が始まります。やがて気がつけば、その新技術があることを前提にして社会が動くようになり、もはや技術があるのが当然となります。

人類は初めて無線通信技術を手に入れたのは、まだほんの100年ほど前のことです。この目には見えない電磁波で離れた場所に情報を伝える技術は、いまや放送や通信あるいは位置情報の取得などの、生活のあらゆる場面で使われています。

さらに21世紀にはいると、私達の生活や社会は、情報の流れで動くようになりました。インターネット、そしてスマートホンとソーシャル・ネットワーキング・サービスが、人々を常にネットワークにつなげています。この情報の流れは、高度に発達した無線通信技術に支えられています。

そして、これから普及すると考えられているものが、身近なあらゆるものがネットワークとつながる世界です。Bluetooth low energy技術は、その世界で必要とされる超低消費電力で低コストな無線通信技術の1つです。

この章では、無線通信技術の歴史を振り返りながら、Bluetooth low energy技術の登場とその活用場面を見ていきます。





筆者が初めてBluetooth low energy技術に出会ったのは、2011年のことでした。アップル社は毎年開発者向けイベント The Apple Worldwide Developers Conference (WWDC) を開催しています。2011年のWWDCの資料に、Core Bluetoothフレームワークという単語があったのです。フレームワークとは、iOSアプリケーションから呼び出せる機能を1まとめにしたライブラリです。




新しい無線通信技術が登場しても、普及せずに忘れ去られたり、普及までに長い時間がかかることはよくあることです。それは、通信には必ず通信相手が必要だからです。製品に新しい無線技術を採用しても、通信相手となる何かが普及していなければ、活用できません。また逆に、身の回りに新しい無線通信技術を採用した製品がなければ、その製品の通信相手になる何かを購入する理由がありません。


Bluetooth low energy技術は、驚くべき速さで世界中に普及しています。それは、このBluetooth low energy技術が、Bluetooth4.0に統合された技術だからです。パーソナル・コンピュータやスマートホンが、Bluetooth無線技術に、Bluetooth4 や Bluetooth5 を採用すれば、そこにはもう、Bluetooth low energy技術があるのです。

Bluetooth low energy技術の驚異的な普及をもたらしたのは、スマートホンによるものです。
を世界で初めて採用した製品は、2011年に発売されたiPhone4Sです。
買い替え周期、ブランド、ハイエンド、技術の取り込み。
Bluetoothブランド
Bluetooth3.0から
4.0を採用すれば、そこには自動的にBluetooth low energy技術がある。
ハードウェアの高性能化が目覚ましいスマートホンは、2年程度の短い周期で買い換えられます。

が、世界で初めてBluetooth4.0を採用しました。
の驚くべき普及をもたらしたのは、スマートホンの存在です。


モバイル・デバイスは2年周期

4年もすれば、世界で使われているiPhoneはほぼ
世界で数多く販売されるiPhone
Bluetooth low energy技術


Bluetooth4.0を世界で初めて採用した製品は、2011年に発売されたiPhone4Sです。

Bluetooth4.0の規格が公開された翌年
つながる相手となる機器がないにも関わらず、iPhone4Sとそれ以降に発売されたiPhoneシリーズおよびMac

Bluetooth low energy技術でつながる相手となる機器がまだな

つながる機器がまだなにもないのに、
世界で初めて、周辺機器も何もない。
いまやほぼすべてのパーソナル・コンピュータやモバイル機器が採用するまでになりました。
フィットネス、マウス、キーボード、。

Bluetooth low energy技術は、身の回りの様々なものに無線通信の機能を与えられる、超低消費電力無線通信技術です。


Bluetooth low energy技術の本を書きはじめて、5年が過ぎ去りました。技術解説
技術解説として本書を書きながら、
Bluetooth low energy技術
技術解説を書くうちに、技術を解説するだけでは意味がない

必要もないのに普及した。なんでもできるが、なにもできない。だけど、なんでもできるが生きる。
雰囲気、使い方、

。



。

Bluetooth low energy技術が急激に普及したのは、Bluetooth low energy技術がBluetooth low energy技術という1つの技術ではなく、Bluetooth 4に統合された技術だったからです。パーソナル・コンピュータやスマートホンの新製品は、競合他社に見劣りしないように、最新の技術を採用します。そして、Bluetooth4が採用されると、そこにはBluetooth low energy技術があるわけです。

Bluetooth low energy技術は、利用場面が生まれる前に普及した技術です。

利用場面がないけど普及した通信相手、エコシステム。採用機器。アプリケーション。アプリと連動、アプ背さり、造語。





この急激な普及は、Bluetooth無線技術の一部として統合された技術であるため、Bluetooth4.0




// 無線の性質、つながり続ける。
// めちゃくちゃ早い時期に普及した。
// スマホでは完結できな部分、でも単体でも意味がない部分。健康機器、電化製品、
// リアルと関わる紐付け、 教育教材、ビーコン。近接。
// パソコン。サービス。それだけかもしれません。
// 幾つか案件をやってみて。
// サービスとして、IT系のあれこれ、アプリづくり。店舗設計、サービス設計の要素。プロでもいいけど
// 知っていればいいだけ


通信には、あたりまえだが、必ず通信相手がいなければならない。だから、新しい無線通信技術が登場しても、その通信相手となる機器が普及していなければ、その技術を採用する製品群が登場することはない。

しかし、これという利用場面もないのに、
規格が公開された翌年2011年に
iPhone4Sが世界で初めてBluetooth low energy技術を採用し、
しかし2011年にiPhone4Sが世界で初めて
そのため、新しい無線通信技術の普及には、長い時間がかかることが

新しい無線通信技術が登場しても、それを採用する機器が登場しはじめるには、通信相手となる機器も普及しなければならないため、
それを採用する機器だけではなく、通信相手となる機器も普及

新しい無線通信技術の普及には、その通信相手になる機器や製品など


本書を手にしているあなたは、Bluetooth low energy技術を使いたい


いま本書を手にしているあなたは、きっとに関心がある方だろう。

ビーコンやフィットネス機器、あるいはサービス開発、ハードウェア、教育素材、
ビジネス、技術、


電池1つで1年程度も通信状態を維持できる新しい超低省電力無線通信技術である。
新しい技術は登場してから普及するまでに長い時間がかかることが普通である。しかし、このBluetooth low energy技術は、2010年に初めて規格が公開された翌年の2011年に、iPhoneに採用された。

確たる使い道もないのに

4年程度で急速に普及した。

しかし、2010年に初めて規格が公開されたBluetooth low energy技術は、その翌年にiPhoneが採用して、いまでは世界中のスマートホンそしてパーソナル・コンピュータに広く普及した。

翌年2011年にiPhoneに

2010年に規格が初めて公開されたこの技術は、はやくにスマートホンに採用され、いまでは


2011年にスマートホンが採用して今では世界中のスマートホン



なぜなら、この本はエンジニアではない方々そして技術とはあまり関係がない

もしも、あなたが専業のエンジニアであるならば、著者である私の敗北である。


本書を手に取られた方、BLEに興味がある方。エンジニアかなと思う。
けっこう分野の違う技術が重なって、ほしいのはBLEじゃないでしょう。まとめて書こうと思う。

1つは専門書は売れないからだ。

アプリとハードウェア、ブラックボック。いかなる専門家もゼロから作れない、逆に専門家である必要がある場面がめったとない。子供用の教育教材にすら使われてて、プロトタイピングは小学生向けのキットで十分。

電池が極端に消費しない、つながりつづける。アプリとセットで開発できる、
なんとなくつながる、八百万の神というけれども、付喪神、あらゆるものに神様が宿る感覚。
虚空に向かってコマンドを発する、SFで照明。それも、目には見えないけど、何かが常に底にいる感覚。
そういうのが、実現できる技術。つながりつづける。

通信相手が人間ではない。

釘と木材。日曜大工、建物を立てるとき、小学校の夏休みの工作でも、大規模な都市建築物でも、防火処理して。同じ釘と木材でも、色んな使い方がある。あとはそれ自体が売上につながっている場合もあれば、ただ手元にある手頃な素材として使っている場合。趣味と仕事、本業と付加価値的な何か。

たぶん、iPhoneとハードウェアの周辺機器、アプリ開発者になりそこね、絵と音ができない。
いくつか開発案件、ファームウェアとハードそしてアプリを一貫してできる人は珍しい。
チームのための、部品として。あとはブラックボックスとして使える。ならば入力と出力だけを理解していればいい。地図アプリとか開発できるのとか、SDKを見て提供されている機能の組み合わせ。それ以外の表現はまずむり。絵を描く時、クレヨンと紙があれば、でもハサミで立体物を作って表現とか、とっぴなこと。

IoTインターネット、情報であらゆるものが連携して動く。利用者、広告。商品。賃貸物件とか、旅行代理店とか、店舗がネット上。出費は小さいが、利用価値は大きい。駅前にお店を出していた時代。その消費活動に乗らないと、残れない。

NB-IoT、実験。電波の接続は、月額料金、高い高いといいながら、まるっとおまかせ、責任は向こう側。
自分たちで、アプリとハードウェア、そういうのも、実験できるかもしれない。

結構すでにいい本がある、ならばなぜ今更書くのか。技術書や教科書を書こうとして、なども書き直して5年位経過している。なぜかかけてない。なぜだろう?

ならば失敗したかも、チームで読んでね。売れるから。




本書を手に取られた方、
Bluetooth low energy技術。まぁこの技術の話をする前に。
スマートホンの周辺機器、ハードウェア、アプリケーション開発、様々な。

無線、放送、石。半導体。
技術を知らなくても? いいと思う。それで。使えるよ。

でもそれでいいのかしら。情報の不均衡、具体的に作るときは細かいこと、おおまかなところ。
ワイワイガヤガヤ、イノベーション。役割の違う人達が理解し合える最低限の、でも間違わない話。
細かい話でも、担当分野。教会がいっぱい。デモ統合して初めて価値が出てくる。

無線でつながるっていうのは、そういうこと。
つながりっぱなしでもない。出会いと別れ。そういう設計。柔軟。機能を決めるのが自分なの。










== Bluetooth low energy技術の登場とその活用 ==



=== 無線通信技術の登場と普及 ===

新たな無線通信技術の登場とその普及は、私達の社会と日常生活を、それ以前とはまるで異なるものに変化させてきました。しかし、技術が普及したあとの、それがあるのが当然の時代に生まれ育った私達には、その変化はわかりません。

Bluetooth low energy技術は、私達が今まさにその登場と普及を目撃している技術です。この技術は、マウスやキーボードといった周辺機器やフィットネス機器あるいは近接検出技術として、急速に普及しています。また、この技術がまだ普及し始めていない電化製品などの分野に向けて、普及する分野をさらに広げようと、より便利で使いやすくするための技術を新たに追加して、柔軟な変化を続けています。

==== 通信と情報 ====

Bluetooth low energy技術は、身の回りにある様々なものをデジタル・データで表現して、そのデジタル・データを無線通信でやり取りする、情報通信の技術です。

情報通信のうち、通信は、デジタル大辞泉 http://www.daijisen.jp/digital/ によると、手紙などで自分の意思やようすなどを他人に伝えること、または郵便・電信・電話などによって情報を伝達すること、とあります。前者は人間の振る舞いからみた通信です。今は通信という手段に興味があるので、後者を通信の定義としましょう。

通信は、ありふれたものです。いま目の前にいる相手と会話しているとします。これは話し言葉を音声にして、空気の振動で相手に伝える通信です。また、情報は媒体を移し替えて伝達させられます。例えば、少し離れた相手と糸電話で会話しているときは、話す側では空気の振動が糸の振動に変換され、受け手側ではその逆の変換をすることで、音声が伝わります。

糸電話のように媒体に配線を用いるものを有線通信、音声による会話のような媒体に配線を用いないものを無線通信と呼びます。

有線通信は、何かしらのエネルギーを伝送できる配線を媒体に用います。糸電話の糸は振動エネルギーを、電気配線は電力を、あるいは光ファイバーは光エネルギーを伝送します。エネルギーが配線の内側に閉じ込められるので、相手に伝わるエネルギーの効率が高く、また外部から通信を盗み取ることも困難です。

無線通信は、媒体に配線を用いない通信です。配線がない空間でエネルギーを伝えるため、無線通信は媒体に波を使います。音声会話は空気の振動という波を、赤外線リモコンであれば赤外線という電磁波を、そしてラジオ放送であれば電波を送信します。波は空間を広がっていきます。ですから、周囲にいる相手と通信ができますが、送信したエネルギーのごく一部しか相手には伝えられず、また周囲にいる不特定多数が通信を受信できます。

Bluetooth low energy技術の振る舞いは、電波という媒体性質で決まります。電波は周囲に広がります。ですから、カバンやポケットに入れたままのスマートホンと、その周囲にあるウエアラブル機器や電化製品とが通信できます。無線通信なので、機器を探し出して配線で接続しなくても、すぐに機器が利用できます。配線がないので、機器を自由に移動したり持ち歩いて利用できます。

では、情報通信のうち情報とは、なんでしょうか。同じように情報の項目を見ると、ある物事の内容や事情についての知らせ、または文字・数字などの記号やシンボルによって伝達され、受け手に状況に対する知識や適切な判断を生じさせるもの、とあります。前者は、人間からみた情報です。通信が伝達する内容物としては、後者を情報の定義とすればよさそうです。

 情報通信は、文字・数字などの記号やシンボルで表現される、受け手に状況に対する知識や適切な判断を生じさせるもの、つまり情報を、なにかの媒体によって伝送すること、といえます。

無線通信技術は、"受け手に状況に対する知識や適切な判断を生じさせるもの"を伝送するのに不可欠です。ですが、無線通信技術それ単体が価値を提供するものではないともいえます。

これは、宅配便の価値に例えることができます。ネット通販など宅配便がなくしては成り立たないサービスがいくつもあります。また配送日の日にちや時間指定ができるなど宅配便も1つのサービスとして価値を高めています。しかし、宅配便だけを利用することはありません。

通信には必ず通信相手がいます。ですから、通信を成り立たせるためには、媒体の伝送やシンボル表現などの方式をお互いが事前に示し合わせておかねばなりません。その示し合わせる根拠が、通信規格なのです。通信規格は、媒体で情報をやり取りする物理的な通信方式、情報の表現方法、そして情報でどう振る舞うかの3つを定義します。

通信相手というと無意識に人を思い浮かべがちですが、Bluetooth無線通信は機械と機械との通信規格です。フィットネスの心拍センサーを使われている方は、心拍数という情報を自分という人が見ているから、機械と人との通信だと思われるかもしれません。しかし、通信は心拍センサーとスマートホンのアプリケーションとの間でおこなわれています。人が見ている心拍数は、アプリケーションが提供している心拍数表示機能です。

新しい技術は、それまでにない利便性を可能にする手段です。新しい無線通信技術は、それまでの技術が運べていなかった、受け手に何かの変化をもたらすものを、運ぶ手段を提供します。その手段をサービスとして活用する場面が登場しなければ、新しい技術は普及しません。そのため新技術が普及しはじめるまでには、通常は長い時間がかかります。

==== 通信とその媒体 ====

媒体により、通信の振る舞いは、どのようなものになるでしょうか。

静電気や磁石が離れた場所に力を及ぼす不思議な作用は、紀元前の古くから知られていました。小学校の理科の授業でも、砂鉄が磁石にくっつけたり、下敷きを強くこすって髪の毛が引きつけられるのを、観察したと思います。この離れた場所に力を及ぼす現象は、通信の媒体につかえるでしょうか。

静電気の力、2つの電気を帯びたものの間に働く力の関係は、1785年にシャルル・ド・クーロンが精密に測定して、クーロンの法則としてまとめました。また、この力をクーロン力と呼びます。

クーロン力は、電気を帯びた2つのものの間の距離、その大きさの2乗に反比例します。例えば、2つの電気を帯びたものを1メートル離して置いたときの、力の大きさを1とします。これを100メートル離すと力の大きさは1万分の1に、さらに10キロメートル離すと1億分の1になります。

また、電気を帯びたもののどちらか一方を金属の球で覆うと、その間に働く力はゼロになります。クーロン力で、金属のなかにたくさんある電子が、金属の表面に引き寄せられて、クーロン力の効果を打ち消すからです。金属でなくとも、例えば水を多く含む人間など、電気を通しやすいものがそばにあるだけでも、クーロン力は随分弱くなります。

ですから、もしも静電気の力を通信の媒体に使うとすると、受信側は極めて小さな力を検出しなければなりません。さらに、送信側と受信側の間に、人や建物のような何かものがあると、その影響をうけて力の大きさが変化します。力の強さが小さくなるだけではなく、その力の変化が通信で送られたものなのか、何かの影響をうけて生じたものなのかが、区別できなくなります。

静電気の力は、通信の媒体には使えません。これは磁石の力でも同じことです。小さな力を精度よく検出する技術は、現代でもとても高度な技術です。遠く離れた場所に、どうしても力を伝えて通信をしたいならば、ただの紐を何キロメートルも伸ばし、その紐の両端を引っ張りあって力を伝えるほうが、確実です。

無線通信には、波が使われます。会話では空気の振動という波が、糸電話では糸の振動という波が、通信の媒体です。空気の振動や糸の振動で運ばれるのは、波はエネルギーの流れです。空気や糸それ自体は移動しません。波は、何か2つのお互いに変換しあえるエネルギーがあれば作れます。例えば、空気を伝わる波は、圧力エネルギーと運動エネルギーとが交互に変換しあって進んでいきます。

エネルギーには、運動エネルギーや位置エネルギー、あるいは熱エネルギーなど様々なエネルギーがあります。熱エネルギーは触ったら暖かいあるいは熱いものとして、実感しやすいエネルギーです。その他のエネルギーは、形がなく実体がないもので実感を持ちにくいかもしれません。エネルギーは相互に変換できますから、例えば光エネルギーであれば、太陽にかざした手のひらに感じる暖かさのように、熱エネルギーに変換すれば実感がわくかもしれません。

エネルギーの相互変換は身近な現象です。例えば、風船をふくらませると中の空気の圧力が高まり圧力エネルギーを貯められます。風船の口を開くと、勢いよく空気が吹き出します。圧力エネルギーが運動エネルギーに変換されたのです。運動エネルギーを圧力エネルギーに変換することもできます。空気は軽すぎて実感がわきませんから、例えば金槌を振り下ろす場面を想像します。金槌が運動するエネルギーが、釘にぶつかった瞬間に、強い圧力エネルギーに変換されて、釘が木に打ちつけられます。

空気の振動や糸の振動は通信の媒体には不向きです。空気の振動は減衰が大きいので、例えば数キロメートル先まで音を伝えようとすれば、雷くらいの音量が必要です。これでは騒音問題で使えません。船や潜水艦など限られた場所で使われる伝声管のように、有線通信として使われます。糸の振動は、糸がどこかに触れると振動がそこで止まるために、直線でしか糸を配線できず、実用ではありません。

電磁波は静電気の力と磁石の力が相互に変換しあって、何もない空間、真空を伝わる波です。目に見える光も電磁波ですが、遠く数百億光年彼方の宇宙を観察できるように、空間は電磁波を吸収しません。文字通り光の速さでエネルギーが伝わる電磁波は、通信の媒体にもってこいです。電磁波は、Bluetooth low energy技術はもちろん、あらゆる通信で媒体として使われています。

人類が電磁波を媒体として活用するようになって、まだほんの100年ほどです。電磁波はどうやって通信媒体として使われるようになってきたのでしょうか。

==== 電気工学と有線通信の発展 ====

電磁波を扱うには、電源と電気回路が必要です。それらを支える電気工学は1800年台から発達し始めます。

冬場にドアノブを触ると、静電気でパチッとくることがあります。もしも静電気がビリビリと流れ続けてくれれば研究に使えます。しかし、静電気として貯められる電荷の量はとても少なく、パチッというくらいの短い時間で、あっという間に流れきってしまいます。研究には使いづらいのです。

これを一変させたのが、1800年にイタリアの物理学者ボルタが発明した、ボルタ電池です。この異種の2枚の金属板を硫酸につけたもので、金属が硫酸に溶け出すときの化学エネルギーを、電気エネルギーとして取り出す電池です。

電池の発明は、安定して流れ続ける電荷の流れ、電流をもたらし、電磁気学の研究が発達します。そして、1820年にハンス・クリスティアン・エルステッドが、電流を流すと磁石に力が働く現象を発見します。これはアンペールが法則にまとめ、アンペールの法則と呼ばれています。さらに、1831年にマイケル・ファラデーが、電線の周りで磁石を動かすと電圧が発生して電流が流れる現象、電磁誘導を発見しました。

この2つの発見は、電気エネルギーの時代の幕開けをもたらしました。電磁誘導の法則から、電線の近くで磁石を動かすと、磁石を動かす仕事を電気エネルギーに変換できます。つまり、発電機ができます。また電気エネルギーは、アンペールの法則で電流を流して磁石をひきつけたりして、仕事に変換できます。つまり、電気モーターを動かせます。つまり、力学的エネルギーと電気エネルギーとの相互変換を手に入れたのです。

この、発電機と電気モーターの発明で、人類は初めて形のないエネルギーを扱えるようになりました。例えば、山奥にあるダムで水力を電気エネルギーに変換して、網目のように張り巡らされた電線を通じて、工場や都市部に送電できます。電気エネルギーは、電気モーターで動力に、電熱線で熱に変換して利用できます。

エネルギーを送る技術は、そのまま通信にも使えます。例えば、電線を遠くまで伸ばし、その先の受信側には電気モーターや電球をつないでおきます。送信側の電線の一端を電池や発電機に、つないだり切り離したりすれば、受信側では電球が光ったりモーターが回ります。

エネルギーを送れるならば、情報が送れます。仮に、電流を短く流すことをトン、電流を長く流すことをツーと呼びます。例えばアルファベットのAであればトン・ツーのように、文字にトンとツー記号を組み合わせた符号を割り当てれば、符号の組み合わせで文章が送れます。これが、有線での電信です。

長距離の電線敷設や送受信の電気設備や、文字を符号にして送受信する技能者の育成には、大きな費用が必要です。しかし、株取引や軍事など、情報を持つものは常に、情報を持たざるものより強い立場に立てます。天候が悪ければ使えない狼煙や輸送に時間がかかる馬による伝令と違い、電線を敷設すれば天候や気温に左右されず遠方に瞬時に情報を伝えられる電信には、大きな資本が投じられました。

==== 電磁気学と無線通信の発展 ====

クーロンの法則、そしてアンペールの法則や電磁誘導の法則は、場(field、フィールド)の考え方を取り入れると、一般的な物理法則としての表現ができます。電気を帯びたものや磁力を帯びたものの周囲の空間には、空間の位置それぞれで定義できる物理量、つまり場(field、フィールド)があると考えます。

電気を帯びたものの周囲には電場が、磁力を帯びたものの周囲には磁場があります。電場の中に電気を帯びたものを置いたり、あるいは磁場のなかに磁力を帯びたものを置くと、場を通じて力が働くと考えます。

また、場の磁界が時間変化すると電場が発生すると考えます。磁石が動いたから電線に電流が流れたのではなく、電線が場の中にあると、電線の中の電子が電界に反応して動き、電流として検出されると考えるのです。

電場と磁場を時間変化も含めた関係は、ジェームズ・クラーク・マクスウェルが1864年に、マクスウェルの方程式にまとめました。この方程式は、時間変化する磁界が電界を、また時間変化する電界が磁界を生じて、それが波として空間を伝播する、つまり電磁波の存在を初めて示しました。また、計算から求めた電磁波の速さと、当時実験的に知られていた光の速さがほぼ同じであることから、光は電磁波だと示しました。

マクスウェルの方程式が示した電磁波の存在は、1888年に、ハインリヒ・ヘルツが初めて実験室で証明しました。その功績をたたえて、その名前は周波数の単位ヘルツ(Hz)に使われています。1秒あたり1回繰り返すことが1ヘルツです。

電磁波を生み出すには、電界か磁界かを素早く時間変化させなくてはなりません。現代のように高速で動作する電子素子がない当時に、ヘルツは花火放電を利用して電流のオンオフを作りました。そして電磁場の検出には、髪の毛よりも狭いギャップがある輪の形に曲げた針金を使いました。そのギャップに飛ぶ花火を顕微鏡で見て、理論で予想された電磁波の波の性質を示して、電磁波の存在を示したのです。

電磁波を使うと、それまで不可能な通信が実現できます。電磁波は空間そのものを伝わり広がっていきます。ですから、電線敷設のような莫大な時間と費用がかからず、また電線敷設が困難な海や山あるいは国境を超えた通信ができます。さらに、船舶のように、どこにいるかがわからない相手との通信や、不特定多数への放送といった新しい利用場面が生み出せます。

ヘルツの実験以降、無線通信の実用化に向けた発明家たちの競争が起きます。黎明期の無線通信は、困難への挑戦でした。例えば、電磁波の検出には、コヒーラ管という、細かい金属粉を詰めたガラス管が使われていました。これは、電磁波のエネルギーで、金属粉末どうしの小さな間隙で放電が起きて接点の状態が変化して、ガラス管全体での電気抵抗が大きく変化する現象を利用したものです。

電磁波のエネルギーは球面状に広がっていくため、距離の2乗に反比例して急激に小さくなります。ですから、送信する電磁波のごくわずかの比率しか、受信側には届きません。より遠く離れた場所のコヒーラ管を反応させるには、より強力な電磁波を送り出し、電磁波を受け取る受信アンテナをより大きくするほかありません。そのため送受信設備は、大きなものとなります。

20世紀にはいると、真空管の発明による電気回路工学の発展により、無線通信技術は長足の進歩をとげます。真空管は、小さな電圧の変化で、電流を大きく変化させる能動素子です。

電磁波は球面のように広がっていきますから、そのエネルギーの面密度は、球面の表面積に反比例、つまり距離の2乗に反比例して急激に小さくなります。ところが、電磁波のエネルギーは電場または磁場の振幅の2乗に比例しますから、電磁波の電場の大きさは距離に反比例して小さくなっていきます。

19世紀の電磁波検出素子は、金属粉を詰めたガラス管などの、電磁波のエネルギーで生じる物質の状態変化を利用したものでした。ですが、真空管を使えば、距離の2乗で小さくなる受信エネルギーではなく、距離に反比例して小さくなる受信信号を利用できます。

真空管と電気回路の発展は、高感度で安定して動作する受信装置をもたらしました。

さらに、周波数が3メガヘルツから30メガヘルツの間の短波帯と呼ばれる周波数帯の電磁波は、地球を取り巻く大気の高度60キロメートルより上層にある電離層と大地による反射されるので、500ワット程度の電気コタツ1つ分程度の送信電力があれば、地球の裏側とも通信できることがわかりました。

国際的な放送と通信の時代の幕が上がったのです。

==== 電波資源の管理と運営制度 ====




==== 放送と通信そして社会の変化 ====

資源がただあるだけでは、何も生まれません。電波資源は、それを活用したサービスとその消費者が登場して、初めて活用されます。

通信は電波資源の使いみちの1つです。通信は"受け手に状況に対する知識や適切な判断を生じさせるもの"を運ぶものです。通信には必ず通信相手が必要であるように、通信サービスが成り立つにはサービスとその消費者の両方が必要です。

新しいサービスが登場して、そのサービスが規模を拡大して継続していくには、新しくサービスが登場してから短期間のうちに消費者が増えて、十分に普及しなくてはなりません。1925年に日本で初めて放送が開始されたラジオ放送や、1953年に開始されたテレビジョン放送は、短期間で爆発的に普及に成功したサービスと言えます。

放送サービスに関わるものは、放送局と視聴者そして広告主の3者です。放送局と広告主は商業として、視聴者は利用者としてサービスに関わります。現代のようなネットワーク技術やデジタル信号処理技術がなくアナログ信号処理技術しかない当時でも、放送サービスは、これら3者の利害と役割がうまく噛み合うことで普及しました。

放送とは、多数の人に同時に聴取されることを目的として、電波によって音声または音声と映像を受信装置に送ることを言います。東京スカイツリーのような高い塔から電波を送信すれば関東一円をカバーできるように、電波は広い範囲に届きます。放送は、放送局から電波が届く範囲にいる多数の視聴者に同じ情報を同時に伝える、効率の高い方法です。

放送局を立ち上げるには、周波数枠の割り当てをうけて、放送設備に投資をせねばなりません。これには大きな資金が必要です。ですが、電波は広い面に届くので、電気やガスあるいは水道などの各家庭まで配線や配管を巡らせなければならないものに比べれば、桁違いに小さな投資ですみます。

放送局の収入源は、広告主からの広告宣伝費用です。同じように放送をしていても、電波が届く領域で番組を見る人が多くなるほど、広告収入が増えます。ですから放送局は、視聴率をより高くしようと努力をします。

広い領域に同じ情報を届けられる放送は、広告収入との組み合わせに適しています。もしも、視聴者から視聴料金を回収しようとすると、どうなるでしょうか。直接一戸一戸を訪問して回収するほかありませんから、大変な回収費用がかかります。また、もしも見ていないと言われれば徴収する理由がありません。かといって、特定の視聴者だけが見られる放送をアナログ放送で実現するのは、技術的に困難です。

番組が宣伝広告費用で制作されるので、視聴者は、テレビジョン受信機を購入しさえすれば、チャンネルを回して好みの放送を無償で視聴できます。当初は高価だったテレビジョン受信機も、普及による大量生産体制の確立と企業間競争により、急速に価格が低下していきます。

高価で限られた世帯にしかなかったものが、安価になり広く普及しはじめます。ある程度まで普及が進むと、例えば昨日の番組内容が社会での雑談の話題になります。ここまで普及すると、テレビジョン受信機は、社会に属するための不可欠な情報入手手段となります。

このように、テレビジョン放送は、電波が広い領域に面で届く性質と広告モデルとの組み合わせは、普及を加速させる仕組みを持っていました。

限られた電波資源の割り当てをうけた強い立場にある放送局は、より高い視聴率を得られる番組を制作して無償で放送します。魅力的な番組を視聴するためにテレビジョン受信機が大量に売れ始め、それが大量生産体制を生み出し、より安価になっていきます。新しい製品やライフスタイルの広告は、多くの視聴者の消費活動を刺激して、大量消費社会が到来します。

==== デジタル化とネットワークの時代 ====

20世紀の終わりから、半導体製造技術の微細化が進み、高性能なデジタル回路が安価に製造されるようになりました。それが、映像を扱うのに十分な高い演算能力と、高速なデジタル・ネットワークをもたらしました。

21世紀はネットワークの時代といっていいでしょう。デジタル・データ化されたテキストや映像が、ネットワークを通じて世界を駆け巡っています。デジタル・データは、ウェブ・ブラウザやインストールしたアプリケーションを通じて、多種多様なサービスとして体験できます。ネットワークを通じて、世界のどこにいてもサービスを受け取ることができます。

20世紀に普及したラジオ放送やテレビジョン放送の受信機は、アナログ信号処理技術で作られていました。アナログ信号処理技術では、デジタル信号処理技術のような柔軟な情報の蓄積や分配は困難です。ですから、放送局と受信機とが放送規格で強く結びつき、それら全体が大きな1つのシステムとなるように開発されました。

しかし、アナログ信号処理技術で作られたハードウェアは、あとから処理内容を変更することはできません。ですから、新しい技術を取り込み規格を更新するには、一般に広く普及している莫大な数の受信機を全て更新しなくてはなりません。

デジタル信号処理技術の進歩にあわせて、デジタル・テレビジョン放送の技術と規格が作られました。日本では2003年から地上波デジタル放送が開始されました。ですが全国の放送機器と受信機とを、デジタル対応機器に置き換えるには、多額の費用がかかります。地上波デジタル放送の開始からアナログ放送が停波するまでに、9年間かかりました。

こうして普及させた地上波デジタル放送技術には、デジタル化にふさわしく、アプリケーションの実行や、視聴者から放送局にデータを送信する機能が盛り込まれました。ですが、それらの技術は、パズルゲームのようなミニゲームや、番組内での簡単な視聴者アンケートに使われるにすぎません。

放送が、アナログ放送からデジタル放送になっても、広告を収益として視聴率を求めるのは同じです。放送は、莫大な費用と時間をかけてデジタル技術を導入しても、サービスとしての仕組みや形までは変えられませんでした。

一方で、私たちは、ネットワークそしてスマートホンを通じて、動画配信やソーシャル・メディアあるいはソーシャル・ゲームなど、多種多様なサービスに常に触れています。

新しい技術が普及する黎明期には、誰しもが小規模な事業者です。ですから、ネットワークの特徴を活用して、サービスをいち早く提供して、それが人々に受け入れられた時には、急速に成長できます。

ネットワークには、放送と通信の区別はありません。世界中のコンピュータは、ネットワークとネットワークの間をつなぐ(インターネット・プロトコル(Internet Protocol, IP)という技術で、お互いが網目状につながっています。放送も通信も、この技術の上で実現できます。

その特性を活かして、動画配信サービスであっても利用者がコメントを書き込むことができるサービスや、だれもが動画を公開できるサービス、また個人がメッセージをやりとりしたり公開できるソーシャル・メディアが登場しました。

ネットワークの世界では、小さなサービスが急激に成長しました。見たこともない新しいサービスでは、それを理解して利用する人は極めて稀な存在です。ですが、ネットワークの利用人口は2016年で30億人を超えますから、仮に1000人に1人しか利用しなくても、その利用者数は300万人にもなります。よいサービスは利用者の口づてで、爆発的に広まります。
// http://www.soumu.go.jp/joho_tsusin/kids/internet/statistics/internet_01.html
//※	出典：ITU World Telecommunication /ICT Indicators database
//※	2016年は推定値

また、デジタル・ネットワークの進歩は、事業者と利用者の区別を取り払いました。放送サービスに必要な電波資源と放送設備を所有できるのは、大きな企業だけです。ですが、ネットワーク・サービスは、個人所有のパーソナル・コンピュータとネットワーク接続からでも、サービス提供を始められます。

さらに、ネットワーク・サービスの中では、作り手と消費者との区別が曖昧です。動画あるいはスマートホン・アプリケーションは、大企業でも個人であっても、同じ開発環境の提供をうけられます。魅力があり人気があれば、動画が見られた回数やアプリケーションの売上から、作り手に大きな利益をもたらします。

万人に等しく機会が提供されるネットワークの時代でも、事業規模が大きいほど強い競争力が持てる規模の経済が働きます。それは、ネットワークの分野であっても、収益源は広告もしくは課金と販売かの、いずれかしかないからです。

利用者が多くなるほど広告収益は大きくなりますし、課金や販売の管理運営にはある一定以上の費用がかかります。売上規模が大きいほど、サービスやコンテンツの開発と更新により多くのお金を使えます。サービスもコンテンツ提供も、開発と競争そして淘汰とを繰り返し、やがて大きな事業者に集約していきます。

==== 人のネットワークと、ものごとのネットワーク ====

広く普及したスマートホンを通じて、人々は常にネットワークにつながっています。所有することがあたりまえとなったスマートホンを中心とするプラットホームの上で、私達は生活をしています。そして、魅力的なコンテンツやアプリケーションそしてネットワーク・サービスの豊富さが、スマートホンの成長を支えています。

コンテンツの豊富さは、大きなお金の流れから生まれます。魅力のあるコンテンツほど利用者に多く消費され、その売上が次のコンテンツを生み出す資金になります。コンテンツの配布と購入処理を担うプラットホームは、購入手数料から利益を得て、さらによい開発環境や購入体験の提供を目指します。

この、作り手と消費者そしてそれらをつなぐプラットホームという、3つの登場人物達の間で、コンテンツやお金がやりとりされて繁栄していく仕組みを、生物界の生態系になぞらえて、スマートホンのエコシステムと呼びます。

常にネットワークにつながり課金処理がおこなえるスマートホンを通じたサービス開発は、通信販売やソーシャル・ゲームあるいはソーシャル・メディアを急成長させました。さらなる次のサービスを追い求める探索の1つが、私達の身の回りにあるものがネットワークにつながった世界だと考えられています。

私達の身の回りにある電化製品や住宅、あるいは生体情報が取得できる衣服や腕時計といった数多くのものが、今はまだネットワークにつながってはいません。それらがネットワークにつながることが当然となれば、さらなる多種多様なサービスが生み出せるかもしれません。

Bluetooth low energy技術は、その可能性を現実のものとするのに不可欠な、私達とものとの間にある1メートルをつなぐ無線通信技術です。Bluetooth low energy技術は、楽器やキーボードそしてゲーム・コントローラのように従来からある周辺機器に使われ始めました。そして、歩数や心拍を記録するフィットネス用品や電化製品にも使われ始めています。

ものがネットワークにつながれば、より便利になるのではという考えは、古くからあります。例えば、スマートホームと言われる、住宅にある家電製品や太陽光発電システムがお互いに通信をして連携動作が可能になれば、それを利用した新たな生活場面が生み出せそうに思えます。

そのような機器連携を実現するには、様々な機器製造企業が統一した通信技術を採用する必要があります。そして、なんでもできる技術は作れませんから、技術を作るためには利用場面の想定が必要です。スマートホームの分野では、省エネルギーや高齢化社会を課題に設定した技術仕様が作られて、対応製品が発売されています。

ですが、その技術が想定された利用場面は一般に広まってはいません。それは、機器製造販売会社が利益を得るのが、機器を販売したときだけだからです。利用者が、購入した機器をどれほど便利に活用しようとも、また活用しなくとも、機器製造販売企業の利益は変わりません。お金が動かないため、より便利な利用場面を作り上げていこうという活動も生じません。

また、想定利用場面と実際のサービスは違うものです。例えば、エアコンの遠隔操作ができれば、より便利になると思えます。具体的な利用場面として、夏の暑い日に帰宅前にエアコンを稼働させて帰宅時には部屋が涼しくなっている、を考えたとしましょう。これは、暑い夏の日に帰宅して部屋が暑くて嫌だった体験があれば、便利そうに思えます。

ですが、これは20世紀の生活感で考えた便利さです。現代の高い断熱性と気密性がある住宅では、24時間エアコンをつけつづけていても、こまめにエアコンをオンオフしても、電気代にさほどの違いはありません。また、空気を冷やしても、壁や床の表面温度はすぐには下がりません。ですから、帰宅前にエアコンをオンにして室温は低くても、壁や床からの放射熱で暑さを感じます。想像した便利な場面は、21世紀の現代では、エアコンをつけたままにしておけば得られるのです。

生活環境は時代と共に変化していき、また年齢が上がるとともに生活スタイルも変化していきます。サービスは、需要に合わせて柔軟に変化できることが必要です。大きな初期費用を支払い通信規格に適合した機器一式を買い揃えても、当初想定された利用場面での便利さだけで柔軟さがなければ、本当の便利さは享受できません。

機器を購入した後に、利用者が便利さを感じるほど、機器製造販売会社に利益がもたらされるような仕組みがなければ、またスマートホンのように利用者がアプリケーションを選び使う仕組みがなければ、得られる便利さは、その技術が作られたときに想定された利用場面だけでしかありません。

==== サービスとしてのハードウェアの登場 ====

スマートホンとBluetooth low energy技術の登場で、周辺機器というハードウェアが持つ機能と、アプリケーションを通じて提供される柔軟なサービスとを組み合わせて、多種多様な利用場面を作り出すサービス提供者が登場しました。

この新しい分野は、アプリケーション(Application)と周辺機器を意味するアクセサリ(Accessory)の2つの単語を組み合わせた、アプセサリ(Appcessory)という造語で呼ばれています。

アプセサリには、例えば心拍や歩数を24時間測定し続けられる腕時計型デバイスがあります。心拍は身体に密着しなければ測定できません。まさか24時間スマートホンを体にはりつけるわけにはいきませんから、心拍を測定するには、スマートホンではなく、アクセサリが必要です。

ですが、心拍数を計測するだけでは意味がありません。心拍数を計測するアクセサリの小さな表示画面や情報処理能力では、できることは限られます。そこで、スマートホンのアプリケーションが、心拍データから消費カロリーの算出や酸素を取り入れる運動能力の推定や、利用者へのデータ表示を担います。

利用者は、アプリケーションの表示データを見て、目標体重や現在の運動能力を考えて、運動量や食べる量を調整するでしょう。アクセサリだけでは、心拍や運動量の表示するくらいです。アプリケーションだけでは、利用者が求める情報を収集できません。

アクセサリとアプリケーションとが連携してはじめて、利用者は、"受け手に状況に対する知識や適切な判断を生じさせるもの"、つまり情報を得たのです。

ネットワーク技術とデジタル化が放送を変えたように、スマートホンとBluetooth low energy技術との組み合わせが、それまでの前提を覆し新たな可能性をもたらしています。

これまでのネットワークにつながる機器は、その機器だけを購入するだけではなく、通信相手となるコントロール・パネルや通信の配線工事が必要でした。大きな初期費用がかかりました。また、機器専用の通信サービスが必要なものは、毎月通信費用を支払わねばなりません。

アプセサリではスマートホンがあるため、この初期費用と通信回線の問題は発生しません。無線通信ですから、使用する機器だけを購入して、対応アプリケーションをインストールすれば、すぐに利用ができます。また、スマートホンはすでに常にネットワークにつながっていますから、新たな通信回線契約も必要ありません。

ネットワーク連携機器の通信規格は、その規格を満たす機器同士が通信するためにあります。異なる会社が開発した機器同士でも、あるいは10年前に開発された機器と今年開発された機器とでも、規格を満たすならばお互いに通信できなければなりません。これを満たすために、これまでの通信規格は、通信方式だけではなく、通信を通じて機器がどう振る舞うかまでを厳密に定義していました。

しかしこれは、柔軟で素早い対応と多様性とを犠牲にします。新しい機能や機器が誕生するたび、通信規格の更新と更新内容の承認が必要になります。また世界に1つだけの機器を作ろうとしても、通信規格の更新には大変な手間と時間がかかりますから、作れません。

Bluetooth low energy技術は、多様な周辺機器を表現するために、仕様を、通信とデータ表現を定義するコア仕様と、周辺機器の機能と振る舞いの仕様の2つに分離しています。新たな周辺機器が現れても、周辺機器の仕様を追加すればよいだけなので、手間と時間がかかりません。さらに、この仕様にない自分たちだけの独自の機能を定義する仕組みも、提供されています。

Bluetooth low energy技術は、機器の機能と、利用者から見た利用場面とを分離しています。例えば、通信で音や光を出す機能が定義されています。この機能をキーホルダーにもたせれば、物を探す時に音を出させる使い方ができるでしょう。また傘にもたせれば、雨が降るだろう日に傘を持っていくように催促する利用場面が作れます。

音や光を出す機能1つ見ても、利用者には、それが警告であったり通知であったり、利用場面次第で様々な意味に見えます。機能と振る舞いが分離されているため、スマートホンのアプリケーションを通じて、それらの機能を組み合わせて利用場面を生み出し、多様性が生まれます。

20世紀の技術仕様は、規格団体に入会審査を提出して年会費を支払い参加してはじめて、公開されることが多くありました。ですが、Bluetooth low energy技術そしてスマートホンのアプリケーション開発は、誰にでも開かれています。

Bluetooth low energy技術は、通信規格が無償で提供されています。電波を発信するものは、たとえ試作であっても電波法の技術基準を満たさねばなりません。無線モジュールと呼ばれる1000円ほどの電子部品を使えば、電波法の技術基準を満たした電子回路を作れます。スマートホンのアプリケーション開発環境は、無償で配布されています。

アプセサリに使われる技術は、とても高度なものです。ですが高度だからこそ、無線モジュールやアプリケーション開発環境などの1つ1つの要素が、専門家により誰もが道具として使えるものへと整えられています。

Bluetooth low energy技術を道具としてどう活用していくのか、その可能性を切り開くのは他ならぬ私達です。

=== Bluetooth low energy技術の生い立ちとその特徴 ===

無線通信と社会変化の歴史を振り返ると、"受け手に状況に対する知識や適切な判断を生じさせるもの"、つまり情報を伝える技術の進歩と普及が、人の振る舞いを、そして社会を大きく変化させてきました。

Bluetooth無線技術も、その情報を伝える技術の1つです。パーソナル・コンピュータと周辺機器とをつなぐ無線通信技術として1999年に初めて登場したこの技術は、人々の要望と技術進歩そして時代の変化をうまく取り込みながら発展してきました。

ここではBluetooth無線技術の誕生とその発展、そして統合されたBluetooth low energy技術の生い立ちとその特徴とを見ていきます。

==== 周辺機器とその通信規格 ====

かつてのパーソナル・コンピュータには、ヘッドホン端子や、キーボードやマウスを接続するPS/2コネクタ、シリアル・ポートやプリンタ・ポートなど、いろいろな形状の端子がいくつもありました。

かつての周辺機器のインタフェース規格は、周辺機器を製造する企業や業界団体が作っていました。電気信号で情報をやり取りする部分を物理層といいます。物理層と物理層を通じたデータのやりとりとを、それぞれの周辺機器に特化した1つのインタフェース規格にまとめていました。

例えば、キーボードには低速でよいが安価な方式が、またディスプレイには高速なアナログ信号を歪みなく伝える方式が工夫されていたのです。周辺機器の種類の数だけインタフェース規格があるため、かつてのパーソナル・コンピュータには、種類の異なる端子がいくつもあったのです。

これは、1996年に初めての仕様が発行されたUSB(Universal Serial Bus、ユニバーサル・シリアル・バス、略称：USB)や、最初の仕様が1999年に公開されたBluetooth無線技術の登場で、大きく変わりました。これらは、高速なデジタル通信技術と、周辺機器をデジタル・データとして表現するデータ形式、そしてデータを通信でやり取りする手順とを、それぞれ分離して規格にまとめることで、柔軟で汎用のインタフェースを提供します。

通信とデータとの分離は、それまでのインタフェース規格にはない汎用で便利な体験をもたらします。まず、これまでにない新たな周辺機器が登場しても、すでにある十分に高速な物理層をそのまま使えばよく、新たに物理層を開発する必要がありません。新たなインタフェース・カードをコンピュータに増設しなくてもよいのです。

新たな周辺機器が登場しても、そのデータ形式だけを新たに定義するだけですみます。デジタル・データであれば、ソフトウェアだけで処理ができます。その新たなデータ形式を扱えるデバイス・ドライバやアプリケーションをパーソナル・コンピュータにインストールするだけで、新たな機器を利用できるようになります。

新たに作るインタフェース規格は、それ以前の規格よりも優れていなければ作る価値がありませんから、便利で合理的なものになるよう設計されます。

ですが、新しいインタフェース規格が必ずしも普及するとは限りません。また普及が始まっても長い時間がかかることもよくあります。





通信とデータが分離されている、ならば逆に物理層の半導体、周辺機器、オペレーティング・システムのそれぞれの会社が参加してくれないと。企業の連携でもあるのです。
利用者が新しいインタフェース規格を使い始めるには、すでに今ある周辺機器を一度買い直すほどの魅力がなければなりません。新しいインタフェース規格を利用者が使うには、
インタフェースは、異種の機器がお互いにやりとりをする接続点です。
そのインタフェース規格に、様々な分野の企業が数多く参加するには、その規格を採用することが企業の利益につながらなくてはなりません。また、

そして、異種の機器やソフトウェアの作り手のよりどころになるのが、インタフェース規格です。さらに、作られたものがインタフェース規格を満たしていることを確認するのが、認証制度です。

ハードウェアの置換、買い替え、参入企業の勢い、

新しいインタフェース規格を使うには、今使っている周辺機器を一度捨てて買い直す。
は、今使えるハードウェアを、売れないと、それを支える企業群、
それを買い求める利用者、インタフェースは物理層、一気に浸透しないと意味がない。今使えるハードウェアをすべて入れ替える。

新しいインタフェース規格は、通信とデータが分離されるがゆえに、周辺機器などのハードウェアだけではなく、データを処理するオペレーティング・システムやデバイス・ドライバなどのソフトウェアが整備されて、はじめて機器が使えるようになります。ですから、物理層を提供する半導体やデータを処理するオペレーティング・システムなど、周辺機器だけではなく、業種が異なる数多くの企業の参加が必要です。

もしも、新しい規格の採用で、物理層を提供する半導体を販売する企業だけが大きな利益を得るのであれば、他の業種の企業は参加しないでしょう。あるいは、ある業種の企業がすでに参加しているから、競合にある企業は規格に参加させないなどの、閉じた運営をしていては、多種多様な製品は登場しないでしょう。

規格、運営、特許の取りまとめ、ライセンシング。
利用者、初めて体験できる。異種の機器がお互いにつながる。オープン、無数の組み合わせ。
ハードウェアだからアップデート不可能。
無数の組み合わせ、時間を超えて、後方互換性。



合理的な手段であるものが、

それぞれの企業にとって規格に参加することで利益があること、
また
また規格を作る企業などが自社の利益を優先して排他的な

それぞれの企業にとって参加するに足りる利益があること、
規格がオープンで排他的な活動をしないだろうということ、支配的ではないこと、

無数の組み合わせ
業種の異なる企業が参加するには、参加の意思判断。
普及、さらに規格、将来も使えること、時間がたっても使えること、1社でがめないこと。

通信とデータとを分離したことで、1つの周辺機器、
が数多く販売されなければなりません。それら製品の無数の組み合わせが動作するように、規格に適合していることを認証する制度も不可欠です。

通信の半導体、OS、ドライバ、周辺機器。オープンさ。
通信とデータを分離したことで
会社の連携。
単純で明快な体験。挿せば使える。
そして今購入した製品が10年後も利用できる後方互換性、柔軟さ、高速化
体験が便利であること、汎用であること、後方互換性や、柔軟で多様であること、

USBは、マウスやキーボードからハードディスクにいたる多種多様な周辺機器に採用されていて、周辺機器をUSB端子に有線接続するだけで利用できる便利さが広く受け入れられています。


無線LANはイーサネットの無線化。

USBを例にして:
基本の体験がシンプル(挿せばOK、データと)、汎用(高速化、後方互換)、柔軟で多様(カスタム品)

USBの登場で、利用者は機器をUSB端子に接続するだけでよくなりました。かつてのように、どの周辺機器をどの端子に接続するか、どのように設定するかなどを、利用者が考える必要はありません。USBは有線接続で電源も供給するので、電源をつなぎ忘れたり電池切れが原因で動かなくて困ることもありません。またUSBは通信技術ですから、パーソナル・コンピュータのUSB端子が足りなくなってもUSBハブで通信を分岐して接続口を増設できます。

高速化:
物理的に信号をやりとりする部分を物理層と呼びます。登場した当初のUSB 1.0の物理層の通信速度は12メガビット/秒で、キーボードやマウスなどの低速な通信速度でよい周辺機器に広がっていきました。それが、USB 2.0では最大480メガビット/秒に、そして3.1では10ギガビット/秒に達しています。USBは、高速通信が必要なストレージを含めた、あらゆる周辺機器の必要を満たすインタフェース技術となっています。

USB3.0で導入された高速な通信技術は、USB2.0までの技術とは全く異なる互換性がない技術です。USB3.0では、USB2.0までのコネクタの形状は同じで、新たな物理層の端子を追加したコネクタを新たに定義することで、強引ですが後方互換性を保っています。

またUSBは、半導体技術の進歩にあわせて

BT接続、機器一覧、表示。接続、アプリケーションからの見え方。
任意の機器を管理する方法がない。有線を無線化する。
単発特殊なもの。一般的な定義しかできない。シリアル通信端子。独自のデバイスドライバ、アプリケーションとセットで。でもモバイル機器。

高速化。
Bluetooth無線技術、シリアル端子の置き換え。マイクやキーボードといった有線接続。
ハードウェアを扱うため、低消費電力、製造費用。電力供給ができない。限られた電池=通信は低速。


規格を提供するだけではなく、
USBは規格を提供するだけではなく、その規格に適合しているかを検査して認証する仕組みも提供しています。この認証制度の運用があるから、様々な機器を無数に組み合わせても機能するのです。
コネクタが同じならば挿せば動くだろうと思うのが人間というものです。
ですから、インタフェース技術の発展では、後方互換性を保つことが重要視されます。USBは、コネクタに挿せば周辺機器が使えるようになる単純な体験を、後方互換性を保ちつつ、より高度な技術へと進歩してきました。



==== Bluetooth無線技術の変遷
