== はじめに ==

スマートホンが存在しなかった頃の生活や社会が、どのようなものだったかを、思い出せるだろうか。21世紀になると、通信とネットワーク技術が急速に一般に普及した。2001年には、雑誌や新聞がインターネットが社会を大きく変えると大きく記事に取り上げ、ADSL回線と常時接続サービスとが普及した。2008年のiPhone3GSの発売で日本にも到来したスマートホンの波は、2010年頃から爆発的に広がり、スマートホンの世帯普及率はわずか2年間で9.5%から49.5%に達した。ブロードバンド回線と高速モバイル通信、そしてスマートホンの登場と普及とが、我々の生活や仕事のありようを変えてしまった。
// 総務省Heisei２７年度通信情報白書　インターネットの普及状態
// http://www.soumu.go.jp/johotsusintokei/whitepaper/ja/h27/html/nc372110.html

例えば、新幹線で移動して一泊する旅行をするとしよう。今ならば、切符の購入と宿泊の予約は、スマートホンを取り出してその場で数分で完了する、ささいな作業でしかない。だが1990年代では、まず分厚い紙の時刻表をたぐり、乗車駅と発車時間とを調べて、それから鉄道駅近くにある旅行代理店まで行き、窓口で鉄道の乗車券と宿泊予約券とを発券してもらっていた。初めてインターネットを通じて切符を購入した時は、その目新しさと便利さに感激すらしたものだが、あっという間にそれらが日常になってしまうと、もはやそれらがなかった頃に、どうやって生活をしていたのかすら思い出せない。

スマートホンから得られる便利さが、スマートホンという1つの機械だけでは成り立たないことは、すぐにわかる。手元にあるスマートホンを、機内モードにして、ネットワークから切り離してみよう。せいぜい、高性能なデジタルカメラか音楽プレイヤーくらいにしか使えないだろう。もしかすると、音楽はストリーミング・サービスを使っていて、もう音楽プレイヤーにすらならないかもしれない。いわゆるクラウドと呼ぶ、ネットワークでつながる世界のどこかにあるコンピュータ群と、そのクラウドを活用して様々なサービスを提供する数多くの事業者と、そしてスマートホン、この3つの連携が便利さを生み出しているのだ。

スマートホンは持ち歩くものだから、有線通信は使えない。外部との連携には、無線通信が使われる。スマートホンに搭載されているいくつかの無線通信技術のうちの1つが、Bluetooth Low Energy技術だ。人が動画を見たり通話をしたりするための無線通信技術は、より途切れずより高速なものへと進歩していく。しかし、Bluetooth Low Energy技術は、我々の身の回りにある無数のものに使えるように工夫された、機械と機械とが無線通信し続けるための無線通信技術である。

この技術が話題になり始めたのは、世界で初めてBluetooth4.0を採用した機器、iPhone4Sが発売された2011年10月14日からだろう。Bluetooth Low Energy技術は、Bluetooth3.0までの技術とは、電波をやりとりする方式すら異なる互換性がない技術だ。Bluetooth4.0は、Bluetooth3.0までの技術に、Bluetooth Low Energy技術という新技術を追加して、異なる2つの技術をBluetooth無線技術という1つのブランドにしたものと言っていい。

2011年のあの日に登場したiPhone4SとiOS５は、お互いに連携しあうハードウェアとiOSアプリケーションを、誰にでも開発できるものにした。iOS5は、通信相手を探して接続して通信をして切断するまでのBluetooth Low Energy技術の利用を、すべてのiOSアプリケーションとその開発者とに提供した。Bluetooth4.0の半導体や無線モジュールを販売している会社は、新しい分野での将来の売上を確保しようと、未来の事業者に向けて扱いやすい開発キットや無線モジュールを、安価で手軽に入手できるようにした。

Bluetooth Low Energy技術は、誰もがそれぞれの立場と目的とで活用できる技術だ。プログラミング教育の現場では、タブレットで作ったプログラムと、モーターやセンサーを組み合わせて作ったロボットとの通信に、Bluetooth Low Energy技術が使われている。また、Bluetooth Low Energy技術を活用した活動量と心拍とを記録し続ける腕時計型デバイスと、それと連携するアプリケーションとを開発して、健康と体力を増進するサービスを立ち上げた人々もいる。

世界のどこかにあるコンピュータ群とスマートホンとの連携が便利なサービスを支えているように、身の回りにある様々なものとスマートホンとの連携は、新しい価値を生み出す土壌となるだろう。Bluetooth Low Energy技術を活用した周辺機器は、マウスやキーボードといったこれまであった周辺機器とは異なり、アプリケーションと一体になって初めて価値を生み出す。それを表現するために、アプリケーション(Application)と周辺機器を表すアクセサリ(Accessory)とを組み合わせたアプセサリ(App-cessory)という造語があるほどだ。

本書を手にされている方は、教育や趣味あるいは仕事で、自分であるいは自分達でハードウェアやアプリケーションを開発しようとしていたり、開発はしないが事業計画を作成して実際に作るのは誰かに依頼しようとしているなど、各々の立場や目的でBluetooth Low Energy技術に関心があるのだろう。だが、誰も無線通信技術の専門家になりたいわけではないのだから、無償で公開されているとはいえ2000ページを超えるBluetooth無線技術の規格書を精読しても、労力の無駄でしかない。

Bluetooth Low Energy技術を、自分の手を動かして実際に活用できるように解説するのが、本書の目的である。Bluetooth Low Energy技術は、簡素なわかりやすい技術だが、簡素であるために通信の物理からデータ表現の定義、その振る舞いまで開発することになる。また馴染みのない概念もあるため、最初は戸惑ったり混乱することもあるだろう。私も、初めての試作開発案件で、サービスやキャラクタリスティクスという初めて見る言葉に戸惑い、それらの意味がわからずに困惑したのを思い出す。

また、Bluetooth Low Energy技術が、機械と機械との通信技術であることも、戸惑う理由になるかもしれない。通信には、必ず通信相手が必要である。通信を通じて提供されるサービスといえば、テレビジョン放送や音楽や動画のストリーミング・サービスあるいはウェブ・サービスなど、通信の先に人がいるものばかりである。だから無線通信技術は、より高速で途切れることなく連続したデジタル・データ通信へと進歩する。しかし、Bluetooth Low Energy技術は、少し異なる。機械と機械との通信は、無駄な電力を消費しないように、お互いが通信可能な時にだけ、素早く必要なデータのやり取りを完了するように設計されている。Bluetooth Low Energy技術は、人が画面をみて操作をする用途ではなく、機械と機械とが直接電波で通信をするシステムを作るための、もっと言えば、ネットワークや情報処理の世界と我々の身の回りの世界そのものとを、つなげる技術と言える。

また、無線通信規格それ自体には、形はない。ちょうど将棋や囲碁などで、明確に定義されたルールがありプレイヤー同士がルールに従って初めてゲームとして成立するように、通信規格は、通信でお互いに作用し合うシステムをくみ上げるための通信のルールとして働く。ゲームをするにはルールを知らねばならないが、ルールを知るだけでは必ずしも楽しいゲームとははならないように、無線通信規格だけを詳しく知っても、それだけでは意味はない。

無線通信システムは、いくつもの無線機、また無線機の中には電子回路や制御ソフトウェアなど、いくつものハードウェアやソフトウェアの組み合わせで作られる。無線通信規格には形はないが、そのシステムやシステムの要素として、無線通信規格は形を成す。したがって、Bluetooth Low Energy技術を見ていくには、技術解説に加えて、無線通信規格がどのように活用されてシステムが組み上げられるのか、またシステムを構成する様々なソフトウェアやハードウェアそれぞれについて、無線通信規格のどの部分をどのように実装していくのかを、見ていくことになる。

Bluetooth Low Energy技術を、部分要素ごとに見ていくことは、チームでBluetooth Low Energy技術に取り組む時にも役立つだろう。領域が異なれば、技術者の背景知識も考え方も立場も異なり、したがってBluetooth Low Energy技術の見え方も異なる。デバイスのデータ構造は誰が定義すべきだろうか。ハードウェア設計者が定義したものは、ソフトウェア設計者から見て妥当な設計となるのだろうか。また逆に、ソフトウェア設計者が定義したならば、それはハードウェア設計から妥当なに見えるのだろうか。アプセサリという造語が示すハードウェアとアプリケーションとの連携を生み出すには、開発チームの中の開発者も、お互いに連携しあわなくてはならない。

ハードウェアはどこかから調達して、ソフトウェアだけを開発するから、Bluetooth Low Energy技術を知る必要がないかといえば、そうとも限らない。Bluetooth Low Energy技術を活用した電波を出す小さなビーコンを設置して、数メートルから数十メートルの領域を設定して、その領域への出入りをアプリケーションで検出できる。電波ビーコンは市販されているしビーコンを活用するためのサービスもいくつもあるから、誰にでも活用できる。しかし、領域の検出の振る舞いは、電波の伝搬の振る舞いそのものだから、よりよく活用しようとすれば、技術の基礎的な理解は欠かせない。そして、その理解は、さほど大変でも難しいものでもない。

企画や事業立案でも、Bluetooth Low Energy技術は知るべきものとなるだろう。インターネット、モバイル、あるいはソーシャルゲームといった新しい言葉が次々に登場するが、実際に社会を変えてきたのは、いち早く新しい言葉に取り組んだ事業会社の行動の結果である。我々の身の回りとの相互作用を生み出す強力な手段となるBluetooth Low Energy技術は、ゲームのルールのようなものだから、ある思いつきが実現できるかどうかは、それがルールの範囲に収まるかどうかをみていけば自ずと判断ができる。

// Bluetooth Low Energy技術は、教育教材としてラジオコントロールのロボットを作るのにも、人の健康を向上させるサービスや、あるいは今はまだ世界のどこにもない何かを生み出すのにも活用できる手軽な技術手段である。本書が、それぞれの方々のそれぞれの立場や分野で、新しい価値を生み出す土壌への手引書として役立てばと思う。

=== 章の構成 ===

=== サンプルコードと実行環境 ===

=== 謝辞 ===

=== 本書につての問い合わせ ===

=== 免責と商標について ===






== はじめに ==


Bluetooth無線技術は、1999年にその最初の規格Bluetooth1.0を公開してから、電池で動く機器でも使える高速な近接無線通信技術としてBluetooth3.0まで進歩を重ねてきた。今では、ワイヤレスのヘッドホンやキーボードなど、周辺機器に広く使われている。そのBluetooth無線技術が、2010年に発表したBluetooth4.0は、それまでのBluetooth3.0までの技術に、それまでの技術とは電波をやりとりする方式すら異なる新しい技術 Bluetooth Low Energy技術を統合した。だから、Bluetooth4.0の中には、これまでのBluetooth3.0までの技術と

Bluetooth3.0までの技術とBluetooth Low Energy技術とは、まったく別の技術なのだ。スマートホンのアプリケーションから
小さな電池1つで何年も無線通信ができる
アプリケーションから、無線機器。その名前にBluetoothという単語が入っているが、
これは2つの大きな転換をもたらした。
通信相手の探索、接続と切断、そして通信。デバイスの発見。データベースアクセス。抽象化された。
それらが電池消費量を極限まで小さくする工夫と合わせて。
1つは、昨日まで世界のどこにも見なかったBluetooth Low Energy技術が、その日を境にiPhone4Sとして世界中に一気に広がったことだ。

学習教材。プログラミングの変数が、外部の世界に反映される。

ハードウェア、クラウドのAPIを作れ。考え方がまるで違う。考え方が異なっている、別のもの。違う。
理解しろというより、理解できない。頭を入れ替えろ。あるいは、学習者を連れてきて、スキルだけ移転しろ。

プロトコル、組み込み、ハードウェア、ファームウェア、利用者の体験、事業の組み立て。アプリ開発。

ライセンスの問題、技術的な問題。
アプリケーション開発、一般アプリケーション開発者。
もう1つのクラウド。目の前1メートル。
世界で初めて、
世界で初めてBluetooth4.0を採用した。2つの意味で。

Bluetooth low energy技術という単語を初めて目にしたのは、2011年10月14日に発売されたiPhone4Sを見た時だった。この半年前、6月6日に開催されたApple社の世界開発者会議の基調講演では、iPhoneのオペレーティング・システムiOS5の、200を超える新機能が発表されていた。その数多くの機能の中に、Core Bluetoothという単語があり、これが開発者の一部では話題になっていた。Made for iPhone(MFi)プログラムと呼ばれる特別な契約をApple社と締結しなければ開発すらできないiPhoneの周辺機器が、一般開発者に開かれるのではないかと期待されたのだ。


Bluetooth low energy技術は、21世紀に登場した新しい無線通信技術と言っていいだろう。無線通信技術を、我々の身の回りにある数多くのこまごましたものにまで広げるには、電池の消費量を極限まで小さくしなければならない。なぜなら、例えば1ヶ月で電池が切れてしまうものが身の回りに30個もあれば、毎日なにかしらの電池交換をしなければならなくなるからだ。電池交換の手間の大きさが、無線通信で得られるあらゆる恩恵を帳消しにしてしまう。

Bluetooth無線技術は、1999年のBluetooth1.0から、Bluetooth3.0まで、電池で動く機器に使える省電力で高速な無線通信規格として進歩を重ねてきた。

Bluetooth3.0までの技術は、ヘッドホンのように、データが高速に流れ続ける用途
Bluetooth low energy技術の特徴は、小さな電池1つでも年単位で無線通信し続けられる超低消費電力無線通信技術と、多種多様な"もの"や"出来事"を、デジタル・データとして表現する強力な仕組みにある。

しかし、1つの技術ですべての要望に応えることはできない。特に、電池消費量を桁違い
Bluetooth low energy技術は、Bluetooth3.0までの技術とは電波をやりとりする方式すら異なり、互換性がない。2010年に公開されたBluetooth4.0は、Bluetooth3.0までの技術に、新しくBluetooth low energy技術を追加したのだ。

しかし、1つの技術であらゆる場面を満足させることはできないものだ。
しかし、1つの技術で、あらゆるすべての場面を満足させることはできないものだ。
Bluetooth無線技術は、2010年に公開したBluetooth4.0で、それまでのBluetooth3.0とBluetooth low energy技術を統合した。

Bluetooth無線技術は、2010年のBluetooth4.0で、それまでのBluetooth3.0までの技術とは電波をやりとりする方式から異なる後方互換性がない新技術、Bluetooth low energy技術を統合した。つまり、Bluetooth4.0とは、Bluetooth3.0に、新しい技術を

"Bluetooth"を冠する、Bluetooth無線技術が2010年に統合した新技術である。
は、ヘッドホンやマウスあるいはキーボードなどの周辺機器に広く普及している。


Bluetooth無線技術は、1999年に最初の規格Bluetooth1.0が公開されてから、2009年のBluetooth3.0まで、電池で動く省電力で高速な近接無線通信技術として進歩を重ねてきました。今では、Bluetooth無線技術は、ワイヤレスのヘッドホンやキーボードなどの周辺機器に広く用いられています。

しかし、周辺機器に限らない、もっと多種多様な身の回りにあるものに、無線通信を広げようとすると、Bluetooth3.0までの技術とは方向性が異なる技術が必要となりました。無線通信が使われる場面を新たに開拓するために、Bluetooth無線技術が2010年のBluetooth4.0で初めて統合した、それまでのBluetooth3.0までの技術とは電波をやりとりする方法すら異なる新技術、それがBluetooth low energy技術です。

当たり前のことですが、通信には必ず通信相手が必要です。これが、新しい無線通信技術は、登場してから普及し始めるまでに何年もかかったり、あるいは普及しないまま忘れ去られる理由です。1つの製品で新しい無線通信技術を採用しても、通信相手がいなければ通信ができず、意味がありません。通信技術は、機器として普及するものではなく、通信でお互いが繋がる機器の群れ、つまりシステムとして普及するものなのです。

Bluetooth low energy技術は、2011年秋に世界で初めてBluetooth4.0を採用した製品 iPhone4S が販売されてから、1~2年ほどという驚くべき短期間で世界中に普及しました。Bluetooth4.0は、それまでのBluetooth3.0に、新しくBluetooth low energy技術を付け加えた規格です。ですから、パーソナルコンピュータやスマートホンの最新機種が、Bluetooth4.0を採用すれば、自動的にBluetooth low energy技術が普及したのです。







個人や、チームであること。決して専門家ではないこと。また専門家である必要もないこと。
通信プロトコルに、異なる手段で関わることになること。
個人利用から、小規模、大規模な事業規模まで、至る所で活用できること。

Bluetooth Low Energy技術は、明確な用途もなく広く普及した無線通信技術です。
Bluetooth low energy技術は、Bluetooth4.0は、それ以前のBluetooth3.0に、Bluetooth low energy技術を足し加えたものです。そして、Bluetooth low energy技術は、Bluetooth3.0までの技術とは、電波をやりとりする方式すら異なるのです。Bluetooth無線技術は、無線通信技術が使われる分野をさらに広げるために、Bluetooth3.0までの技術の発展する方向とは違う
Bluetooth4.0
では、Bluetooth low energy技術は、使い道がない技術なのでしょうか。

いらないこ、使い道がないのか。
また、Bluetooth low energy技術は、その存在に気づかれない技術かもしれません。
無線技術、ワイヤレスのイヤホンやヘッドホン。用途が決まった。見えない電線。無線通信のすべての機能がアプリケーション任せ。

本書を手にされている方は、もしかするとBluetooth low energy技術という単語を聞いたことがあったり、あるいは何かの目的のためにこの技術を使いたいのかもしれません。それは、スマートホンから無線で操作するロボットを作ることかもしれません。あるいは、マイクロ・ロケーション技術を活用する、美術館の展示案内アプリケーションを開発しようとしているのかもしれません。それとも、素晴らしいアイディアを思いついて、プロトタイピングを始めようとしているのでしょうか。

その技術の存在に気づくかどうかは別として、Bluetooth low energy技術が身近なのは、私たちが毎日持ち歩き常に触れているスマートホンが搭載しているからです。

普及しただけではなく、自由度。エコシステムについての話。
通信には、必ず通信相手が必要です。
無線通信の使い道。
当たり前のことですが、通信には必ず通信相手が必要です。新しい無線通信技術が登場しても、通信相手になる何かがなければ、その技術を採用する製品が登場しません。製品が登場しなければ、その技術が広まることはありません。


また、Bluetooth low energy技術を使う分野も、人それぞれでしょう。もしかすると、モーターを制御する電気回路やファームウェア、それらを無線を通じて操作するスマートホンのアプリケーションとを、一人で開発しているのかもしれません。マイクロ・ロケーションに使う電波ビーコンの開発で、無線通信回路や通信を制御するファームウェアを担当しているのでしょうか。あるいは、ハードウェアやアプリケーションなどの異なる分野の専門家でチームを作り、プロトタイピングを繰り返しているのでしょうか。

通信には必ず通信相手が必要ですが、Bluetooth low energy技術でお互いに情報をやり取りするのは、機械と機械です。Bluetooth low energy技術を活用する場面は、

無線通信技術というと、なにか難しい専門家が扱うもので、自分が作ったり活用する場面は想像し難いかもしれません。
確かに、20世紀までは、無線通信は専門家や知識のあるアマチュアが楽しむものでした。ですが、21世紀に爆発的に普及したスマートホンと、2010年に新たに公開されたBluetooth無線技術の規格が、無線通信技術を道具として、誰もが利用して活用できるものへと変えました。

よくある勘違い。万能ではない。用途を限定して、開かれた。ものすごいインパクト。
Android、iOS、Windows、すべてで共通して使える。MFi。
Bluetooth Low Energy技術、とても小さなん電池で年単位の無線接続を保持する超低消費、で情報をやり取りする技術。
用途が違うから、用途に合う、その用途で使える技術が必要であったこと。スマホという通信相手が、アプリと同時。ベンチャー。
組み込み機器、何かに組み込まれて表からは見えない。
パーソナル・コンピュータ、ソフトウェアを入れ替えて、自分で使う。機器単体として、買ってすぐに使える。
組み込みシステム（くみこみシステム、英: Embedded system）
工作、作りたい。サービスを開発したい。ハードウェアから、試作、量産。
アプリ開発、ファームウェア、C言語、半導体によって異なる。
TypeScriptのサブセット、それを内部でコンパイルして実行する。それ自体が、かなり高度なもの。
実際に知ってしまえば、そんなもの。知る必要のないもの、知っていても手も足も出ないもの。
知っていればいいけど、知らないと危ないもの。



近接無線通信技術を"もの"に使うには、それまでの無線通信技術よりも、消費電力がさらに桁1つは小さい技術が必要でした。例えば、毎日頻繁に使うマウスやキーボードであれば、電池交換が2ヶ月に1回でも問題はありません。その電池交換頻度でもよいならば、 Bluetooth3.0 の技術でも実現できます。ですが、例えば壁掛け時計に無線通信機能を搭載したために、それまで2年に1回だった電池交換が、2ヶ月に1回になるようでは、商品として売れません。これは、高速かつ低消費電力を目指してきたBluetooth3.0までの技術の改良で、実現できるものではありません。そのために、Bluetooth3.0までの技術とは開発の発想や前提が異なる、Bluetooth low energy技術が新たに統合されたのです。

そして、GATT基盤を活用できるスマートホンの登場が、Bluetooth low energy技術を爆発的に普及させました。パーソナル・コンピュータの分野でのBluetooth low energy技術は、マウスやキーボードの消費電力が無線通信の分だけ小さく電池交換の手間が少しだけ小さくなる、なくてもあっても気がづかないものでしかありません。ですが、スマートホンの分野では、フィットネスやヘルスケアあるいはスマートホームの分野で、活動量や心拍センサーあるいは電化製品など多種多様なハードウェアをアプリケーションと連携させる、必要不可欠の技術となったのです。



Bluetooth無線技術は、1999年に登場してから、電池で動く機器に使える省電力で高速な近接無線通信規格として、発展を重ねてきました。今では、Bluetooth無線技術を採用したワイヤレス・ヘッドホンやワイヤレス・キーボードなどのワイヤレスな周辺機器に広く使われていて、ほとんどのパーソナルコンピュータやスマートホンに採用されています。そのBluetooth無線技術が、2010年に公開された Bluetooth4.0 で初めて統合した新しい無線通信技術が、Bluetooth Low Energy技術です。つまり、Bluetooth4.0 以降のBluetooth無線技術には、必ずBluetooth Low Energy技術が入るのです。ですから、最新機種が Bluetooth4.0 を採用すれば、勝手にBluetooth Low Energy技術も普及したのです。


世界で初めてBluetooth4.0を採用したのは、2011年に発売されたiPhone4sです。また、iPhone4sのiOS5は、アプリケーションから、Bluetooth low energy技術で通信している機器と、GATT基盤を通じて直接やりとりできるようになりました。アプリケーションとハードウェアとの連携から生まれた新たな魅力は、アプリケーション(Application)とアクセサリ(Accessory)の単語を組み合わせたアプセサリ(Appcessory)という造語で呼ばれます。

いまでは、Bluetooth low energy技術を活用した子供向けプログラミング教材が、二千円ほどで販売されています。スマートホンやタブレットでプログラムを実行すると、デジタル・データが無線通信で教材に送られて、モーターの動きや音として出力されます。また、教材の機械スイッチを押すと、その情報が無線通信を通じてプログラムに伝わり、画面表示を変更させたりできます。目には見えないデジタル・データを、自分たちのいるリアルな世界の出来事として見ることで、論理的に考える力と、プログラムで物事を解決するスキルを身につけられます。

つまり、Bluetooth low energy技術を活用したハードウェアは、誰にでも二千円ほどで作れるのです。ですが、機械スイッチを押すとスマートホンの画面表示が変わるかを、先生に見せても、それはプログラミング学習の成果物でしかありません。ですが、それを世界的なネット通信販売会社の社長が手にして、ボタンが押されるだけで商品が届くサービスを始めると発表したらどうでしょうか。これまでにない購入体験をもたらす発表として、世界中の人々が注目するでしょう。アプセサリは、たとえ同じハードウェアでも、それと組み合わされるアプリケーションやサービス、あるいは誰が手がけるかで、その価値はまるで異なるのです。

アプセサリは、どうすれば生み出せるでしょうか。それは、どこにでもある紙や鉛筆あるいは絵の具で、誰でも小説や絵画を作れますが、どうすれば商業商品あるいは歴史に残る名作を作れるかと問いかけるようなものです。ですが、思いついた何かを、魅力あるものに仕上げるには、道具と、道具を活用する知識と経験が必要です。アプセサリでは、Bluetooth low energy技術を実装した無線通信回路やアプリケーション開発環境が、その道具にあたります。

Bluetooth low energy技術は、身近にある道具として活用できる技術です。無線通信技術の専門家が、通信に必要な無線通信規格を整備して半導体素子を製造しています。子どもの学習教材にも使われていて、加速度や心拍センサーを使う方法や、アプリケーションの作り方が公開されています。アプセサリは、電子工作として個人で楽しむことも、自社事業を高効率化したり、新規事業の創出にも使えます。

本書が、新しい価値を生み出そうと行動する方々にとっての、ガイドブックとして役立てばと思います。

=== 章の構成 ===

=== サンプルコードと実行環境 ===

本書で使用しているサンプル・コードは、Github https://github.com/reinforce-lab/BluetoothLowEnergyInAction　にあります。このサンプル・コードは、ライセンスは MIT License です。つまり、誰でも無償で無制限に扱えます。ただし、作者はソフトウェアに関してなんらの責任を負いません。また、著作権表示および許諾表示とをソフトウェアのすべての複製または重要な部分に記載しなければなりません。

本書のiOSアプリケーション開発環境は、以下のとおりです:

- オペレーティング・システム: macOS High Sierra (バージョン 10.13) またはそれ以降。
- 開発環境: Xcode 9.2 またはそれ以降。
- 開発言語: Swift 4.0。
- iOSのバージョン: iOS11。
- iOSデバイス: iOS11が動作するiOSデバイス。iPhone5s 以降のiPhone、iPod touch(第6世代)、およびiPad(第4世代)以前を除くiPad。

iPad用のアプリケーション、
Swift Playgrounds
iOS10と違いはない。

iOSアプリケーションのBluetooth low energyの機能は、シミュレータでは動作しません。ですから、iOSサンプル・アプリケーションは実機でのみ動作します。

iOS実機でのアプリケーションの実行とデバッグには、XcodeをインストールしたMacと、自分のApple IDで登録したiOSデバイスのみが必要です。Xcode７以前と違い、有償のApple社の Apple Developer Program への加入は必要はありません。

=== 謝辞 ===

=== 本書の問い合わせ先 ===

本書への疑問や質問は、ツイッター・アカウント https://twitter.com/u_akihiro[@u_akihiro]　もしくはもしくは電子メール・アドレス u-akihiro@reinforce-lab.com に送ってください。問い合わせ内容は、本書の内容や正誤表の更新のために、活用するかもしれないことを了解ください。

=== 謝辞 ===

本書の Bluetooth low energy技術の解説の多くは、2012年からの (有)トリガーデバイス 佐藤 忠彦さんとの技術調査および技術セミナーや開発案件( http://www.triggerdevice.com/blebu/index.html )から得られています。

<ハードウェアはゴミである本>
<Senstickの開発>

また、表紙カバー絵は(有)トリガーデバイスの池本 貴子さんに描いていただきました。あえて技術書らしくない表紙として、(有)トリガーデバイスのキャラクター"どくはきむらさき"を描いていただきました。

スマートフォンと物や物事との関わりについては、
http://ma-tilde.com[株式会社 Matilde(マチルダ）] 白鳥　啓さん 、
http://goccojapan.com[(株)GOCCO] 森 誠之さん、
http://akamatsu.org[情報科学芸術大学院大学(IAMAS)] 赤松 正行さん
とのブレイン・ストーミングおよびディスカッションから、多くの気づきを得ています。

本書のタイトル「うれしい! たのしい! びー・える・いー!」は、技術解説ではなく、
技術を手段として活用するためのガイドブックであることを表すタイトルが思いつかず悩んでいた時に、
https://twitter.com/ksksue[@ksksue]さんからいただきました。
@ksksue さんは、Internet of Things スタートアップをアクセラレートするためのソフトウェア＆ハードウェアプロジェクト
http://www.physicaloid.com[Physicaloid]
を展開されています。

このほかにも、岐阜県大垣市で開催されたBluetooth low energyセミナーやiBeaconハッカソン、またBluetooth low energyのプロトタイピングでのやりとりなどで、数多くの方々からいただいた知見も盛り込んでいます。


=== 免責と商標について ===

- 本書に登場する会社名、製品名、サービス名は、各社の登録商標または商標です。
- 本文中では、<!-- ®、™、© --> &reg;、&trade;、および&copy;マークは明記していません。
- Bluetooth &reg; のワードマークおよびロゴは、Bluetooth SIG, Inc.が所有する登録商標です。
- 本書の内容に基づき実施または運用したことで発生したいかなる損害も著者は一切の責任を負いません。
- 本書の内容は2016年12月時点のものです。本書で紹介した製品およびサービスの名称や内容は執筆時点から変更される可能性があります。


Bluetooth無線技術は、後方互換性、同じロゴがついているのに、繋がらないじゃないか。10年後、ハードウェアとして実装される。ソフトウェアをアップデートしたり、安心して使われる、世界中で使われるために、安心感が普及の原動力。
Bluetooth3.0

後方互換性とは、新しい規格で作られたものが、それ以前の規格で作られたものと通信ができることです。Bluetooth無線技術は、ヘッドホンやマウスなどの周辺機器に使われています。Bluetooth無線技術のロゴがついていれば、どの機器との組み合わせでも、何年間でも使い続けられるこそ、消費者は安心して製品を購入できます。もしも、新しい技術になったから、これまでの技術で作られている周辺機器はもう使えなくなってしまうようでは、誰もそのような技術を使いたいとは思わないでしょう。

周辺機器に使われるBluetooth無線技術では、消費者に安心感を与えるために、後方互換性がとても重要なのです。周辺機器が設計されて製造され販売され、そして破棄されるまでに、10年間あるいは20年間はかかるかもしれません。後方互換性が保たれているからこそ、最新機器を購入しても、すでにある周辺機器を引き続き利用し続けられる安心感が保たれます。また最新機器同士であれば、より高速でより低消費電力な最新の無線通信技術で、さらに快適な体験が楽しめます。




この技術は、電気回路やアプリケーション、技術者のものではない。アプリケーションやサービス開発、あるいは事業計画、事業を作る方、商品の企画、新しい試み、作り実験するため。



21世紀には通信技術が広く普及しました。高速デジタル通信サービスとスマートホンの普及は、ソーシャル・メディアをはじめとする、ネットワークを通じて提供される多種多様なサービスをもたらしました。私達は今、毎日膨大な情報が流れ続ける高度な情報化社会に生きています。玄関でスマートホンの天気予報を見て傘を持っていくかを決め、メッセージ・アプリで連絡をとりあい仕事を進め、クレジットカードや非接触カードで食品を購入しています。はるか遠く離れた相手に情報を伝える無線通信技術は、情報で動く今の私達の生活に不可欠な技術です。

通信規格が必要であること、それは分野で支配的になること、それは専門家で閉じる世界と閉じない世界があること。
あたりまえのことで見過ごしがちになりますが、通信には必ず通信相手が必要です。
目には見えない電波で、つながるといっても、消費者には安心感が必要なのです。特に消費者が使うもの。専門家が扱う、
放送設備などであれば、

その通信相手の確保には、無線通信規格の普及が不可欠です。無線通信規格は、電波をどのタイミングでやり取りするのか、やり取りする情報表現の形式などの方式や技術をまとめたものです。

しっかりした規格を作り、様々な企業のそれぞれの製品が規格を満たしているかを検査して認証することで初めて、消費者は

消費者に将来にわたり安心して製品を使い続けられると信頼されて

世界中の様々な企業がそれぞれに製造する装置の間で無線通信ができるためには、無線通信規格、あたりまえすぎて忘れがちですが、通信をするには通信相手が必要です。鋳型コスト。ですが、しっかりした規格を作るだけでは、何も普及はしません。

初めて、その規格は普及できます。
技術や方式が無線通信規格にまとめられます。
世の中には、数多くの無線通信規格があります。利用される場面ごとに、必要な通信速度や距離あるいは消費電力、そして製造コストが異なるからです。ですが、利用場面が同じ

急に宿泊が必要な出張をするとしましょう。スマートホンであらゆるサービスが提供されている現代では、移動経路の確認も宿泊予約も、スマートホンを自分で操作をして数分で完了する、些細な作業でしかありません。ですが、これが1980年代ならば、まず分厚い時刻表をたぐり移動経路を調べて、駅前にある旅行代理店に行き、窓口で電車と宿泊先の予約チケットを発券してもらい、それを封筒に入れて駅から出発していたでしょう。

情報で動く社会にとって、情報の流れを担うデジタル通信技術は、重要な技術です。利用分野ごとに、最適化された無線通信技術があります。その中で、本書で取り上げるBluetooth low energy技術は、2010年に規格が公開されたBluetooth4.0で、初めてBluetooth無線技術の一部として統合された超低消費電力無線通信技術です。この技術は、身の回りにあるスマートホンやパーソナル・コンピュータなど、すでに皆さんの身近に普及しています。マウスやキーボードなどの周辺機器、あるいは活動量や脈拍を記録するウエアラブル・デバイス、さらには無線でモータやLEDをスマートホンから操作できる安価なプログラミング教材など、そうとは気づかずにこの技術を利用しているでしょう。

ものと情報とのはざまにある技術です。ですから、ハードウェア分野からみれば、今まで扱ったことがない無線通信技術やアプリケーションあるいはネットワーク・サービスに触れることになります。またソフトウェア分野からみれば、今まで関わったことがない形あるハードウェアの製造や販売が必要になるかもしれません。これまでに経験がないことを始めることを、壁と感じるか、挑戦ととらえるかは、人それぞれです。

ですが、しっかりした規格を作るだけでは、何も普及はしません。様々な会社が製造する数知れない製品が規格を満たしているかを検査して、認証することで、あらゆる通信機器を組み合わせも、問題なく通信ができることを保証するのです。消費者に将来にわたり安心して製品を使い続けられると信頼されて初めて、その規格は普及できます。

本書で取り上げるBluetooth low energy技術も、数ある無線通信技術の中の1つのです。その名前にある"Bluetooth"が示すように、Bluetooth low energy技術は、2010年に規格が公開されたBluetooth4.0で、初めてBluetooth無線技術に統合された新技術です。その特徴は、やはりその名前が示す通り、桁違いに消費電力が小さな超低消費電力無線通信技術にあります。

Bluetooth無線技術は、1999年のBluetooth1.0から2009年のBluetooth3.0まで、後方互換性を保ちつつ、より高速かつ低消費電力な無線通信技術として進歩を重ねてきました。周辺機器に使われるBluetooth無線技術では、消費者に安心感を与えるために、後方互換性がとても重要なのです。周辺機器が設計されて製造され販売され、そして破棄されるまでに、10年間あるいは20年間はかかるかもしれません。後方互換性が保たれているからこそ、最新機器を購入しても、すでにある周辺機器を引き続き利用し続けられる安心感が保たれます。また最新機器同士であれば、より高速でより低消費電力な最新の無線通信技術で、さらに快適な体験が楽しめます。

ところが、Bluetooth low energy技術は、それまでのBluetooth3.0とは電波をやりとりする方式から異なる、互換性のない新技術です。高い周波数の電波を送信したり、微弱な信号を増幅して信号を読み取る無線通信は、そもそも電力を消費するものです。毎日頻繁に使うマウスやキーボードであれば、2ヶ月に1回の電池交換でも問題はありません。ですが、例えば壁掛け時計に無線通信機能を搭載したために、それまで2年に1回だった電池交換が、2ヶ月に1回になるようでは、商品としては売れないでしょう。近接無線通信技術が使われる場面をさらに広げていくには、これまでとは桁違いの低消費電力無線通信技術が不可欠でした。そのために、Bluetooth無線技術は、Bluetooth3.0までの技術とは開発の発想や前提が異なる、Bluetooth low energy技術を統合したのです。

新しい無線通信技術は、通信相手がいなければ利用できないため、なかなか普及することはありません。ですが、Bluetooth low energy技術は、あっという間に世界中に普及しました。2010年に規格が公開された翌年、2011年に世界で初めてBluetooth4.0を採用したiPhone4sが発売されました。それ以降の、パーソナルコンピュータやスマートホンの最新機器はBluetooth4.0を採用しました。Bluetooth low energy技術は、これという必要性や利用場面がないのに、Bluetoothのブランド力で普及したのです。

Bluetooth low energy技術は、GATT基盤という、多種多様な"もの"をデジタル・データとして表現する強力な仕組みを備えています。また、iOSやAndroidのオペレーティング・システムは、アプリケーションに、GATT基盤を通じてデバイスに自由なアクセスを解放しました。スマートホンという通信相手と、デバイスと自由に連携できるアプリケーションの登場から、これまで見られなかったサービスと連携するデバイスが登場しています。この、アプリケーションとの連携が新たな魅力を生み出すデバイスは、アプリケーションとアクセサリとを組み合わせたアプセサリという造語で呼ばれます。

様々なアプセサリを見ていると、私達の身の回りに広がるリアルな世界と、デジタル無線通信の向こう側にあるだろうネットワークの世界とが、気配や雰囲気のような、ぼんやりとした目には見えない関わりを通じて変化していく様子が感じられるようになります。

ところで、消費者ではなく作り手として、
2000ページを超える規格書、良い書籍、スマートホンのアプリケーションを作る、ファームウェアを作る。
500円で、1万円で。
を通して、私達のリアルな世界とネットワークの世界がお互いに関係して変化していく様子は、いつ見ても不思議なものです。Bluetooth low energy技術を楽しみ、活用するための、一貫した基礎知識をここにまとめます。


無線通信を通じて何かを、企画や事業計画、ハードウェア、アプリケーション、そして製造と流通管理、
サービスと連携したデバイスのファームウェアの更新計画、知っていればいいだけのこと。使い方。
アプリケーションと

スマートホン、アプリケーション開発、
1万円程度、500円程度、センサーを含めて、ボタン1つの何もないデバイスが、見立てで、ビーコンや、サービスが変わる。
誰かに売るのではなく、社内のシステムとして。
フィットネスやヘルスケアの分野での身につけるウエアラブル・デバイスや、接近や小さな領域を知らせるマイクロロケーション技術の電波ビーコン、Appleペン、クラウドと連携する電化製品、

急速に、普及。アプリケーション、アプリケーションの中に振る舞い、データ表現の強力な仕組み。カスタムな機器。フィットネス、ヘルスケアの分野。ネットワークを通じて、センサー、身につける。
Bluetooth low energy技術は、私達の身の回りにある様々な"もの"に使えるように工夫された無線通信技術と言えます。

私達の身の回りには、エアコンや電気ストーブ、あるいはシーリングライト(天井照明)や洗濯機のような電化製品や、腕時計やスマートホンのように、いつも持ち歩く小さなデバイスなど、様々な"もの"があります。このような"もの"に必要とされる無線通信は、小さなデータを、たまにやり取りすることです。例えば、エアコンのリモコンであれば、1日に数回、オンオフと設定温度の情報をやり取りできれば十分でしょう。

そして、"もの"の無線通信は、電池消費の小ささが求められます。例えば、置き時計の電池を最後に交換したのがいつか、思い出せるでしょうか。ふっと時計を見たときに止まっていたら、電池を交換すると思いますが、その頻度は1年か2年に1回でしょう。あるいは、光発電機能があり電池を交換する必要すらないかもしれません。もしも毎週あるいは毎月のように電池交換が必要な時計を発売しても、電池交換の手間がかかるようなものは売れないでしょう。

Bluetooth low energy技術の特徴は、その名前が示す通り、小さな電池で何年も通信し続けられる超低消費電力無線通信技術にあります。高い周波数の電磁波を送信したり、微弱な信号を増幅して情報を受信する無線通信技術は、そもそも相応の電力を必要とします。無線通信を活用して便利な"もの"が作れるとしても、無線通信のために頻繁な電池交換の手間が必要にな流のでは、かえって不便なものにしかなりません。
電池交換の手間をより小さくしようと、時計の技術は進歩してきました。
もしも今、電力消費が大きくて毎週あるいは毎月のように電池交換が必要な時計を販売しても、その手間が問題にならないくらい新たな魅力がない限りは、売れないでしょう。

Bluetooth low energy技術は、私達の身の回りにある様々な"もの"に使えるように工夫された無線通信技術と言えます。Bluetooth low energy技術の特徴は、その名前が示す通り、小さな電池で何年も通信し続けられる超低消費電力無線通信技術にあります。高い周波数の電磁波を送信したり、微弱な信号を増幅して情報を受信する無線通信技術は、そもそも相応の電力を必要とします。無線通信を活用して便利な"もの"が作れるとしても、無線通信のために頻繁な電池交換の手間が必要にな流のでは、かえって不便なものにしかなりません。

便利さのなかに、電池交換の手間と引き換え、電池が切れたまま放置されてるだけ。
無線通信は、電力消費量の大きなもの。
2.4GHz、高周波、とても高い周波数の信号を扱う、微弱な電波を増幅して情報を読み出す受信技術。
パソコンの内部クロックのような、
便利な機能、そのために電池交換の手間、電池が切れたままで放置、無線通信技術で解決しなければいけない。

数ある無線通信技術の中でも、
ラジコン、放送、
BLE、新しく登場した、プラットホーム、普及。他の通信だと、WiFi、ルータまで、その後はネットワーク技術者。
アプリケーション、アプセサリ、統合した。1つのまるっとセットで。結構ハードウェアから手がけることになる、
今まで一緒に仕事をしてこなかった業界の、協力。ゼロから新規事業を立ち上げる、チーム。外注かもしれないし。
使える技術として、1つ1つの技術の意味とその活用方法をまとめてみようと。小さなプロジェクト。だけど、全体が含まれる。
知識、同じ無線通信でも、立場が異なれば、見方が異なる。その異なりを解説してみようかなと。

さて、本書を手に取られた方は、Bluetooth low energy技術自体に興味があるか、なにかの目的のために、この技術
に関心を持たれた方かと思います。

ちょうど世界的に爆発的に普及し始めていたスマートホンが、Bluetooth4.0を採用したことで、瞬く間に世界中に普及したのです。

フィットネス、肌に密着し続けるウエアラブル・デバイス
マイクロ・ロケーション、近接と領域検出、電波ビーコンとして、
アプリケーション、サービスと連携した、今までにない新しい領域を生み出している。

サービスを立ち上げるためのデータを生み出すところを確保する、個人単にフィジカルに情報を物理的に表現したい、
何か持っている機材なり事業を情報を絡めて別のものに展開する。

Bluetooth low energy技術は、目の前にあるものや、せいぜい30メートル程度までの範囲にある身の回りにある様々なものと、直接通信する技術です。人間には電波を感じ取る能力も、多種多様なデジタル・データを扱う能力もありません。しかし、スマートホンがあります。身の回りにある様々なものと、スマートホンとが直接通信をします。そして、スマートホンのアプリケーションが、多種多様なデジタル・データを扱います。

Bluetooth low energy技術は、スマートホンやスマートホンの向こう側に広がるインターネットといったデジタルの世界と、我々が住むリアルな世界との間をつなぐ、無線通信技術と言えます。あるいは、ものと無線通信とを1つのものにする技術とも言えます。

数多くの無線通信技術に支えられています。スマートホンを通じて、ネットワークのどこかから、移動経路や今日の天気を入手したり、あるいはビデオ通話やテキスト・チャットのやりとりで仕事をしたりと、もはや無線通信技術があることを前提として、日常生活が形作られています。

空気のような技術、それを使って、空気のようなサービスに欠かせない、ハードウェアが要素に入る、他に選択肢がない。競争力。
スマートホンは常に持っている、常に肌に密着させるわけにはいかない。みじかな置物、電池交換、置き時計。
ネットワークを通じたサービスが普及した時代、押せば商品が送付される押しボタン、物事が繋がる、目には見えないけど。

今までにない技術で実現されるものは、今までにない社会や常識、日常。冷蔵庫が普及していない時代は、生鮮食料品を保存できない、毎日お買い物、市場。

技術者、何かを作る人、事業として考える人、いわゆるインターネット・オブ・シングス(Internet of Things, IoT)

目に見えない無線通信技術、数多くの無線通信技術、情報を知ることで人の振る舞いは変化する、
情報で社会が動くかのような錯覚を覚えるまで。ほんの100年前に実用化された無線通信技術は、
電子メールやソーシャル・メディア、ネット・ニュース、経済や株式投資、毎日のお天気、

作れる無線通信技術、アプリケーション、規格がなければ、規格があっても、1社による支配的なもの、様々な役割の関わり。
その中で、2010年に登場したBLEは、短い期間で爆発的な普及、みじかで使われている、大きく成功した

しかし私達は、普段の生活で通信を気にすることはありません。スマートホンを取り出せば、それはいつでもどこでも通信ができて、すぐにサービスが利用できることが、あたりまえなのです。それがあたりまえになるのは、携帯電話の無線通信それ自体がサービスとして提供されているからです。携帯電話の会社の中で、無線通信の技術者たちは、高速で途切れにくい高品質な通信技術の開発や運用をがんばります。そのサービス提供の費用は、利用者が支払う月額料金で賄われます。

私達は、通信サービスの提供を気にすることもありません。通信には必ず通信相手がいます。携帯電話の直接の通信相手は、携帯電話の基地局です。ですが、スマートホンのアプリケーションの通信相手は、いわゆるインターネットの向こう側にある、世界のどこかにあるサービス事業者のサーバーです。携帯電話網は、それ自体がサービスでありながらインタネットの通信の一部分でしかなく、空気のように意識されないものです。

このような、インターネットとつながるための無線通信技術とは逆の方向に、私達の目の前や身の回りにあるものとつながるための無線通信技術があります。

Bluetooth low energy技術は、高度なデジタル通信技術です。通信相手となるアプリケーションまで作らねばなりません。しかし、この技術は、ロボット制御やプログラミング教育に用いる子供向けの理科教育教材に活用されるほど、手軽に始められるものです。とても高度な技術だからこそ、詳細な細かい実現のための技術を知る必要なく、その原理と仕組みとを知り、その仕組を組み合わせることで、多種多様な場面に活用ができます。

2017年7月5日 上原 昭宏

=== 章の構成 ===
無線LAN、携帯網。通信し続けられれば良い。高速なデジタル通信。意識することはない。
意識する。それも、ハードウェア、スマートホンのアプリケーション、あるいは企画や事業計画。
もちろん必要な知識の粒度や細かさは異なる。
そして、どのような目的でも、Bluetooth low energy技術に直接触れることになります。
身近な技術。身近の意味は、自分たちで扱える技術。面白いのは、道具として扱える。
普通の無線通信技術は隠れているもの。
システムの一部、課金でキャリア。モバイル通信網、月額課金。
本書が取り上げるBluetooth low energy技術は、いくつもある無線通信技術のなかでも、

とても身近


その一方で、Bluetooth low energy技術は、4000円程度の子供向け理科教育教材に使われて、ロボット制御やプログラミング教育教材に活用されています。無線通信の電子回路も、スマートホンのアプリケーションも、どれも高度な技術で作られていますが、高度だからこそ、誰もが扱える部品化されています。手順どおりに、あるいは知識があるなら自分で考えて、組み合わせることで様々なものを作れます。


作れる、使える技術。エコシステム。アプリケーション開発、

周辺機器、新しい事業のための、イベントのための仕組みとして使われている、機器を購入して利用する、
機器だけ、機器+アプリケーション、アプリケーションだけ。
アプリケーションだけ、機器だけ、機器+アプリケーション。

Bluetooth無線技術 = 電線を省略する技術。ヘッドホンや、テザリング。

Bluetooth無線技術

さらに、Bluetooth low energy技術を使う分野が、いくつもの分野にまたがります。
使われる目的は、多種多様です。

ある方は、キーボードのような周辺機器を開発したいのかもしれません。あるいは、新しく始めた事業のために、まだ誰も見たことがないような機器と、その連携するアプリケーションとを開発するのかもしれません。ひょっとすると、イベントの企画にビーコンを活用するのかもしれません。

Bluetooth low energy技術は、それが使われる目的が多種多様で、また目的を実現する手段がいくつもの分野にまたがります。
本書を手にされた方は、なにかの目的があり、その目的のためにBluetooth low energy技術を利用したいのだろうと思います。
Bluetooth low energy技術は、すでに広く世界中に普及しています。

ハードウェア、ソフトウェア、融合。万人が使うわけではないが、ある人には便利な毎日使う機能。

Bluetooth low energy技術の活用は、技術、企画、事業。
作るものが決まっている、作るものを決めて作る、作ったものを売る、
多種多様、工夫次第で利用方法が広がる、エコシステム、スマートホン。

でも活用するとなると、
Bluetooth low energy技術の利用は、技術開発だけをみても、いくつもの分野にまたがります。


身の回りの様々なもの->売れるから
多種多様->エコシステム、電線ではない。
利益の源泉。
趣味、機器販売、なにかプラットホーム化や独自のハードウェア、
手段と、作り上げるための分野。
使われる目的。
開発者視点で見ていても、
分野、手段、また、目的のためのBluetooth low energy技術の利用は、いくつもの分野に広がります。周辺機器の開発であれば、電子回路や無線通信回路そして通信制御のプログラミング

様々な目的のためのの利用は、


Bluetooth low energy技術の活用では、これまでの無線通信技術ではあまり見られなかった、いくつもの分野の人たちがチームを組み関わり合うことがよく見られます。

Bluetooth low energy技術は、

これまでの無線通信技術では見られなかった、とても広い分野で多種多様な使われ方をしています。
利用分野のまたがり:
このように、Bluetooth low energy技術の利用と一口に言っても、電子回路や無線通信回路、デジタル通信技術や通信制御のプログラミング、あるいはスマートホンのアプリケーション開発やネットワーク・サービス開発など、この技術はいくつもの分野にまたがります。

だから関わる方は、技術職とは限らない:

おや、要素。
電子回路や無線通信回路、デジタル通信の制御、ファームウェア、スマートホンのアプリケーションやネットワーク・サービス。開発者。
作るものが決まっていて、それを満たす仕事。これから世に問うもの。何も作るわけではなく利用、組み合わせて、体験を作り出すもの。デザインとか野望とか。
それらを束ねる事業計画。経営そのものとか、ベンチャーとか。

試行錯誤する長い時間、開発者を張り付かせる、かゆいところに手が届かない。
ハードウェア、ソフトウェア、ネットワーク・サービス、
技術開発、事業利用、家電分野プラットホーム。


このBluetooth low energy技術は、それ以前の無線通信技術と異なる、おもしろい特徴がいくつもあります。


それが登場する以前の無線通信技術とは

新しい技術は、登場しても普及するとは限りませんし、また普及に長い時間がかかることもよくあります。しかし、Bluetooth4.0は、Bluetooth low energy技術を統合しました。そのため、最新のBluetooth無線技術を採用するスマートホンやパーソナル・コンピュータには、Bluetooth low energy技術


は、Bluetooth4.0で初めて、Bluetooth low energy技術を統合しました。

新しい技術の普及には、ジレンマがあります。
新しい技術が登場しても、それまで利用場面がないから新しい技術

この超低消費電力無線通信技術は、Bluetooth無線技術に統合されたことで、

電池交換の手間を解決する、


Bluetooth low energy技術が利用される分野は、キーボードやマウスなどの周辺機器や、フィットネス・サービスの一部に組み込まれる活動量計などのウエアラブル機器、あるいはオリエンテーションなどのイベントでのビーコンなど、様々です。その実現手段も、機器開発だけをすればよいもの、サービスとして連携する機器とアプリケーションとを開発するもの、あるいはサービスとして提供されている機器やアプリケーションを活用するものと、様々です。

新しい技術は、技術だけでは売れないから、普及もしない。


// BLE、高速に普及した技術
// 目的があって、そのための手段として利用したい方。多いですよね。
// 出会ったのが2011年、iPhoneと連携するアプリケーション開発。
// はじめは、単なる無線通信、インタフェースかと思っていたけど、違った
// 面白いのいっぱい出てきました。
// 結構苦労していると思います。既存のところは。
// いまも、通信規格って普通は進歩が遅いけど、めちゃくちゃ更新が早いです。
// 最後の1メートルをつなぐ技術なので。
// チームで仕事するとき、あるいは誰かに頼むとき。企画の人が技術の本質をわかっていないと企画できない
// ブラックボックスと、ブラックボックスのままでいいところと、実際の細かい所、

Bluetooth low energy技術

// 高度、だから誰でも使える、ちょっと知っておくこと
// 2011年から、少し開発もして経験として、知っておくことをまとめてみる。


Bluetooth low energy技術が登場する以前から、いくつもの超低消費電力無線通信技術が登場しています。しかし、それらの技術は今も普及しているとはいえません。超低消費電力無線通信技術として単体で登場したそれらの技術は、例えば、よく電化製品のリモートコントローラに提案されます。しかし、赤外線方式よりも部品代金が高くなるが、無線通信だからこそ実現できる画期的なユーザ体験がなければ、無線通信を採用する理由はありません。



さらに、スマートホンのアプリケーション開発環境は、スマートホンのアプリケーションにBluetooth low energy機器とやり取りする機能を一般のアプリケーション開発者に解放しました。また、Bluetooth low energy技術を活用した、近接と位置を検出するマイクロ・ロケーション技術も提供されています。

Bluetooth low energy技術に対応したスマートホンの普及と、そのスマートホンのアプリケーションから周辺機器が自由に扱えることが、アプリケーションと連携する多種多様な周辺機器が生み出される素地になりました。

Bluetooth low energy技術が登場する以前の周辺機器は、キーボードあるいはマウスなど、単体で機能する機器でした。ですが、Bluetooth low energy技術の登場は、機器とアプリケーションそしてネットワーク・サービスとの連携が価値を生み出す、新しい分野をもたらしました。この新しい分野は、アプリケーションと周辺機器を意味するアクセサリとを組み合わせた"アプセサリ"という造語で呼ばれます。

アプセサリの登場は、Bluetooth low energy機器の開発環境をも大きく変えています。単体で機能する周辺機器は、周辺機器を開発する会社だけで開発をすすめられます。しかしアプセサリの開発は、これまでハードウェアを扱ってこなかったサービスやアプリケーションを担う会社と周辺機器を担当する会社との、密な連携が必要です。

また、ネットワーク・サービスやアプリケーション開発の分野では、技術情報はオンラインで広く公開され、誰もが開発に参加できる開かれた開発者文化が一般的です。その開発者文化にあわせるように、Bluetooth low energy機器の開発情報もオンラインで広く公開されるようになりました。開発機材は5000円程度の安価なものを通信販売で購入できます。

Bluetooth low energy技術の豊富な開発資料と、誰もが開発に参加ができる開かれた環境で、開発機材を入手して手順に従えば誰でも機器を開発できます。しかし、その手順から一歩外に飛び出そうとすると、無線通信技術だけではなくハードウェアそしてアプリケーション開発までの広い範囲にわたる大量の知識が必要になります。

本書は、Bluetooth low energy技術を道具あるいは手段として活用する方々、あるいはアプセサリに関心がある方々のためのガイドブックです。Bluetooth low energy技術の特徴と限界を、この技術を構成する無線通信技術そしてハードウェアやアプリケーションの関わりから、広く全体を見渡していきます。

また、多様な背景の個人あるいはチームが、そのよりどころにするテキスト・ブックでもあります。Bluetooth low energy技術に関心があるのは、個人かもしれませんしチームかもしれません。技術者かもしれませんし企画を担当する方かもしれません。アプセサリは、これまでになかった分野の人々の関わりの中から生まれてきます。そのため、電気回路や情報処理の専門知識がなくとも内容が理解できるように努めました。道具としての技術活用の基礎知識と、実際に技術を活用していくための詳細情報とをまとめています。

身近なあらゆるものがネットワークとつながる世界が、本当に実現するのか、またもし実現したとすれば具体的にどのような社会になるのかは、まだ誰にもわかりません。それは、インターネットと言う単語が話題になった2000年頃に、現在のインターネットを日々の生活で利用している社会を、誰も具体的には予想し得なかったのと同じです。

ですが、情報を得た人の振る舞いは変化します。人の振る舞いが変わるのであれば、それがどのようなものであれ、人の集団である社会も変わっていくでしょう。

本書が、新しい価値を生み出す方々にとっての、ガイドブックとして役立つことを望みます。

2017年4月12日 上原 昭宏



Bluetooth low energy技術は、Bluetooth4.0ではじめて統合された新技術です。2016年の執筆時点での最新規格は Bluetooth4.2 です。本書は、まず Bluetooth4.2 の仕様書に基づいて解説をして、必要なところで Bluetooth4.0、4.1 との差異を述べます。
