
=== Bluetooth Low Energy技術の活用とその概要 ===

通信には、通信相手が必要である。電波による無線通信は、相手が電波を受信できる範囲にいること、その相手が電波を受信しようと待ち受けていること、そして相手が受信した信号から意味を読み取れなければならない。

この通信のやりとりの方法を決めるのが、通信規格である。ちょうど囲碁や将棋などのゲームにおけるルールのように、通信規格には形はないが、これがなければ通信が成り立たない。通信規格は、通信機の中にぎっしり詰まっている高周波回路や通信制御ソフトウェア、あるいは信号をやり取りする順番や時間など、通信システムを構成する有形無形の様々な要素としてそこにある。

ゲームのルールを覚えれば、ゲームはできる。しかし、面白いゲームができるかどうかはプレイヤーの技量次第だろう。また、自分がプレイヤーとして参加するだけではなく、誰かのプレイを観戦や解説をしたり、記録を残していくのも、ゲームとの関わりだろう。ルールを知ってから、どのような楽しみ方をするのか、その関わり方をするのかはいろいろある。

この章では、まずいくつかの立場や目的ごとに、Bluetooth Low Energy技術との関わりを見ていく。そして、共有すべき基礎知識として、Bluetooth Low Energy技術の概要をのべる。

==== あなたとBluetooth Low Energy技術 ====

スマートホンには、携帯電話網、WiFi、そしてBluetooth無線技術の3つの無線技術が搭載されている。Bluetooth Low Energy技術の活用は、その他の無線通信技術の活用とは異なる。

まず、物理的に直接通信する相手と、デジタル・データをやりとりする相手とが異なる。携帯電話網とWiFiは、物理的に通信するのは、携帯電話の基地局やWiFiルータといった広大なネットワークと接続するための接続点、情報的に通信するのは、世界のどこかにあるコンピュータ群である。接続点から先の通信網がどのように作られているかは、気にする必要はない。デジタル・データはパケットという小さな単位に分割されて、インターネット・プロトコルで世界中のネットワークを中継されて、たまに欠損もあるだろうがたいていは、相手にまで届く。

Bluetooth Low Energy技術は、近接無線通信技術と呼ばれるように、物理的にも情報的にも、通信するのは電波が直接届く近くにいる相手である。Bluetooth Low Energy技術には、インターネット・プロトコルのような他のデバイスのためにデータを転送するネットワーク機能はない (メッシュネットワーク技術については、xxxで解説する)。多種多様なものをデジタル・データで表現する仕組みと超低消費電力に適した通信プロトコル、ジェネリック・アトリビュート(Generic ATTribute, GATT)基盤を通じて、直接つながる。

この通信相手の違いが、携帯電話網とWiFiで作る何かと、Bluetooth Low Energy技術で作る何かを、異なるものにする。携帯電話網やWiFiを活用して作る何かは、スマートホンで動くネイティブあるいはウェブ・アプリケーションと、インターネット・プロトコルを通じてアプリケーションと連携するサーバー・アプリケーションになる。そのサーバーは、世界のどこかのデータセンターできんきんに冷やされている何千何万台のサーバーのうちの一台で、それ一台が何十ギガバイトものメモリや高速なネットワークやプロセッサがある強力な計算機だろう。そして、データセンターへの莫大な設備投資と釣り合いが取れる開発投資がなされた、アプリケーション開発環境が提供されている。新技術を採用したり、あるいは利用者を飽きさせないように、スマートホンで動くアプリケーションとサーバー・アプリケーションはネットワークを通じて随時更新される。

Bluetooth Low Energy技術では、スマートホンで動くネイティブ・アプリケーションと連携するものは、腕時計型で活動量を記録し続けるデバイスや家電製品の操作回路、あるいは電波ビーコンなどの、それ単体でケースに入っているか、何かの大きな製品の中に組み込まれた、小さなハードウェアである。無線通信の高周波回路と通信や製品の内部制御を行うマイクロ・プロセッサを組み込んで、何らかのハードウェアを作ることになる。このプロセッサは、低価格で製造するために、また限られた電力で長期間動くための厳しい消費電力の要求から、処理に必要最小限のリソースしかなく、メモリは多くてもせいぜい数百キロバイトと、サーバーやスマートホンと比べると2桁から3桁小さい。また、ハードウェアは製造されれば機能や振る舞いが変わることはないから、設計の不具合でもない限り、ファームウェアと呼ばれるその中で動く小さなプログラムを更新する必要は生じない。

通信相手が、クラウドの場合と、身の回りの小さなものの場合では、開発の様子が異なってくる。開発手法を見てみよう。前者は、スマートホンにしてもサーバーにしても十分に大きなメモリ量と処理能力があり、開発環境には莫大な投資がなされているから、最新の開発言語が駆使されて、開発者の層も厚い。後者は、機能を小さなメモリ量で実装する制約があり、最新のスマートホンやサーバーの大きなメモリ量を前提に開発される最新の開発言語は使えないし、通信だけではなくハードウェアの機能も実装するためハードウェアの理解も必要となり、そのような開発環境で経験と能力を兼ね備える開発者は限られる。

また、配布も異なる。例えば、ゲーム・アプリケーションであれば、クラウドと呼ばれるコンピュータ群で動くサーバー群に、世界中からスマートホンがアクセスして、アプリケーションをダウンロードする。デジタル・データは、ほぼコストゼロでコピーできて、ネットワークを通じて瞬く間に世界中に広がることができる。ゲームの更新も、更新データの販売もネットワーク上で完了するし、更新データはネットワーク経由で配布できる。身の回りのものは、ものだから、1つ1つ製造して、ネットショップやリアル店舗の店頭に並べて販売し、購入されたものを配送して、利用者の手元に届いて、初めて利用が始まる。

身の回りのものに使う技術は、クラウドやネットワークといったデジタル・データで完結できる分野から見ると、手間ばかりかかるように見える。実際、手間だ。しかし、この手間は、形あるものを取り扱うところから出てくるもので、通信技術のために生じるものではない。これまでの携帯電話網やWiFiでは、通信のための月額課金が受け入れられなかったものや、電子回路の費用や電池交換の手間の問題が解決できず販売にいたらなかったものが、Bluetooth Low Energy技術の登場で可能になった、その可能になったものにかかる手間を、これまで見てきたわけである。

では単なるサービス利用者としてではなく、作り手としてのBluetooth Low Energy技術との関わりは、どのようなものがあるだろうか。まず、視覚的なプログラミング教育教材で、スマートホンとロボットを動かす部品との無線通信として利用しているかもしれない。もっと踏み込んで、技術者として生体センサーや電波ビーコンの無線通信回路や通信制御ファームウェアを開発するかもしれない。あるいは、技術者でなくとも、電波ビーコンを活用した新たな屋内移動誘導体験を生み出すような、新規事業あるいは企画立案をするのかもしれない。

この3つの場合について、目標の設定と成果物、成果物に至る時間軸、そしてそれらに通信規格がどのように関わるか、そして必要となる通信規格の知識を見ていこう。

===== 教育教材とBluetooth Low Energy技術 ====

Bluetooth Low Energy技術は、プログラミング教育の教材に活用されている。プログラミング教育の目標は、手順を定義すれば世界がその通りに動くことを理解すること、そして、その手順を生み出すための論理的な思考力を身につけることである。タブレットやパーソナル・コンピュータでプログラムを作成して実行すれば、色とりどりの図形が移動したり、図形に触れれば色が変わったり、あるいは衝突判定を組み入れてゲームにしたりと、どのような表示や処理も端末の中で実現ができる。論理的な思考は、情報処理端末の中だけでも十分に育成できるだろう。しかし、プログラミングがもっと広く世界を変えうるものだと理解を深めるには、プログラムと外の世界との関わりを体験することが役に立つ。

プログラミング教育の教室を見てみよう。机の上には、パーソナルコンピュータやタブレットと、小さな電子回路基板やモーターといった電気部品のセットも並んでいる。タブレットの視覚的なプログラミング環境で、変数や論理構造を表す色とりどりのブロックを組み合わせて、プログラミングができる。いく種類ものブロックの中には、無線通信の接続や切断、デジタル・データの送信や受信機能を表すブロックもある。それらを組み合わせれば、例えば、タブレットに表示したボタンを押せば、その情報が無線通信でロボットに伝わり、ロボットを操縦できるアプリケーションが作れるだろう。


論理的な手続き、
イベント、データの変化が処理されて、ロボットの動きに反映される。無線通信技術はなんでも良い。
教育が目標で、論理的思考能力の習得と論理的思考で世界が変更できることの理解が成果物。教室の場では、教材に従って、より能力の高い子であればテキストエディタでプログラミング、教室の中でのコンテストやその発表を通じた切磋琢磨。

このタブレットとロボットの間の無線通信に、Bluetooth Low Energy技術が活用される。



無線通信はなんでもいい。論理的な思考で、作る物自体に何かを求めるわけではない。コンテストなど、楽しみや、より高い能力を行くいする専門コースなど、展開はあるだろうが。


図形を表示する、移動する、図形同士の衝突を判定、ボタンを押す、して、点数計算をする。
Bluetooth Low Energy技術は、プログラミング教育の教材に活用されている。
で活用されている教材を見てみよう。
ブロックの形、積み木。つならなり。
プログラミング言語、テキスト、色々な言語文法、if then elseやwhile文など制御文、を組み立てて。


成果物: 何か作ったもの、コンテスト、クラス内発表。個人の中に育てる論理的な思考力。長く続いていく中での1つ。
物理的に動かすもの、ロボット。
Arduino https://www.arduino.cc
micro:bit http://microbit.org
われわれの身の回りの物理的な世界とコンピュータ上の仮想的な世界との間に対話を作り出すという分野。ニューヨーク大学のITP (Interactive Telecommunication Program) で、Ｔ・ アイゴらを中心に教育プログラムとして開始された。既存のマウスやキーボード、ディスプレイ、スピーカーといった入出力装置に、センサー、アクチュエータ、マイクロコントローラを組み合わせ、人間とコンピュータとの意思疎通の幅を拡げることがフィジカル・コンピューティングの目的である。例えば、2005年にＭ・バンチらがI

教育を受ける側、教育プログラムを提供する側、教材やらを作ったり企画する側、道具として活用する側。
プログラミング教育とか。フィジカル・コンピューティング
理科教育の目的が、自然の観察と考察を通じて、その背後にある仕組みに気づき、とてもシンプルな法則で世界が成り立つことを理解する。プログラミング言語など、特定のスキルの表現取得。
人間は、みずみずしい感性を働かせながら、社会や人生をより良いも温位していくのななどの目的を考え出すことができ、その目的に応じた創造的な問題解決を行うことができるなどの強みを持っている。このような人間の強みを伸ばしていくことが、学校教育が。
便利な機械が、魔法の箱ではなく、プログラミングを通じて人間の意図した処理を行わせることができることを理解する
コーディング(プログラミング言語を用いた記述方法)を覚えることがプログラミング教育の目的であるとの誤解
コンピュータに意図した処理を行わせるために必要な論理的思考力を身につけるための学習活動
プログラミング的思考。
知能と思考、みじかな生活でコンピュータが活用されていることや、問題の解決には必要な手順があること。
学びに向かう人間性力、コンピュータの働きをより良い人生や社会づくりに生かそうとする態度の育成。
思考力判断力表現力。プログラミング的思考の育成。

// https://miraino-manabi.jp 小学校を中心としたプログラミング教育ポータル
// http://www.mext.go.jp/b_menu/shingi/chousa/shotou/122/attach/1372525.htm 小学校段階におけるプログラミング教育の在り方について（議論の取りまとめ）

// https://edtechzine.jp/article/detail/518

平成28年6月16日
micro:bit
// 2160円。
// http://microbit.org/ja/guide/
// Arduino rupppau@kindle.com 統合開発環境。ライブラリ。豊富なサンプル。いくつもの。サイト集約。書籍。

最初の具体的な実例と、どんなものかの中身:
micro:bit、ビジュアル開発環境、TypeScriptという静的型付き言語、サブセット。コードで書くこともできる。
それを機械語にして。
HEXファイルを、USBマスストレージ、BLE経由で。
JavaScriptのようなランタイムは、普通にコアを動かして、ブラウザと同じ方法では。動かないけど。
Arduino、独自のライブラリ。C++。仕組みは異なっていても、教材としては、使う流れは、大体は同じもの。

目標設定は、外からの設定、サンプルを通じて、プログラミングというスキルと考え方を習得すること:
時間軸では、何も手を加えず動かすこと、作るものを模写、真似ること、一部変更、分解と再組み立て。目標設定して組み立てる:
時間軸での役割: 最初は模倣者、分解して理解、スキルの向上、知識をもとにした発想(作れるはず)、作って動かして考える:
BLEそれ自体が教材。教材を作っている側がいる。視覚的なプログラミング環境、動かす例題。
手順は、サンプルを見て、動かす。変更して、いく。
目標設定は、最初は何ができるのかわからない。サンプル、仕組みを見る、仕組みに触る。次に、要素理解、組み立て、作りたいもの。その繰り返し。
拡散は、ネットで。作り方を。教材がベース。よいものであれば、コンテスト、あるいは競技。ロボット大会など。ネットで。
そのプログラミング。目に見える。情報を能動的に扱う手段、情報が形を変えて加工されていく仕組みを組み立てる、さらにそのシステムがある世界を作っていく。教育のベース。
通信規格の知識: なくていい。リモートで何かと何かが操作できる無線の何か。WiFiではなく? スマホから直接出せる便利さ。
たまたま教材として使えるものがあっただけで。価格、用途。

// 目標の設定と成果物
// 成果物に至る時間軸
// 時間軸での役割
// 通信規格の知識の関わり方。


3つの役割:
個人、教材。
チーム、開発。
マネージャ、運用管理。

全体のプランニング。プロデューサー。
作る過程を組み立てる人。マネージャー。
具体的に作る人。作業者。

作るもの、
作る時間軸、
果たす役割の時間軸。




//流れは。使う人=使う人か。今は使う人=作る人、でも作る人は増やすのか。
// 個人か、チームか
// 時間軸。ステップ。順番と時間のスケール。
// ==== 過程とゴールを想像する、場面の想像、立場的なもの ====
場面を想像する。

教育的なリソースで。PlayGroundで作る。アプリは、Pythonianでもいいかも。教材はMicro:bitやMbedを活用。Arduino。
スタートポイント、どちらも資料があり、色々な人の解説記事を探して。画面を見て操作する、リモートコントロール的なもの。
センサーの値をスマートホンの画面でかしか。データの蓄積や表示。リッチなスマートホンの活用。教育的には。つながった状態。


教材:
  要素: ハードウェア  アプリケーション
  両方作る。 つながった状態。  作る人=使う人 作って使い捨てるみたいな。
  使う人=作る人、作ったら分解して道具箱に戻す。作れる組み立てられる能力育成、考えて目標を達成すること、発展?


試作だと:
 要素: ハードウェア　アプリケーション
 実際に作らなくてもいい。ダンボールで、センサーの値を書いたもの。ボタンを押した操作、それを見て、黒子さんが。動画。
 体験を確認すること。でも実際に。コスト計算。
 作る人=思いついた人、ではない。

活動や心拍を記録する何か。+サービス。アプリケーション、ハードウェア、サーバ側。作る作らない、買う買わない。
将来の展開。胸ベルトのセンサーなら、どこかOEM。でも、独自の機能、例えば活動量も取れますとか。かなり一般的か。
デザインとか、腕時計型のデバイス。独自のデザイン。一生懸命開発することに。
通信、アプリケーションとの接続、ユーザ登録、破棄。サーバ側と合わせて。データは、気がついたら同期している。

サービス:
  要素: ハードウェア、ファームウェア、アプリケーション、サーバーサイド
  分担する。 つながったり、繋がらなかったり。  サポートし続ける。
技術分野、全体の組み立て(買うのか、開発するのか、技術と経営の全体からの判断)、スケジュールやお金、打ち合わせと連絡。


切り口がいっぱいある


必要な技能や分野。技術概要を共有する。活用方法を組み立てる。
作るものの構成：
