=== 放送そして通信へ ===

怒涛の真空管から半導体
通信設備と周波数割り当て

無線通信技術が実用化された現代では、放送や通信に使われる電磁波が飛び交っています。
各々が勝手に無秩序に電磁波を利用すると、混信したり通信妨害が生じてしまいます。
ですから、電磁波の利用を法律で決めなくてはなりません。

その電磁波の利用ルールを法律で決めなくてはなりませんが、

電磁波といっても、周波数で性質が全く異なります。

通信に使うものとして、周波数が300万メガヘルツ(メガは単位の前につける接頭辞で、$10^6を表す)以下の電磁波を、電波と呼びます。

光の速さは約毎秒30万キロメートルですから、電波は波長が0.1ミリメートルよりも長い電磁波とも言えます。可視光の波長は、おおよそ400ナノメートルから800ナノメートル(1ナノメートルは10^-9メートル)です。ですから、光は電磁波ですが、電波ではありません。



// 半球状に広がるものとして、表面積 2PI R^2, R=10km
// 家庭用電力 契約30Aとして3kW
// 3kW / 半球の表面積 = 4.8uW/m^2, 電子レンジ5つ分くらい。
// 畳1枚分の面積1.8m^2, 8.6uW/畳1枚分
// 1gの1円玉1mの高さから落としたとき、10mNx1m=10mJ
// 無線の電力はだいたい3桁違う。1/1000。
// ただし、8.6uWでZ=50ohmのときV^2/Z=8.6uWで、V=21mV


情報を伝える方法、0/1。究極のこれしかないでしょ。
送信側と受信側が必要。電線でも無線でも。
情報を持つものが強い、社会的に意味がある。それが使えるようになると、社会はそれを前提に再編成される。

ビットレートの問題。伝えられる情報量、物理的な力。
のちに述べる、1秒あたりどれほど速く変化させられるか。
1万RPM(1分間に1万回転、167回転)、1回転ごとに1ビットの情報量、167ビット/秒。

安定した電力、発電機。
半導体や電気回路、信号処理技術そしてデジタル化
放送、通信、デジタル。

アマチュア無線、国を超えて、資本。
自由に通信ができるホビー。無線機が購入できる時代になっても。投資額。

==== 無線通信技術の発展 ====

//まとめ
段階を踏んでいること。100年単位。
熱力学、物量
電気工学、電気エネルギー
電磁気学、無線、目に見えないところでの。情報、マス。
そして21世紀の、インターネットとか、デジタル化、通信。
生活が大きく変化。
ワイヤレス、有線。その原理。

==== 放送から通信そしてモバイル ====

トポロジー、設備の話。
情報を貯める技術。処理する話。


=== 無線の黎明期、放送の時代 ===
20世紀、むちゃくちゃ進歩した。

// 黎明期、電気回路ない時代。送信側と受信側は、前もって実験だから決めておける。
黎明期の無線通信、
ヘルツの説明を個々でしておく。
電荷の塊を手に持ってぐるぐる回しても、電磁波はでるはず。でも周波数的には? 1秒に1回が1Hz、高速に回転するエンジンでも1分間に1万回転、200Hzとかその程度。
太平洋横断、通信、受信機は金属の粉、電波を浴びると金属の粉が電磁波の影響で、電気抵抗が変化する。感度はとてつもなく低い。大きな発電機、その電力を空間に電波として大きなアンテナ。
黎明期。重力波。

電気回路、増幅素子、真空管、半導体、トランジスタの発明。電池で動く、ラジオ、テレビ。
放送。
// まとめ:
// 力ではなく波。周囲に広がっていくもの。
// パラメータは、周波数と強さ。誰が出しても電波は電波。
// 電波とは資源。四方八方に広がっていく
// 形があるもので運用されていた社会が、形のないもので運用されるように。
// 薪や石炭、電気エネルギー。手紙から、電信電話。通信。


==== 利用の発展、電波の性質とあわせて ====

電波、周波数
「電波」とは、三百万メガヘルツ以下の周波数の電磁波をいう。
3テラヘルツ
0.1ミリメートル
毎秒30万キロメートル

// 電気回路と素子の急速な発展。半導体。制御できるのと小型化。一気に産業化。
// まずは放送の普及。エリアで。多様性はない。インフラとしての。放送、ソフト、コンテンツ
// でっかい放送局の設備、電波資源の割当。変調信号=方式。全体が1つのシステム。マス。
ラジオ、糸電話みたいなもの。テレビ、画像をアナログ信号に変換して。エリア。9kHz間隔(占有周波数帯幅の許容値は15kHz, AM:7.5kHz, 上下)
短波放送。地球全体に届く。国際的な周波数の割当調整の組織。

// テレビ放送
画像をアナログ信号に変換する方法。耳で聞くものとは違い、とても工学的なもの。
より高い周波数。1つの放送あたり, NTSC 6MHz

// これの形は。
電波が割当(ライセンスドバンド)。混信しては困るので、免許制とか。
独占事業になったりしないように。投資をして放送局を作って。
なので新規放送局とかはきつい。広告で収益源。放送していることで収益。

// まとめ:
// 周波数がある。伝わる性質が違う。短波の発見。国際的な周波数の割当調整。
// 放送局みたいなのが必要なものが、今までの歴史。かなり大きなお金が動く話(鈍足)
// 放送なので、誰でも聞ける。(スクランブルとかで収益もできるけど。広域は公共性)
// 広告による収益モデル。新聞社とかと違って。不動産的な強い立場。配線とかいらない。
// 複合産業。受像機、放送設備。放送コンテンツ。広告

=== 電波の活用 ===
振幅変調と周波数変調。どっちがどっちというわけではないけど、周波数変調、強し。
通信路符号化の考え方。

// 携帯電話
音声通話の無線化。

// デジタル化
// 大切なポイント: 通信とその意味が、分離できる。デジタル通信+デジタルの活用
0と1のデータのあつまり。それが何を意味するかは。
インターネット、モバイル。



// デジタル化
// デジタル化でデータ化、信号そのものが音声、デジタル信号、とりあえず送って解釈
// なので、データの解釈(符号化、復号化)とかとっても重要。
// デジタル化しちゃうと、上の部分をいれかえたら、いろんなものに使える。汎用的。

// 黎明期はごっつかったのが、小さく電池駆動になったのは、真空管から半導体の流れ
// 電磁気学の話


// 電磁波の理論と実証、そして利用
電磁波の理論。時間の変化が作れる、理論的に、電圧の、時間変化。
音が空気の圧力と運動エネルギーを交換しながら疎密波として

ヘルツ。電気を帯びたものをぐるぐる手で回しても、微弱な電磁波が出ているはず。
1秒に1回、1Hz、いちヘルツ。あまりに微弱。

太平洋横断、家庭の20軒分くらいの電力の発電機と、電力を空間に電磁波として送り出す巨大なアンテナ、受信装置が金属の粉を詰めたようなもの、電磁波の検出能力は高くない、送信電力を巨大にするしかなかった。パイオニア、世界で誰でもできることではないから。

// アナログからデジタルになって、ずんどこ意味が変わった。放送から通信へ
// 現在の利用
真空管および半導体素子の発明が、劇的に。高周波を操れる、微弱な受信信号を増幅して、信号を処理して。
ラジオ。糸電話の強弱、電波の強弱。
テレビ。動画像をアナログ信号に変換して、それを電波の強弱や周波数の高低。

// 周波数がとても大切。帯域、情報を伝える速度は帯域で。伝わるのは周波数の性質。
短波、2.4GHz、

// 周波数はとても大切なので、公共の資源。国が管理して、割当したり、オークションしたり

// 身の回りのもののネットワーク
// 基地局(誰かが作るもの、ライセンスバンド)+装置
// 基地局(自前)+装置 アンライセンスドバンド
// WiFi的なものとかスマートホン+装置


==== 放送から通信へ、そしてデジタルへ ====

空間の帯域。放送であれば、例えば6MHzの帯域１つ。個人個人で通信、別のもの。100人が1MHzの帯域を必要とする=100MHz。桁違い。桁が違う=技術革新が必要。半導体技術、デジタル信号処理、デジタル回路、それらの複合的な桁違いの進歩。ムーアの法則。

// 電子回路の発展にしたがい、高度化。特にデジタル化は通信を抽象化する大きな転換
// 放送と違い、音声通話のモバイル化、そしてデジタル化。放送ではなく通信。
周波数が高い、広い帯域を割り当てやすい、高速な通信。アンテナが小さくてよい。
~100MHzまでの世界。からGHｚへの世界。

吸収されやすい、見通し範囲でしか届かなくなる。~ GHz。
高密度に収容。同じ周波数で沢山の人が同時に通信したら混信。電波が届かない、空間で分割。

//=== 帯域の話 ==
// 帯域、情報
情報を伝える、例えばピアノの鍵盤。ドの音のある無し。次のオクターブ離れたドの音。人間の耳では、分別困難、聞き分けられない。フィルタ。ドの横にあるレの音、もっと近づいたら。やっぱり分別できない。これは音の成分が純粋なドの音だけじゃないから。音の立ち上がりや立ち下がりに近くのレや1つしたのシの音の成分がどうしても混じる。原理的なもの。

情報を伝えようとすると、ある程度の周波数の幅が必要。例えば、ラジオであれば。人間の音声4kHzの幅 (実際には9kHz幅で割当)。テレビであれば、6MHz。帯域。その領域で6MHzの電波、広く伝われば良い放送。

通信は。一人ひとりとのやりとり。なので人数分必要。
テレビ放送に使っているVHFやUHF、~400MHz。

// まとめ:
// デジタル化は、通信とコンテンツを分離できる。アプリケーションが大きな比重。
// 放送と違い通信には、非常に高速な通信帯域が必要。速度と収納人数。
// 高い周波数、半導体とデジタルの技術
// 通信それ自体に、お金を払う理由が必要。インターネット。
// ちょうどネット世界の放送の立場。放送設備はなくてもコンテンツを無償でブロードキャスト
// 電波資源や放送局を作らなくても、誰でもコンテンツを出してサービスを作ることができる。
// 選択。超参入容易。
放送の方式と、その上に乗っかるデータの形式。ただ受像機の装置としての性質があるので、
固定した技術で、固定した目的。それでも相互通信やアプリなど、デジタルだからできる工夫がある。

// まとめ
時間の流れの中で、電磁波が発見されて、それが高度な技術で、小さな電力で。
デジタル化で、通信とデータの意味が分離された。



=== 通信、モバイル、そして ===
今の社会、人間、スマートホン、インターネット(どこかにあるサーバ)。
スマートホンの先にあるもの、通信のあれこれは気にする必要はない。キャリア。

構成:
1つは基地局的なもの。多数を収納する、費用分担。専門家。電波の割当。公共性。
1つは自分が基地局を作るもの。WiFiとか。モバイル? 電波の届く範囲。広げたりしない。
1つは、ハブとなるデバイス。スマホ+BLEのタイプ。持ち歩き。

==== 無線通信の使われ方キーワード ====

提供される形態:
事業者の回線それぞれを中継して、全体として1つの大きなネットワークを作っている。
インターネットサービスプロバイダ。ネットワーク間をつなぐ技術。光ファイバーなど。
通信、個人利用。帯域、時間幅。基地局。無線LAN。有線までつなぐ自家。
空間の広がり。四方八方。基地局のカバーエリア。自家用、家で使える。
SIMカード、認証、月額。

==== アプセサリ ====
// Windows時代はデバイスドライバ+ハード+アプリ。一般的なキーボードとか。
// モバイルの時代、慣習が違う。
// BLEみたいなものは、身の回りのささいなものに無線機能。+アプリ。
// スマホ+デバイス。アプリケーション次第で別のものになる。
// フィットネス。万歩計であれば300円。サービスとして、グラフ、蓄積、共有。
// 仲間内で自慢したい、自分でわざわざ、共有ボタンが有る、そういうものだ。
// 口コミ商品サービス。また消耗品、モデルチェンジ。ハードウェアのみが売上。
// フィットネスは成功例として稀有。習慣づけ、ハードウェア、ハードを通じたサービス。
// 黎明期, 商売が成り立ちうる。
// 収益源(ハード、サービス)、体験(個人的なものかソーシャル的なものか)

=== モノのインターネット ===
// どういうものかは、広い分野。
// ご家庭: 家電が自動的に連携 (だめな例)
// 産業: 情報であれこれ管理とか。(だめな例)
// 飛行機のエンジンのサブスクリプション。
// 同じお金でより多くを得る、という工夫ではなく、つながりつづける、という前提で
// ビジネスの形を換えてしまう。通信だけじゃなくて、故障や整備、予測技術。課金とか。

// BLEの使われ方。スマホ、周辺機器、インターネットとのつながりを意識した、別の仕組み。
// 無線でつながる機能、その上に色々な仕組み。IPを取り入れ、CoAP、MQTTプロトコル。

=== モノのインターネットでの接続状態 ===
最後の1メートル。
人相手の通信とは声質が違う:
必要なのは。製造の低コスト、超低消費電力(電池交換めんどくさい)、
やり取りするデータはむちゃ少ない上に間欠的。常に目で見ているわけじゃないし、送らねばならぬそれほどデータ量があるわけでもない。

構造と課金、設備。インターネットまでの距離。
クラウドありき。IPリーチアブル。パケットが届く範囲。物理的に。

- ハブを自分で作る (アンライセンスド)
  - WiFiルータ的な。電力的に違う無線通信技術。LoRaなど。
- ハブはすでにある
  - NB-IoTなど。パケット課金。
BLE。デバイス、スマホ(wifi)
